export const words = {
    "verbIchidan": [
        {"kanji":"居<rt>い<\/rt>る","type":"ru","eng":"to be, to exist", "kana":"いる"},
        {"kanji":"始<rt>はじ<\/rt>める","type":"ru","eng":"to begin", "kana":"はじめる"},
        {"kanji":"借<rt>か<\/rt>りる","type":"ru","eng":"to borrow", "kana":"かりる"},
        {"kanji":"続<rt>つづ<\/rt>ける","type":"ru","eng":"to continue, to proceed", "kana":"つづける"},
        {"kanji":"決<rt>き<\/rt>める","type":"ru","eng":"to decide", "kana":"きめる"},
        {"kanji":"食<rt>た<\/rt>べる","type":"ru","eng":"to eat", "kana":"たべる"},
        {"kanji":"忘<rt>わす<\/rt>れる","type":"ru","eng":"to forget", "kana":"わすれる"},
        {"kanji":"降<rt>お<\/rt>りる","type":"ru","eng":"to get off (a vehicle)", "kana":"おりる"},
        {"kanji":"下<rt>お<\/rt>りる","type":"ru","eng":"to come down", "kana":"おりる"},
        {"kanji":"疲<rt>つか<\/rt>れる","type":"ru","eng":"to get tired", "kana":"つかれる"},
        {"kanji":"起<rt>お<\/rt>きる","type":"ru","eng":"to get up, to wake up", "kana":"おきる"},
        {"kanji":"出<rt>で<\/rt>る","type":"ru","eng":"to leave, to exit", "kana":"でる"},
        {"kanji":"助<rt>たす<\/rt>ける","type":"ru","eng":"to help", "kana":"たすける"},
        {"kanji":"見<rt>み<\/rt>る","type":"ru","eng":"to see, to look", "kana":"みる"},
        {"kanji":"開<rt>あ<\/rt>ける","type":"ru","eng":"to open", "kana":"あける"},
        {"kanji":"上<rt>あ<\/rt>げる","type":"ru","eng":"to give", "kana":"あげる"},
        {"kanji":"覚<rt>おぼ<\/rt>える","type":"ru","eng":"to remember", "kana":"おぼえる"},
        {"kanji":"寝<rt>ね<\/rt>る","type":"ru","eng":"to sleep", "kana":"ねる"},
        {"kanji":"眠<rt>ねむ<\/rt>る","type":"ru","eng":"to fall asleep", "kana":"ねむる"},
        {"kanji":"閉<rt>し<\/rt>める","type":"ru","eng":"to close", "kana":"しめる"},
        {"kanji":"着<rt>き<\/rt>る","type":"ru","eng":"to put on, to wear (shirt, jacket, etc.)", "kana":"きる"},
        {"kanji":"信<rt>しん<\/rt>じる","type":"ru","eng":"to believe, to place faith (in)", "kana":"しんじる"},
        {"kanji":"越<rt>こ<\/rt>える","type":"ru","eng":"to exceed, to go beyond", "kana":"こえる"},
        {"kanji":"流<rt>なが<\/rt>れる","type":"ru","eng":"to flow, to stream, to drift, to pass", "kana":"ながれる"},
        {"kanji":"出来<rt>でき<\/rt>る","type":"ru","eng":"to be able to (do)", "kana":"できる"},
        {"kanji":"浴<rt>あ<\/rt>びる","type":"ru","eng":"to take a shower, to bathe in", "kana":"あびる"},
        {"kanji":"付<rt>つ<\/rt>ける","type":"ru","eng":"to attach, to join", "kana":"つける"},
        {"kanji":"止<rt>と<\/rt>める","type":"ru","eng":"to stop", "kana":"とめる"},
        {"kanji":"褒<rt>ほ<\/rt>める","type":"ru","eng":"to praise, to commend", "kana":"ほめる"},
        {"kanji":"濡<rt>ぬ<\/rt>れる","type":"ru","eng":"to get wet", "kana":"ぬれる"},
        {"kanji":"終<rt>お<\/rt>える","type":"ru","eng":"to finish", "kana":"おえる"},
        {"kanji":"感<rt>かん<\/rt>じる","type":"ru","eng":"to feel", "kana":"かんじる"},
        {"kanji":"現<rt>あらわ<\/rt>れる","type":"ru","eng":"to appear, to come out", "kana":"あらわれる"},
        {"kanji":"離<rt>はな<\/rt>れる","type":"ru","eng":"to be separated, to be apart, to leave", "kana":"はなれる"},
        {"kanji":"恐<rt>おそ<\/rt>れる","type":"ru","eng":"to fear, to be afraid of", "kana":"おそれる"},
        {"kanji":"備<rt>そな<\/rt>える","type":"ru","eng":"to equip with, to prepare", "kana":"そなえる"},
        {"kanji":"燃<rt>も<\/rt>える","type":"ru","eng":"to burn, to get fired up", "kana":"もえる"},
        {"kanji":"乗<rt>の<\/rt>せる","type":"ru","eng":"to place on (something), to give (someone) a ride", "kana":"のせる"},
        {"kanji":"閉<rt>と<\/rt>じる","type":"ru","eng":"to close, to shut", "kana":"とじる"},
        {"kanji":"合<rt>あ<\/rt>わせる","type":"ru","eng":"to match (rhythm, speed)", "kana":"あわせる"},
        {"kanji":"命<rt>めい<\/rt>じる","type":"ru","eng":"to order, to command", "kana":"めいじる"},
        {"kanji":"分<rt>わ<\/rt>ける","type":"ru","eng":"to divide (into), to split, to differentiate (between)", "kana":"わける"},
        {"kanji":"確<rt>たし<\/rt>かめる","type":"ru","eng":"to check, to verify", "kana":"たしかめる"},
        {"kanji":"加<rt>くわ<\/rt>える","type":"ru","eng":"to add, to increase", "kana":"くわえる"},
        {"kanji":"当<rt>あ<\/rt>てる","type":"ru","eng":"to hit", "kana":"あてる"},
        {"kanji":"眺<rt>なが<\/rt>める","type":"ru","eng":"to stare at, to watch, to get a view of", "kana":"ながめる"},
        {"kanji":"抱<rt>かか<\/rt>える","type":"ru","eng":"to hold in one's arms, to shoulder, to be burdened with", "kana":"かかえる"},
        {"kanji":"数<rt>かぞ<\/rt>える","type":"ru","eng":"to count", "kana":"かぞえる"},
        {"kanji":"替<rt>か<\/rt>える","type":"ru","eng":"to replace, to exchange, to substitute", "kana":"かえる"},
        {"kanji":"与<rt>あた<\/rt>える","type":"ru","eng":"to bestow, to grant", "kana":"あたえる"},
        {"kanji":"求<rt>もと<\/rt>める","type":"ru","eng":"to want, to wish for, to request, to seek", "kana":"もとめる"},
        {"kanji":"認<rt>みと<\/rt>める","type":"ru","eng":"to recognize, to acknowledge, to approve of", "kana":"みとめる"},
        {"kanji":"向<rt>む<\/rt>ける","type":"ru","eng":"to face, to point toward", "kana":"むける"},
        {"kanji":"避<rt>さ<\/rt>ける","type":"ru","eng":"to avoid", "kana":"さける"},
        {"kanji":"諦<rt>あきら<\/rt>める","type":"ru","eng":"to give up", "kana":"あきらめる"},
        {"kanji":"触<rt>ふ<\/rt>れる","type":"ru","eng":"to touch, to feel", "kana":"ふれる"},
        {"kanji":"解<rt>と<\/rt>ける","type":"ru","eng":"to be solved", "kana":"とける"},
        {"kanji":"辞<rt>や<\/rt>める","type":"ru","eng":"to give up on, to retire, to quit", "kana":"やめる"},
        {"kanji":"勧<rt>すす<\/rt>める","type":"ru","eng":"to recommend, to advise", "kana":"すすめる"},
        {"kanji":"責<rt>せ<\/rt>める","type":"ru","eng":"to condemn, to blame, to criticize", "kana":"せめる"},
    ],
    "verbす": [
        {"kanji":"話<rt>はな<\/rt>す","type":"u","eng":"to speak", "kana":"はなす"},
        {"kanji":"返<rt>かえ<\/rt>す","type":"u","eng":"to return (something), to put back", "kana":"かえす"},
        {"kanji":"押<rt>お<\/rt>す","type":"u","eng":"to push, to press", "kana":"おす"},
        {"kanji":"治<rt>なお<\/rt>す","type":"u","eng":"to cure, to repair", "kana":"なおす"},
        {"kanji":"直<rt>なお<\/rt>す","type":"u","eng":"to correct", "kana":"なおす"},
        {"kanji":"探<rt>さが<\/rt>す","type":"u","eng":"to search, to look for", "kana":"さがす"},
        {"kanji":"貸<rt>か<\/rt>す","type":"u","eng":"to lend, to loan", "kana":"かす"},
        {"kanji":"過<rt>す<\/rt>ごす","type":"u","eng":"to spend (time)", "kana":"すごす"},
        {"kanji":"出<rt>だ<\/rt>す","type":"u","eng":"to take out, to get out, to show", "kana":"だす"},
        {"kanji":"渡<rt>わた<\/rt>す","type":"u","eng":"to carry across, to traverse", "kana":"わたす"},
        {"kanji":"無<rt>な<\/rt>くす","type":"u","eng":"to lose (something)", "kana":"なくす"},
        {"kanji":"消<rt>け<\/rt>す","type":"u","eng":"to erase, to turn off (a light), to extinguish", "kana":"けす"},
        {"kanji":"落<rt>お<\/rt>とす","type":"u","eng":"to drop", "kana":"おとす"},
        {"kanji":"壊<rt>こわ<\/rt>す","type":"u","eng":"to break, to destroy", "kana":"こわす"},
        {"kanji":"写<rt>うつ<\/rt>す","type":"u","eng":"to copy, to transcribe", "kana":"うつす"},
        {"kanji":"沸<rt>わ<\/rt>かす","type":"u","eng":"to boil, to heat", "kana":"わかす"},
        {"kanji":"足<rt>た<\/rt>す","type":"u","eng":"to add (numbers)", "kana":"たす"},
        {"kanji":"許<rt>ゆる<\/rt>す","type":"u","eng":"to permit, to allow, to forgive", "kana":"ゆるす"},
        {"kanji":"残<rt>のこ<\/rt>す","type":"u","eng":"to leave (behind), to set aside", "kana":"のこす"},
        {"kanji":"隠<rt>かく<\/rt>す","type":"u","eng":"to hide, to conceal", "kana":"かくす"},
        {"kanji":"殺<rt>ころ<\/rt>す","type":"u","eng":"to kill", "kana":"ころす"},
        {"kanji":"動<rt>うご<\/rt>かす","type":"u","eng":"to move (something), to rouse, to operate", "kana":"うごかす"},
        {"kanji":"回<rt>まわ<\/rt>す","type":"u","eng":"to turn, to rotate", "kana":"まわす"},
        {"kanji":"戻<rt>もど<\/rt>す","type":"u","eng":"to put back, to return, to restore (to a previous state)", "kana":"もどす"},
        {"kanji":"流<rt>なが<\/rt>す","type":"u","eng":"to drain, to shed (blood, tears), to wash away", "kana":"ながす"},
        {"kanji":"倒<rt>たお<\/rt>す","type":"u","eng":"to beat, to defeat (e.g. an opponent, a boss)", "kana":"たおす"},
        {"kanji":"表<rt>あらわ<\/rt>す","type":"u","eng":"to express, to represent, to signify, to show", "kana":"あらわす"},
        {"kanji":"伸<rt>の<\/rt>ばす","type":"u","eng":"to grow long (e.g. hair, nails)", "kana":"のばす"},
        {"kanji":"<ruby>思<rt>おも</rt></ruby>い<ruby>出<rt>だ</rt></ruby>す","type":"u","eng":"to recall, to remember", "kana":"おもいだす"},
        {"kanji":"<ruby>引<rt>ひ</rt></ruby>っ<ruby>超<rt>こ</rt></ruby>す","type":"u","eng":"to move (house)", "kana":"ひっこす"},
        {"kanji":"<ruby>引<rt>ひ</rt></ruby>き<ruby>出<rt>だ</rt></ruby>す","type":"u","eng":"to pull out, to take out", "kana":"ひきだす"},
        {"kanji":"<ruby>繰<rt>く</rt></ruby>り<ruby>返<rt>かえ</rt></ruby>す","type":"u","eng":"to do again, to repeat", "kana":"くりかえす"},
        {"kanji":"<ruby>飛<rt>と</rt></ruby>び<ruby>出<rt>だ</rt></ruby>す","type":"u","eng":"to jump out, to fly out", "kana":"とびだす"},
    ],
    "verbく": [
        {"kanji":"続<rt>つづ<\/rt>く","type":"u","eng":"to continue, to proceed", "kana":"つづく"},
        {"kanji":"開<rt>ひら<\/rt>く","type":"u","eng":"to open", "kana":"ひらく"},
        {"kanji":"泳<rt>およ<\/rt>ぐ","type":"u","eng":"to swim", "kana":"およぐ"},
        {"kanji":"聞<rt>き<\/rt>く","type":"u","eng":"to hear, to listen", "kana":"きく"},
        {"kanji":"引<rt>ひ<\/rt>く","type":"u","eng":"to pull", "kana":"ひく"},
        {"kanji":"響<rt>ひび<\/rt>く","type":"u","eng":"to resound, to reverbrate", "kana":"ひびく"},
        {"kanji":"届<rt>とど<\/rt>く","type":"u","eng":"to reach, to get to, to be delivered", "kana":"とどく"},
        {"kanji":"履<rt>は<\/rt>く","type":"u","eng":"to put on (pants, skirt, shoes, etc.)", "kana":"はく"},
        {"kanji":"歩<rt>ある<\/rt>く","type":"u","eng":"to walk", "kana":"あるく"},
        {"kanji":"書<rt>か<\/rt>く","type":"u","eng":"to write", "kana":"かく"},
        {"kanji":"働<rt>はたら<\/rt>く","type":"u","eng":"to work", "kana":"はたらく"},
        {"kanji":"脱<rt>ぬ<\/rt>ぐ","type":"u","eng":"to undress", "kana":"ぬぐ"},
        {"kanji":"急<rt>いそ<\/rt>ぐ","type":"u","eng":"to hurry", "kana":"いそぐ"},
        {"kanji":"稼<rt>かせ<\/rt>ぐ","type":"u","eng":"to earn income, to make money", "kana":"かせぐ"},
        {"kanji":"寛<rt>くつろ<\/rt>ぐ","type":"u","eng":"to relax, to feel at home", "kana":"くつろぐ"},
        {"kanji":"繋<rt>つな<\/rt>ぐ","type":"u","eng":"to connect, to link together", "kana":"つなぐ"},
        {"kanji":"着<rt>つ<\/rt>く","type":"u","eng":"to arrive at", "kana":"つく"},
        {"kanji":"付<rt>つ<\/rt>く","type":"u","eng":"to be attached", "kana":"つく"},

        {"kanji":"置<rt>お<\/rt>く","type":"u","eng":"to place, to put, to leave (something) behind", "kana":"おく"},
        {"kanji":"弾<rt>ひ<\/rt>く","type":"u","eng":"to play (a stringed or keyboard instrument), to pluck", "kana":"ひく"},
        {"kanji":"吹<rt>ふ<\/rt>く","type":"u","eng":"to blow, to play (a wind instrument)", "kana":"ふく"},
        {"kanji":"咲<rt>さ<\/rt>く","type":"u","eng":"to bloom, to flower", "kana":"さく"},
        {"kanji":"磨<rt>みが<\/rt>く","type":"u","eng":"to polish, to shine, to refine, to improve", "kana":"みがく"},
        {"kanji":"泣<rt>な<\/rt>く","type":"u","eng":"to cry, to sob", "kana":"なく"},
        {"kanji":"鳴<rt>な<\/rt>く","type":"u","eng":"to call, to cry, to whine, to make animal noises, to chirp", "kana":"なく"},
        {"kanji":"驚<rt>おどろ<\/rt>く","type":"u","eng":"to be surprised, to be astonished", "kana":"おどろく"},
        {"kanji":"焼<rt>や<\/rt>く","type":"u","eng":"to burn, to roast, to broil, to grill, to bake, to toast, to heat, to tan", "kana":"やく"},
        {"kanji":"乾<rt>かわ<\/rt>く","type":"u","eng":"to get dry", "kana":"かわく"},
        {"kanji":"気<rt>き<\/rt>づく","type":"u","eng":"to notice, to realize", "kana":"きづく"},
        {"kanji":"解<rt>と<\/rt>く","type":"u","eng":"to untie, to unfasten, to undo, to solve (e.g. a question), to answer", "kana":"とく"},
        {"kanji":"描<rt>えが<\/rt>く","type":"u","eng":"to draw, to paint", "kana":"えがく"},
        {"kanji":"効<rt>き<\/rt>く","type":"u","eng":"to be effective, to take effect, to work", "kana":"きく"},
        {"kanji":"輝<rt>かがや<\/rt>く","type":"u","eng":"to shine, to sparkle, to twinkle, to glitter", "kana":"かがやく"},
        {"kanji":"基<rt>もと<\/rt>づく","type":"u","eng":"to be based (on), to be founded (on), to be grounded (on)", "kana":"もとづく"},
        {"kanji":"向<rt>む<\/rt>く","type":"u","eng":"to turn toward, to face", "kana":"むく"},
        {"kanji":"抜<rt>ぬ<\/rt>く","type":"u","eng":"to pull out, to extract, to omit, to leave out", "kana":"ぬく"},
        {"kanji":"除<rt>のぞ<\/rt>く","type":"u","eng":"to exclude, to remove, to eliminate", "kana":"のぞく"},
        {"kanji":"拭<rt>ふ<\/rt>く","type":"u","eng":"to wipe, to dry", "kana":"ふく"},
        {"kanji":"浮<rt>う<\/rt>く","type":"u","eng":"to float", "kana":"うく"},
        {"kanji":"<ruby>立<rt>た</rt></ruby>ち<ruby>退<rt>の</rt></ruby>く","type":"u","eng":"to evacuate, to vacate", "kana":"たちのく"},
        {"kanji":"<ruby>追<rt>お</rt></ruby>い<ruby>付<rt>つ</rt></ruby>く","type":"u","eng":"to catch up (with), to pull even, to be compensated, to make up for one's losses", "kana":"おいつく"},
        {"kanji":"<ruby>落<rt>お</rt></ruby>ち<ruby>着<rt>つ</rt></ruby>く","type":"u","eng":"to calm down, to compose oneself, to relax", "kana":"おちつく"},
        {"kanji":"<ruby>思<rt>おも</rt></ruby>い<ruby>付<rt>つ</rt></ruby>く","type":"u","eng":"to think of, to come across one's mind", "kana":"おもいつく"},
        {"kanji":"騒<rt>さわ<\/rt>ぐ","type":"u","eng":"to make noise, to be noisy", "kana":"さわぐ"},
        {"kanji":"防<rt>ふせ<\/rt>ぐ","type":"u","eng":"to prevent against, to prevent", "kana":"ふせぐ"},
    ],
    "verbむ": [
        {"kanji":"住<rt>す<\/rt>む","type":"u","eng":"to live (in)", "kana":"すむ"},
        {"kanji":"飛<rt>と<\/rt>ぶ","type":"u","eng":"to fly", "kana":"とぶ"},
        {"kanji":"死<rt>し<\/rt>ぬ","type":"u","eng":"to die", "kana":"しぬ"},
        {"kanji":"飲<rt>の<\/rt>む","type":"u","eng":"to drink", "kana":"のむ"},
        {"kanji":"楽<rt>たの<\/rt>しむ","type":"u","eng":"to enjoy, to have fun", "kana":"たのしむ"},
        {"kanji":"進<rt>すす<\/rt>む","type":"u","eng":"to advance, to go forward", "kana":"すすむ"},
        {"kanji":"読<rt>よ<\/rt>む","type":"u","eng":"to read", "kana":"よむ"},
        {"kanji":"休<rt>やす<\/rt>む","type":"u","eng":"to rest", "kana":"やすむ"},
        {"kanji":"包<rt>つつ<\/rt>む","type":"u","eng":"to wrap up, to cover, to envelop", "kana":"つつむ"},
        {"kanji":"遊<rt>あそ<\/rt>ぶ","type":"u","eng":"to play, to hang out", "kana":"あそぶ"},
        {"kanji":"学<rt>まな<\/rt>ぶ","type":"u","eng":"to study, to learn", "kana":"まなぶ"},
        {"kanji":"選<rt>えら<\/rt>ぶ","type":"u","eng":"to choose, to select", "kana":"えらぶ"},
        {"kanji":"頼<rt>たの<\/rt>む","type":"u","eng":"to request, to ask, to order (food)", "kana":"たのむ"},
        {"kanji":"盗<rt>ぬす<\/rt>む","type":"u","eng":"to steal, to plagiarize", "kana":"ぬすむ"},
        {"kanji":"踏<rt>ふ<\/rt>む","type":"u","eng":"to step on, to trample on, to set foot on (e.g. new land)", "kana":"ふむ"},
        {"kanji":"止<rt>や<\/rt>む","type":"u","eng":"to cease, to stop", "kana":"やむ"},
        {"kanji":"済<rt>す<\/rt>む","type":"u","eng":"to finish, to end, to be completed", "kana":"すむ"},
        {"kanji":"込<rt>こ<\/rt>む","type":"u","eng":"to be crowded, to be congested", "kana":"こむ"},
        {"kanji":"噛<rt>か<\/rt>む","type":"u","eng":"to bite", "kana":"かむ"},
        {"kanji":"望<rt>のぞ<\/rt>む","type":"u","eng":"to desire, to hope, to wish for", "kana":"のぞむ"},
        {"kanji":"好<rt>この<\/rt>む","type":"u","eng":"to like, to prefer", "kana":"このむ"},
        {"kanji":"囲<rt>かこ<\/rt>む","type":"u","eng":"to surround, to encircle, to wall in, to lay siege to", "kana":"かこむ"},
        {"kanji":"悩<rt>なや<\/rt>む","type":"u","eng":"to be worried, to be troubled", "kana":"なやむ"},
        {"kanji":"悲<rt>かな<\/rt>しむ","type":"u","eng":"to be sad, to mourn", "kana":"かなしむ"},
        {"kanji":"苦<rt>くる<\/rt>しむ","type":"u","eng":"to suffer", "kana":"くるしむ"},
        {"kanji":"<ruby>申<rt>もう</rt></ruby>し<ruby>込<rt>こ</rt></ruby>む","type":"u","eng":"to apply for, to propose", "kana":"もうしこむ"},
        {"kanji":"呼<rt>よ<\/rt>ぶ","type":"u","eng":"to call, to summon", "kana":"よぶ"},
        {"kanji":"並<rt>なら<\/rt>ぶ","type":"u","eng":"to be in line", "kana":"ならぶ"},
        {"kanji":"喜<rt>よろこ<\/rt>ぶ","type":"u","eng":"to be pleased", "kana":"よろこぶ"},
        {"kanji":"運<rt>はこ<\/rt>ぶ","type":"u","eng":"to carry, to transport", "kana":"はこぶ"},
        {"kanji":"結<rt>むす<\/rt>ぶ","type":"u","eng":"to tie, to link, to connect, to bear (e.g. fruit)", "kana":"むすぶ"},
        {"kanji":"転<rt>ころ<\/rt>ぶ","type":"u","eng":"to fall down, to fall over", "kana":"ころぶ"},
        {"kanji":"叫<rt>さけ<\/rt>ぶ","type":"u","eng":"to shout, to scream", "kana":"さけぶ"},
    ],
    "verbう": [
        {"kanji":"歌<rt>うた<\/rt>う","type":"u","eng":"to sing", "kana":"うたう"},
        {"kanji":"成<rt>な<\/rt>る","type":"u","eng":"to become", "kana":"なる"},
        {"kanji":"乗<rt>の<\/rt>る","type":"u","eng":"to board, to ride", "kana":"のる"},
        {"kanji":"掛<rt>か<\/rt>かる","type":"u","eng":"to hang", "kana":"かかる"},
        {"kanji":"喋<rt>しゃべ<\/rt>る","type":"u","eng":"to talk, to chat", "kana":"しゃべる"},
        {"kanji":"走<rt>はし<\/rt>る","type":"u","eng":"to run", "kana":"はしる"},
        {"kanji":"過<rt>す<\/rt>ぎる","type":"u","eng":"to pass (of time)", "kana":"すぎる"},
        {"kanji":"切<rt>き<\/rt>る","type":"u","eng":"to cut", "kana":"きる"},
        {"kanji":"太<rt>ふと<\/rt>る","type":"u","eng":"to get fat, to gain weight", "kana":"ふとる"},
        {"kanji":"終<rt>お<\/rt>わる","type":"u","eng":"to end", "kana":"おわる"},
        {"kanji":"上<rt>あ<\/rt>がる","type":"u","eng":"to go up, to rise", "kana":"あがる"},
        {"kanji":"上<rt>のぼ<\/rt>る","type":"u","eng":"to climb, to ascend", "kana":"のぼる"},
        {"kanji":"知<rt>し<\/rt>る","type":"u","eng":"to know, to be aware (of)", "kana":"しる"},
        {"kanji":"作<rt>つく<\/rt>る","type":"u","eng":"to make, to build", "kana":"つくる"},
        {"kanji":"帰<rt>かえ<\/rt>る","type":"u","eng":"to return, to go home", "kana":"かえる"},
        {"kanji":"取<rt>と<\/rt>る","type":"u","eng":"to take", "kana":"とる"},
        {"kanji":"無<rt>な<\/rt>くなる","type":"u","eng":"to be lost, to be used up, to be spent", "kana":"なくなる"},
        {"kanji":"亡<rt>な<\/rt>くなる","type":"u","eng":"to pass away", "kana":"なくなる"},
        {"kanji":"染<rt>そ<\/rt>まる","type":"u","eng":"to be dyed", "kana":"そまる"},
        {"kanji":"買<rt>か<\/rt>う","type":"u","eng":"to buy", "kana":"かう"},
        {"kanji":"笑<rt>わら<\/rt>う","type":"u","eng":"to laugh, to smile", "kana":"わらう"},
        {"kanji":"会<rt>あ<\/rt>う","type":"u","eng":"to meet", "kana":"あう"},
        {"kanji":"言<rt>い<\/rt>う","type":"u","eng":"to say, to utter", "kana":"いう"},
        {"kanji":"思<rt>おも<\/rt>う","type":"u","eng":"to think", "kana":"おもう"},
        {"kanji":"使<rt>つか<\/rt>う","type":"u","eng":"to use", "kana":"つかう"},
        {"kanji":"奪<rt>うば<\/rt>う","type":"u","eng":"to steal, to take away", "kana":"うばう"},
        {"kanji":"持<rt>も<\/rt>つ","type":"u","eng":"to hold, to have", "kana":"もつ"},
        {"kanji":"待<rt>ま<\/rt>つ","type":"u","eng":"to wait", "kana":"まつ"},
        {"kanji":"立<rt>た<\/rt>つ","type":"u","eng":"to stand", "kana":"たつ"},
        {"kanji":"払<rt>はら<\/rt>う","type":"u","eng":"to pay (e.g. money, bill), to brush off, to dust off", "kana":"はらう"},
        {"kanji":"<ruby>立<rt>た</rt></ruby>ち<ruby>上<rt>あ</rt></ruby>がる","type":"u","eng":"to stand up", "kana":"たちあがる"},
        {"kanji":"<ruby>立<rt>た</rt></ruby>ち<ruby>止<rt>ど</rt></ruby>まる","type":"u","eng":"to come to a stop", "kana":"たちどまる"},
        {"kanji":"<ruby>立<rt>た</rt></ruby>ち<ruby>去<rt>さ</rt></ruby>る","type":"u","eng":"to leave, to depart", "kana":"たちさる"},
        {"kanji":"<ruby>立<rt>た</rt></ruby>ち<ruby>直<rt>なお</rt></ruby>る","type":"u","eng":"to regain one's footing", "kana":"たちなおる"},
        {"kanji":"<ruby>立<rt>た</rt></ruby>ち<ruby>向<rt>む</rt></ruby>かう","type":"u","eng":"to stand up against, to oppose", "kana":"たちむかう"},

        
    ],
    "verbException": [
        {"kanji":"為<rt>す<\/rt>る","type":"exv","eng":"to do", "kana":"する"},
        {"kanji":"来<rt>く<\/rt>る","type":"exv","eng":"to come", "kana":"くる"},
        {"kanji":"行<rt>い<\/rt>く","type":"exv","eng":"to go", "kana":"いく"},
        {"kanji":"有<rt>あ<\/rt>る","type":"exv","eng":"to be, to have", "kana":"ある"}
    ],
    "adjい": [
        {"kanji":"赤<rt>あか<\/rt>い","type":"i","eng":"red", "kana":"あかい"},
        {"kanji":"早<rt>はや<\/rt>い","type":"i","eng":"early", "kana":"はやい"},
        {"kanji":"速<rt>はや<\/rt>い","type":"i","eng":"fast, quick", "kana":"はやい"},
        {"kanji":"新<rt>あたら<\/rt>しい","type":"i","eng":"new", "kana":"あたらしい"},
        {"kanji":"暑<rt>あつ<\/rt>い","type":"i","eng":"hot (weather)", "kana":"あつい"},
        {"kanji":"熱<rt>あつ<\/rt>い","type":"i","eng":"hot (to the touch)", "kana":"あつい"},
        {"kanji":"厚<rt>あつ<\/rt>い","type":"i","eng":"thick", "kana":"あつい"},
        {"kanji":"冷<rt>つめ<\/rt>たい","type":"i","eng":"cold (to the touch), coldhearted, unfeeling", "kana":"つめたい"},
        {"kanji":"危<rt>あぶ<\/rt>ない","type":"i","eng":"dangerous", "kana":"あぶない"},
        {"kanji":"美<rt>お<\/rt>味<rt>い<\/rt>しい","type":"i","eng":"delicious", "kana":"おいしい"},
        {"kanji":"大<rt>おお<\/rt>きい","type":"i","eng":"big", "kana":"おおきい"},
        {"kanji":"遅<rt>おそ<\/rt>い","type":"i","eng":"late, slow", "kana":"おそい"},
        {"kanji":"面<rt>おも<\/rt>白<rt>しろ<\/rt>い","type":"i","eng":"interesting, funny", "kana":"おもしろい"},
        {"kanji":"可<rt>か<\/rt>愛<rt>わい<\/rt>い","type":"i","eng":"cute, pretty", "kana":"かわいい"},
        {"kanji":"寒<rt>さむ<\/rt>い","type":"i","eng":"cold (weather)", "kana":"さむい"},
        {"kanji":"高<rt>たか<\/rt>い","type":"i","eng":"high, expensive", "kana":"たかい"},
        {"kanji":"楽<rt>たの<\/rt>しい","type":"i","eng":"fun, pleasant", "kana":"たのしい"},
        {"kanji":"小<rt>ちい<\/rt>さい","type":"i","eng":"small", "kana":"ちいさい"},
        {"kanji":"詰<rt>つま<\/rt>らない","type":"i","eng":"uninteresting, boring", "kana":"つまらない"},
        {"kanji":"速<rt>はや<\/rt>い","type":"i","eng":"fast, quick", "kana":"はやい"},
        {"kanji":"近<rt>ちか<\/rt>い","type":"i","eng":"close (distance)", "kana":"ちかい"},
        {"kanji":"長<rt>なが<\/rt>い","type":"i","eng":"long", "kana":"ながい"},
        {"kanji":"忙<rt>いそが<\/rt>しい","type":"i","eng":"busy", "kana":"いそがしい"},
        {"kanji":"強<rt>つよ<\/rt>い","type":"i","eng":"strong", "kana":"つよい"},
        {"kanji":"暖<rt>あたた<\/rt>かい","type":"i","eng":"warm (weather), mild", "kana":"あたたかい"},
        {"kanji":"白<rt>しろ<\/rt>い","type":"i","eng":"white", "kana":"しろい"},
        {"kanji":"少<rt>すく<\/rt>ない","type":"i","eng":"few, a little", "kana":"すくない"},
        {"kanji":"広<rt>ひろ<\/rt>い","type":"i","eng":"wide", "kana":"ひろい"},
        {"kanji":"明<rt>あか<\/rt>るい","type":"i","eng":"bright", "kana":"あかるい"},
        {"kanji":"痛<rt>いた<\/rt>い","type":"i","eng":"painful", "kana":"いたい"},
        {"kanji":"弱<rt>よわ<\/rt>い","type":"i","eng":"weak, frail", "kana":"よわい"},
        {"kanji":"黒<rt>くろ<\/rt>い","type":"i","eng":"black", "kana":"くろい"},
        {"kanji":"甘<rt>あま<\/rt>い","type":"i","eng":"sweet, sugary", "kana":"あまい"},
        {"kanji":"低<rt>ひく<\/rt>い","type":"i","eng":"low", "kana":"ひくい"},
        {"kanji":"丸<rt>まる<\/rt>い","type":"i","eng":"round, circular, spherical", "kana":"まるい"},
        {"kanji":"薄<rt>うす<\/rt>い","type":"i","eng":"thin, pale", "kana":"うすい"},
        {"kanji":"太<rt>ふと<\/rt>い","type":"i","eng":"fat", "kana":"ふとい"},
        {"kanji":"悪<rt>わる<\/rt>い","type":"i","eng":"bad, evil, inferior", "kana":"わるい"},
        {"kanji":"多<rt>おお<\/rt>い","type":"i","eng":"many, a lot", "kana":"おおい"},
        {"kanji":"優<rt>やさ<\/rt>しい","type":"i","eng":"gentle, kind, affectionate", "kana":"やさしい"},
        {"kanji":"若<rt>わか<\/rt>い","type":"i","eng":"young, youthful", "kana":"わかい"},
        {"kanji":"暗<rt>くら<\/rt>い","type":"i","eng":"dark, gloomy, murky", "kana":"くらい"},
        {"kanji":"重<rt>おも<\/rt>い","type":"i","eng":"heavy", "kana":"おもい"},
        {"kanji":"遠<rt>とお<\/rt>い","type":"i","eng":"far, distant", "kana":"とおい"},
        {"kanji":"短<rt>みじか<\/rt>い","type":"i","eng":"short (height, length)", "kana":"みじかい"},
        {"kanji":"青<rt>あお<\/rt>い","type":"i","eng":"blue, green", "kana":"あおい"},
        {"kanji":"狭<rt>せま<\/rt>い","type":"i","eng":"narrow, confined", "kana":"せまい"},
        {"kanji":"軽<rt>かる<\/rt>い","type":"i","eng":"lightweight", "kana":"かるい"},
        {"kanji":"煩<rt>うるさ<\/rt>い","type":"i","eng":"loud, noisy, annoying", "kana":"うるさい"},
        {"kanji":"涼<rt>すず<\/rt>しい","type":"i","eng":"cool, refreshing", "kana":"すずしい"},
        {"kanji":"汚<rt>きたな<\/rt>い","type":"i","eng":"dirty, filthy, foul, vulgar", "kana":"きたない"},
        {"kanji":"不味<rt>まず<\/rt>い","type":"i","eng":"distasteful, unpleasant, unskillful", "kana":"まずい"},
        {"kanji":"黄<rt>き<\/rt>色<rt>いろ<\/rt>い","type":"i","eng":"yellow", "kana":"きいろい"},
        {"kanji":"正<rt>ただ<\/rt>しい","type":"i","eng":"correct, proper, righteous", "kana":"ただしい"},
        {"kanji":"深<rt>ふか<\/rt>い","type":"i","eng":"deep", "kana":"ふかい"},
        {"kanji":"厳<rt>きび<\/rt>しい","type":"i","eng":"strict, severe, difficult, tricky", "kana":"きびしい"},
        {"kanji":"怖<rt>こわ<\/rt>い","type":"i","eng":"scary, frightening", "kana":"こわい"},
        {"kanji":"柔<rt>やわ<\/rt>らかい","type":"i","eng":"soft, tender, gentle, mild", "kana":"やわらかい"},
        {"kanji":"苦<rt>にが<\/rt>い","type":"i","eng":"bitter", "kana":"にがい"},
        {"kanji":"酷<rt>ひど<\/rt>い","type":"i","eng":"awful, cruel, heartless", "kana":"ひどい"},
        {"kanji":"悲<rt>かな<\/rt>しい","type":"i","eng":"sad, sorrowful", "kana":"かなしい"},
        {"kanji":"苦<rt>くる<\/rt>しい","type":"i","eng":"painful, difficult, tough", "kana":"くろしい"},
        {"kanji":"硬<rt>かた<\/rt>い","type":"i","eng":"hard, stiff, (overly) formal", "kana":"かたい"},
        {"kanji":"寂<rt>さび<\/rt>しい","type":"i","eng":"lonely", "kana":"さびしい"},
        {"kanji":"寂<rt>さみ<\/rt>しい","type":"i","eng":"lonely", "kana":"さみしい"},
        {"kanji":"眠<rt>ねむ<\/rt>い","type":"i","eng":"sleepy", "kana":"ねむい"},
        {"kanji":"浅<rt>あさ<\/rt>い","type":"i","eng":"shallow, superficial", "kana":"あさい"},
        {"kanji":"素<rt>す<\/rt>晴<rt>ば<\/rt>らしい","type":"i","eng":"wonderful, splendid, magnificent", "kana":"すばらしい"},
        {"kanji":"宜<rt>よろ<\/rt>しい","type":"i","eng":"good, okay, alright", "kana":"よろしい"},
        {"kanji":"賢<rt>かしこ<\/rt>い","type":"i","eng":"smart, clever, wise", "kana":"かしこい"},
        {"kanji":"欲<rt>ほ<\/rt>しい","type":"i","eng":"wanted, desired", "kana":"ほしい"},
        {"kanji":"難<rt>むずか<\/rt>しい","type":"i","eng":"difficult", "kana":"むずかしい"},
        {"kanji":"恥<rt>はずか<\/rt>しい","type":"i","eng":"embarrassing, shameful, cringe", "kana":"はずかしい"},
        {"kanji":"可笑<rt>おか<\/rt>しい","type":"i","eng":"funny, laughable, ridiculous, strange, odd", "kana":"おかしい"},
        {"kanji":"安<rt>やす<\/rt>い","type":"i","eng":"cheap", "kana":"やすい"},
        {"kanji":"美<rt>うつく<\/rt>しい","type":"i","eng":"pretty, beautiful", "kana":"うつくしい"},
        {"kanji":"面倒臭<rt>めんどうくさ<\/rt>い","type":"i","eng":"bothersome, bother to do", "kana":"めんどうくさい"},
    ],
    "adjな": [
        {"kanji":"好<rt>す<\/rt>き","type":"na","eng":"liked", "kana":"すき"},
        {"kanji":"有<rt>ゆう<\/rt>名<rt>めい<\/rt>","type":"na","eng":"famous", "kana":"ゆうめい"},
        {"kanji":"綺麗<rt>きれい<\/rt>","type":"na","eng":"beautiful, tidy", "kana":"きれい"},
        {"kanji":"嫌<rt>きら<\/rt>い","type":"na","eng":"disliked", "kana":"きらい"},
        {"kanji":"静<rt>しず<\/rt>か","type":"na","eng":"quiet", "kana":"しずか"},
        {"kanji":"元<rt>げん<\/rt>気<rt>き<\/rt>","type":"na","eng":"healthy", "kana":"げんき"},
        {"kanji":"色<rt>いろ<\/rt>々<rt>いろ<\/rt>","type":"na","eng":"various", "kana":"いろいろ"},
        {"kanji":"心<rt>しん<\/rt>配<rt>ぱい<\/rt>","type":"na","eng":"worry, care", "kana":"しんぱい"},
        {"kanji":"嫌<rt>いや<\/rt>","type":"na","eng":"unpleasant, detestable", "kana":"いや"},
        {"kanji":"十<rt>じゅう<\/rt>分<rt>ぶん<\/rt>","type":"na","eng":"sufficient", "kana":"じゅうぶん"},
        {"kanji":"立<rt>りっ<\/rt>派<rt>ぱ<\/rt>","type":"na","eng":"excellent, splendid", "kana":"りっぱ"},
        {"kanji":"同<rt>おな<\/rt>じ","type":"na","eng":"same, alike", "kana":"おなじ"},
        {"kanji":"大<rt>だい<\/rt>丈<rt>じょう<\/rt>夫<rt>ぶ<\/rt>","type":"na","eng":"okay, safe", "kana":"だいじょうぶ"},
        {"kanji":"真<rt>ま<\/rt>っ<ruby>直<rt>す<\/rt><\/ruby>ぐ","type":"na","eng":"straight, direct", "kana":"まっすぐ"},
        {"kanji":"下<rt>へ<\/rt>手<rt>た<\/rt>","type":"na","eng":"unskilled, awkward", "kana":"へた"},
        {"kanji":"上<rt>じょう<\/rt>手<rt>ず<\/rt>","type":"na","eng":"adept, skilled (at)", "kana":"じょうず"},
        {"kanji":"苦<rt>にが<\/rt>手<rt>て<\/rt>","type":"na","eng":"weak (in), not very good (at)", "kana":"にがて"},
        {"kanji":"簡<rt>かん<\/rt>単<rt>たん<\/rt>","type":"na","eng":"simple, easy", "kana":"かんたん"},
        {"kanji":"安<rt>あん<\/rt>全<rt>ぜん<\/rt>","type":"na","eng":"safe, secure", "kana":"あんぜん"},
        {"kanji":"危<rt>き<\/rt>険<rt>けん<\/rt>","type":"na","eng":"dangerous, hazardous", "kana":"きけん"},
        {"kanji":"普<rt>ふ<\/rt>通<rt>つう<\/rt>","type":"na","eng":"normal, ordinary", "kana":"ふつう"},
        {"kanji":"特<rt>とく<\/rt>別<rt>べつ<\/rt>","type":"na","eng":"special", "kana":"とくべつ"},
        {"kanji":"正<rt>しょう<\/rt>直<rt>じき<\/rt>","type":"na","eng":"honest, frank", "kana":"しょうじき"},
        {"kanji":"秘<rt>ひ<\/rt>密<rt>みつ<\/rt>","type":"na","eng":"secret", "kana":"ひみつ"},
        {"kanji":"自<rt>し<\/rt>然<rt>ぜん<\/rt>","type":"na","eng":"natural", "kana":"しぜん"},
        {"kanji":"独<rt>どく<\/rt>立<rt>りつ<\/rt>","type":"na","eng":"independent", "kana":"どくりつ"},
        {"kanji":"永<rt>えい<\/rt>遠<rt>えん<\/rt>","type":"na","eng":"eternal, permanent", "kana":"えいえん"},
        {"kanji":"安<rt>あん<\/rt>定<rt>てい<\/rt>","type":"na","eng":"stable", "kana":"あんてい"},
        {"kanji":"馬<rt>ば<\/rt>鹿<rt>か<\/rt>","type":"na","eng":"stupid, foolish, ridiculous", "kana":"ばか"},
        {"kanji":"退<rt>たい<\/rt>屈<rt>くつ<\/rt>","type":"na","eng":"boring, monotonous", "kana":"たいくつ"},
        {"kanji":"大<rt>たい<\/rt>変<rt>へん<\/rt>","type":"na","eng":"immense, enormous, dreadful, grave", "kana":"たいへん"},
        {"kanji":"大<rt>たい<\/rt>切<rt>せつ<\/rt>","type":"na","eng":"important, significant, precious", "kana":"たいへん"},
        {"kanji":"便<rt>べん<\/rt>利<rt>り<\/rt>","type":"na","eng":"convenient, handy", "kana":"べんり"},
        {"kanji":"楽<rt>らく<\/rt>","type":"na","eng":"comfortable, easy", "kana":"らく"},
        {"kanji":"残<rt>ざん<\/rt>念<rt>ねん<\/rt>","type":"na","eng":"unfortunate, disappointing", "kana":"ざんねん"},
        {"kanji":"必<rt>ひつ<\/rt>要<rt>よう<\/rt>","type":"na","eng":"necessary", "kana":"ひつよう"}
    ],
    "adjException": [
        {"kanji":"良<rt>い<\/rt>い","type":"exa","eng":"good", "kana":"いい"},
        {"kanji":"格好良<rt>かっこい<\/rt>い","type":"exa","eng":"cool, handsome", "kana":"かっこいい"},
    ]
}

export let ConjForms = {
  "verbFormal": null, 
  "verbCasual": null,
  "verbPresent": null,
  "verbPast": null,
  "verbAffirmative": null,
  "verbNegative":null
}

export let specialConjForms = {
    "verbて": null, //negative
    "verbPotential": null, //negative, present, formal
    "verbPassive": null, //negative, present, formal
    "verbCausative": null, //negative, present, formal
    "verbCausativePassive": null, //negative, present, formal
    "verbImperative": null, //negative
    "verbVolitional": null //formal
}

export let adjConjForms = {
  "adjFormal": null, 
  "adjCasual": null,
  "adjPresent": null,
  "adjPast": null,
  "adjAffirmative": null,
  "adjNegative":null
}

export let adjSpConjForms = {
    "adjて": null,
    "adverb": null,
    "nominalized": null
}

export let wordPool = [
    "verbIchidan", 
    "verbす", 
    "verbく", 
    "verbむ", 
    "verbう", 
    "verbException",
    "adjい",
    "adjな",
    "adjException"
];

export let verbPool = [
    "verbIchidan", 
    "verbす", 
    "verbく", 
    "verbむ", 
    "verbう", 
    "verbException"
];

export let adjPool = [
    "adjい",
    "adjな",
    "adjException"
];

export let adjConjPool = [
    "adjPresent",
    "adjPast",
    "adjAffirmative",
    "adjNegative",
    "adjCasual",
    "adjFormal",
];

export let adjSpConjPool = [
    "adjて",
    "adverb",
    "nominalized"
];
    
export let spConjPool = [
    "verbて",
    "verbPotential",
    "verbPassive",
    "verbCausative",
    "verbCausativePassive",
    "verbImperative",
    "verbVolitional"
];
    
export let ConjPool = [
    "verbFormal",
    "verbCasual",
    "verbPresent",
    "verbPast",
    "verbAffirmative",
    "verbNegative"
];
    
export let verbTenses = [
    "verbPresent",
    "verbPast",
    "verbて"
];

export let adjTenses = [
    "adjPresent",
    "adjPast",
    "adjて",
    "adverb",
    "nominalized"
];
    
export let verbAffOrNeg = [
    "verbAffirmative",
    "verbNegative"
];

export let adjAffOrNeg = [
    "adjAffirmative",
    "adjNegative"
];

export let adjFormality = [
    "adjCasual",
    "adjFormal",
];
    
export let verbFormality = [
    "verbFormal",
    "verbCasual"
];