export const hsk1 = [
    {"word": "我", "answer": "wo3", "eng": "I, me"},
    {"word": "我们", "answer": "wo3men", "eng": "we, us"},
    {"word": "你", "answer": "ni3", "eng": "you (singular)"},
    {"word": "你们", "answer": "ni3men", "eng": "you (plural), you all"},
    {"word": "他", "answer": "ta1", "eng": "he, him"},
    {"word": "她", "answer": "ta1", "eng": "she, her"},
    {"word": "它", "answer": "ta1", "eng": "it"},
    {"word": "他们", "answer": "ta1men", "eng": "they, them (masculine)"},
    {"word": "她们", "answer": "ta1men", "eng": "they, them (feminine)"},
    {"word": "这", "answer": "zhe4", "eng": "this; here"},
    {"word": "那", "answer": "na4", "eng": "that; there"},
    {"word": "什么", "answer": "shen2me", "eng": "what"},
    {"word": "多少", "answer": "duo1shao3", "eng": "how much, how many"},
    {"word": "几", "answer": "ji3", "eng": "a few, how many"},
    {"word": "怎么", "answer": "zen3me", "eng": "how"},
    {"word": "怎么样", "answer": "zen3meyang4", "eng": "how"},
    {"word": "一", "answer": "yi1", "eng": "one"},
    {"word": "二", "answer": "er4", "eng": "two"},
    {"word": "三", "answer": "san1", "eng": "three"},
    {"word": "四", "answer": "si4", "eng": "four"},
    {"word": "五", "answer": "wu3", "eng": "five"},
    {"word": "六", "answer": "liu4", "eng": "six"},
    {"word": "七", "answer": "qi1", "eng": "seven"},
    {"word": "八", "answer": "ba1", "eng": "eight"},
    {"word": "九", "answer": "jiu3", "eng": "nine"},
    {"word": "十", "answer": "shi2", "eng": "ten"},
    {"word": "零", "answer": "ling2", "eng": "zero"},
    {"word": "个", "answer": "ge4,ge", "eng": "counter word for people, general"},
    {"word": "岁", "answer": "sui4", "eng": "age, years old"},
    {"word": "些", "answer": "xie1", "eng": "some"},
    {"word": "块", "answer": "kuai4", "eng": "pieces"},
    {"word": "本", "answer": "ben3", "eng": "volume"},
    {"word": "不", "answer": "bu4", "eng": "not"},
    {"word": "没", "answer": "mei2", "eng": "not have"},
    {"word": "太", "answer": "tai4", "eng": "too (excessive)"},
    {"word": "都", "answer": "dou1", "eng": "all"},
    {"word": "很", "answer": "hen3", "eng": "very"},
    {"word": "和", "answer": "he2", "eng": "and"},
    {"word": "在", "answer": "zai4", "eng": "at"},
    {"word": "的", "answer": "de", "eng": "possessive marker"},
    {"word": "了", "answer": "le,liao3", "eng": "completion marker"},
    {"word": "吗", "answer": "ma", "eng": "word marker"},
    {"word": "呢", "answer": "ne", "eng": "word marker v2"},
    {"word": "喂", "answer": "wei2,wei4", "eng": "hey"},
    {"word": "家", "answer": "jia1", "eng": "home"},
    {"word": "学校", "answer": "xue2xiao4", "eng": "school"},
    {"word": "饭店", "answer": "fan4dian4", "eng": "restaurant"},
    {"word": "商店", "answer": "shang1dian4", "eng": "store"},
    {"word": "医院", "answer": "yi1yuan4", "eng": "hospital"},
    {"word": "火车站", "answer": "huo3che1zhan4", "eng": "train station"},
    {"word": "中国", "answer": "zhong1guo2", "eng": "China"},
    {"word": "北京", "answer": "bei3jing1", "eng": "Beijing"},
    {"word": "上", "answer": "shang4", "eng": "up, on, over"},
    {"word": "下", "answer": "xia4", "eng": "down, under"},
    {"word": "前面", "answer": "qian2mian4", "eng": "front side"},
    {"word": "后面", "answer": "hou4mian4", "eng": "back side, behind"},
    {"word": "里面", "answer": "li3mian4", "eng": "inside"},
    {"word": "今天", "answer": "jin1tian1", "eng": "today"},
    {"word": "明天", "answer": "ming2tian1", "eng": "tomorrow"},
    {"word": "昨天", "answer": "zuo2tian1", "eng": "yesterday"},
    {"word": "上午", "answer": "shang4wu3", "eng": "morning"},
    {"word": "中午", "answer": "zhong1wu3", "eng": "noon"},
    {"word": "下午", "answer": "xia4wu3", "eng": "afternoon"},
    {"word": "年", "answer": "nian2", "eng": "year"},
    {"word": "月", "answer": "yue4", "eng": "moon, month"},
    {"word": "日", "answer": "ri4", "eng": "day, sun"},
    {"word": "星期", "answer": "xing1qi1", "eng": "week"},
    {"word": "分钟", "answer": "fen1zhong1", "eng": "minute"},
    {"word": "点", "answer": "dian3", "eng": "dot"},
    {"word": "现在", "answer": "xian4zai4", "eng": "now"},
    {"word": "时候", "answer": "shi2hou4", "eng": "time"},
    {"word": "爸爸", "answer": "ba4ba", "eng": "dad, father"},
    {"word": "妈妈", "answer": "ma1ma", "eng": "mom, mother"},
    {"word": "儿子", "answer": "er2zi", "eng": "son"},
    {"word": "女儿", "answer": "nv3er2", "eng": "daughter"},
    {"word": "老师", "answer": "lao3shi1", "eng": "teacher"},
    {"word": "学生", "answer": "xue2sheng1", "eng": "student"},
    {"word": "同学", "answer": "tong2xue2", "eng": "schoolmate"},
    {"word": "朋友", "answer": "peng2you3", "eng": "friend"},
    {"word": "医生", "answer": "yi1sheng1", "eng": "doctor"},
    {"word": "先生", "answer": "xian1sheng1", "eng": "sir"},
    {"word": "小姐", "answer": "xiao3jie3", "eng": "ma'am"},
    {"word": "衣服", "answer": "yi1fu2", "eng": "clothes"},
    {"word": "水", "answer": "shui3", "eng": "water"},
    {"word": "菜", "answer": "cai4", "eng": "cuisine"},
    {"word": "米饭", "answer": "mi3fan4", "eng": "cooked rice, meal"},
    {"word": "水果", "answer": "shui3guo3", "eng": "fruit"},
    {"word": "苹果", "answer": "ping2guo3", "eng": "apple"},
    {"word": "茶", "answer": "cha2", "eng": "tea"},
    {"word": "杯子", "answer": "bei1zi", "eng": "cup"},
    {"word": "钱", "answer": "qian2", "eng": "money"},
    {"word": "飞机", "answer": "fei1ji1", "eng": "airplane"},
    {"word": "出租车", "answer": "chu1zu1che1", "eng": "taxi"},
    {"word": "电视", "answer": "dian4shi4", "eng": "television"},
    {"word": "电脑", "answer": "dian4nao3", "eng": "computer"},
    {"word": "电影", "answer": "dian4ying3", "eng": "movie"},
    {"word": "天气", "answer": "tian1qi4", "eng": "weather"},
    {"word": "猫", "answer": "mao1", "eng": "cat"},
    {"word": "狗", "answer": "gou3", "eng": "dog"},
    {"word": "东西", "answer": "dong1xi", "eng": "thing, things, stuff"},
    {"word": "人", "answer": "ren2", "eng": "person"},
    {"word": "名字", "answer": "ming2zi4", "eng": "name"},
    {"word": "书", "answer": "shu1", "eng": "book"},
    {"word": "汉语", "answer": "han4yu3", "eng": "Chinese language"},
    {"word": "字", "answer": "zi4", "eng": "character, symbol"},
    {"word": "桌子", "answer": "zhuo1zi", "eng": "table, desk"},
    {"word": "椅子", "answer": "yi3zi", "eng": "chair"},
    {"word": "谢谢", "answer": "xie4xie", "eng": "thank you, thanks"},
    {"word": "不客气", "answer": "bu2ke4qi4", "eng": "you're welcome"},
    {"word": "再见", "answer": "zai4jian4", "eng": "goodbye"},
    {"word": "请", "answer": "qing3", "eng": "please"},
    {"word": "对不起", "answer": "dui4bu4qi3", "eng": "I'm sorry"},
    {"word": "没关系", "answer": "mei2guan1xi4", "eng": "it's ok"},
    {"word": "是", "answer": "shi4", "eng": "to be, am, is, are, was, were"},
    {"word": "有", "answer": "you3", "eng": "to have"},
    {"word": "看", "answer": "kan4", "eng": "to look, to see, to read"},
    {"word": "听", "answer": "ting1", "eng": "to listen, to hear"},
    {"word": "说", "answer": "shuo1", "eng": "to speak, to talk"},
    {"word": "读", "answer": "du2", "eng": "to read"},
    {"word": "写", "answer": "xie3", "eng": "to write"},
    {"word": "看见", "answer": "kan4jian4", "eng": "to see"},
    {"word": "叫", "answer": "jiao4", "eng": "to be called, to call to"},
    {"word": "来", "answer": "lai2", "eng": "to come"},
    {"word": "回", "answer": "hui2", "eng": "to return, to come back"},
    {"word": "去", "answer": "qu4", "eng": "to go"},
    {"word": "吃", "answer": "chi1", "eng": "to eat"},
    {"word": "喝", "answer": "he1", "eng": "to drink"},
    {"word": "睡觉", "answer": "shui4jiao4", "eng": "to sleep"},
    {"word": "打电话", "answer": "da3dian4hua4", "eng": "to call on the phone"},
    {"word": "做", "answer": "zuo4", "eng": "to do"},
    {"word": "买", "answer": "mai3", "eng": "to buy"},
    {"word": "开", "answer": "kai1", "eng": "to open, to turn on, to drive, to begin, to start"},
    {"word": "坐", "answer": "zuo4", "eng": "to sit, to ride as passenger"},
    {"word": "住", "answer": "zhu4", "eng": "to live"},
    {"word": "学习", "answer": "xue2xi2", "eng": "to study, to learn"},
    {"word": "工作", "answer": "gong1zuo4", "eng": "to work"},
    {"word": "下雨", "answer": "xia4yu3", "eng": "to rain"},
    {"word": "爱", "answer": "ai4", "eng": "love, to love"},
    {"word": "喜欢", "answer": "xi3huan1", "eng": "to like"},
    {"word": "想", "answer": "xiang3", "eng": "to want"},
    {"word": "认识", "answer": "ren4shi2", "eng": "to know someone, to meet"},
    {"word": "会", "answer": "hui4", "eng": "to be able to"},
    {"word": "能", "answer": "neng2", "eng": "to be able to"},
    {"word": "好", "answer": "hao3", "eng": "good"},
    {"word": "大", "answer": "da4", "eng": "big"},
    {"word": "小", "answer": "xiao3", "eng": "small"},
    {"word": "多", "answer": "duo1", "eng": "a lot, many"},
    {"word": "少", "answer": "shao3", "eng": "a few, little"},
    {"word": "冷", "answer": "leng3", "eng": "cold"},
    {"word": "热", "answer": "re4", "eng": "hot"},
    {"word": "高兴", "answer": "gao1xing4", "eng": "happy, glad"},
    {"word": "漂亮", "answer": "piao4liang4,piao4liang", "eng": "beautiful, pretty"},
    {"word": "饭馆", "answer": "fan4guan3", "eng": "restaurant"},
    {"word": "下雪", "answer": "xia4xue3", "eng": "to snow"},
    {"word": "雨", "answer": "yu3", "eng": "rain"},
    {"word": "雪", "answer": "xue3", "eng": "snow"},
    {"word": "国", "answer": "guo2", "eng": "country, kingdom"},
    {"word": "美国", "answer": "mei3guo2", "eng": "America, USA"},
    {"word": "德国", "answer": "de2guo2", "eng": "Germany"},
    {"word": "法国", "answer": "fa4guo2,fa3guo2", "eng": "France"},
    {"word": "俄国", "answer": "e2guo2", "eng": "Russia"},
    {"word": "日本", "answer": "ri4ben3", "eng": "Japan"},
    {"word": "中文", "answer": "zhong1wen2", "eng": "Chinese language"},
    {"word": "英文", "answer": "ying1wen2", "eng": "English language"},
    {"word": "北", "answer": "bei3", "eng": "north"},
    {"word": "东", "answer": "dong1", "eng": "east"},
    {"word": "西", "answer": "xi1", "eng": "west"},
    {"word": "南", "answer": "nan2", "eng": "south"},
    {"word": "西南", "answer": "xi1nan2", "eng": "southwest"},
    {"word": "西北", "answer": "xi1bei3", "eng": "northwest"},
    {"word": "东南", "answer": "dong1nan2", "eng": "southeast"},
    {"word": "东北", "answer": "dong1bei3", "eng": "northeast"},
    {"word": "市", "answer": "shi4", "eng": "city"},
    {"word": "东京", "answer": "dong1jing1", "eng": "Tokyo"},
    {"word": "红色", "answer": "hong2se4", "eng": "red"},
    {"word": "绿色", "answer": "lv4se4", "eng": "green"},
    {"word": "颜色", "answer": "yan2se4", "eng": "color"},
    {"word": "黄色", "answer": "huang2se4", "eng": "yellow"},
    {"word": "白色", "answer": "bai2se4", "eng": "white"},
    {"word": "黑色", "answer": "hei1se4", "eng": "black"},
    {"word": "橙", "answer": "cheng2", "eng": "orange"},
    {"word": "蓝色", "answer": "lan2se4", "eng": "blue"},
    {"word": "男人", "answer": "nan2ren2", "eng": "man"},
    {"word": "男", "answer": "nan2", "eng": "male"},
    {"word": "女人", "answer": "nv3ren2", "eng": "woman"},
    {"word": "女", "answer": "nv3", "eng": "female"},
    {"word": "中", "answer": "zhong1", "eng": "middle"},
    {"word": "出", "answer": "chu1", "eng": "to go out"},
    {"word": "关", "answer": "guan1", "eng": "to close, to turn off"},
    {"word": "高", "answer": "gao1", "eng": "tall, high"},
    {"word": "谁", "answer": "shui2,shei2", "eng": "who, whom"},
    {"word": "哪", "answer": "na3", "eng": "what, which, where"},
    {"word": "子", "answer": "zi,zi3", "eng": "child"},
    {"word": "星期一", "answer": "xing1qi1yi1", "eng": "Monday"},
    {"word": "星期二", "answer": "xing1qi1er4", "eng": "Tuesday"},
    {"word": "星期三", "answer": "xing1qi1san1", "eng": "Wednesday"},
    {"word": "星期四", "answer": "xing1qi1si4", "eng": "Thursday"},
    {"word": "星期五", "answer": "xing1qi1wu3", "eng": "Friday"},
    {"word": "星期六", "answer": "xing1qi1liu4", "eng": "Saturday"},
    {"word": "星期天", "answer": "xing1qi1tian1", "eng": "Sunday"},
    {"word": "左", "answer": "zuo3", "eng": "left"},
    {"word": "右", "answer": "you4", "eng": "right"},
    {"word": "左边", "answer": "zuo3bian1", "eng": "left side"},
    {"word": "右边", "answer": "you4bian1", "eng": "right side"},
    {"word": "早", "answer": "zao3", "eng": "early"},
    {"word": "早上", "answer": "zao3shang4", "eng": "morning"},
    {"word": "晚上", "answer": "wan3shang4", "eng": "evening"},
    {"word": "晚安", "answer": "wan3an1", "eng": "good night"},
    {"word": "安", "answer": "an1", "eng": "rest, calm"},
    {"word": "鱼", "answer": "yu2", "eng": "fish"},
    {"word": "夜", "answer": "ye4", "eng": "night"},
    {"word": "蔬菜", "answer": "shu1cai4", "eng": "vegetables"},
    {"word": "汉字", "answer": "han4zi4", "eng": "Chinese character, hanzi"},
    {"word": "非常", "answer": "fei1chang2", "eng": "very"},
    {"word": "咖啡", "answer": "ka1fei1", "eng": "coffee"},
    {"word": "太阳", "answer": "tai4yang2", "eng": "the sun"},
    {"word": "打", "answer": "da3", "eng": "to hit, to strike"},
    {"word": "电话", "answer": "dian4hua4", "eng": "telephone"},
    {"word": "卖", "answer": "mai4", "eng": "to sell"},
    {"word": "国家", "answer": "guo2jia1", "eng": "country"},
    {"word": "上班", "answer": "shang4ban1", "eng": "to go to work"},
    {"word": "下班", "answer": "xia4ban1", "eng": "to leave from work"},
    {"word": "起床", "answer": "qi3chuang2", "eng": "to wake up"},
    {"word": "床", "answer": "chuang2", "eng": "bed"},
    {"word": "汽车", "answer": "qi4che1", "eng": "car"},
    {"word": "火车", "answer": "huo3che1", "eng": "train"},
    {"word": "月亮", "answer": "yue4liang4", "eng": "the moon"},
    {"word": "洗手间", "answer": "xi3shou3jian1", "eng": ""},
    {"word": "洗", "answer": "xi3", "eng": "to wash"},
    {"word": "手", "answer": "shou3", "eng": "hand, hands"},
    {"word": "手机", "answer": "shou3ji1", "eng": "cell phone"},
    {"word": "机", "answer": "ji1", "eng": "device, desk, machine, moment"},
    {"word": "站", "answer": "zhan4", "eng": "to stand"},
    {"word": "白", "answer": "bai2", "eng": "white"},
    {"word": "黑", "answer": "hei1", "eng": "black"},
    {"word": "蓝", "answer": "lan2", "eng": "blue"},
    {"word": "绿", "answer": "lv4", "eng": "green"},
    {"word": "黄", "answer": "huang2", "eng": "yellow"},
    {"word": "红", "answer": "hong2", "eng": "red"},
    {"word": "百", "answer": "bai3", "eng": "hundred"},
    {"word": "千", "answer": "qian1", "eng": "thousand"},
    {"word": "哥哥", "answer": "ge1ge", "eng": "older brother"},
    {"word": "弟弟", "answer": "di4di", "eng": "younger brother"},
    {"word": "妹妹", "answer": "mei4mei", "eng": "younger sister"},
    {"word": "姐姐", "answer": "jie3jie", "eng": "older sister"},
    {"word": "飞", "answer": "fei1", "eng": "to fly"},
    {"word": "时", "answer": "shi2", "eng": "time, season; era, age, period"},
    {"word": "对", "answer": "dui4", "eng": "correct, right; facing, opposed"},
    {"word": "生", "answer": "sheng1", "eng": "life, living, lifetime; birth"},
    {"word": "后", "answer": "hou4", "eng": "behind, rear, after"},
    {"word": "里", "answer": "li3", "eng": "unit of distance; village; lane"},
    {"word": "么", "answer": "me", "eng": "interrogative particle; repetition of a tune small; tender"},
    {"word": "学", "answer": "xue2", "eng": "learning, knowledge; school"},
    {"word": "同", "answer": "tong2", "eng": "same, similar; together with"},
    {"word": "现", "answer": "xian4", "eng": "appear, manifest, become visible"},
    {"word": "面", "answer": "mian4", "eng": "face; surface; plane; side, dimension"},
    {"word": "起", "answer": "qi3", "eng": "rise, stand up; go up; begin"},
    {"word": "天", "answer": "tian1", "eng": "sky, heaven; god, celestial"},
    {"word": "分", "answer": "fen1", "eng": "divide; small unit of time etc."},
    {"word": "错", "answer": "cuo4", "eng": "wrong"},
    {"word": "样", "answer": "yang4", "eng": "shape, form, pattern, style"},
    {"word": "羊", "answer": "yang2", "eng": "sheep"},
    {"word": "前", "answer": "qian2", "eng": "in front, forward; preceding"},
    {"word": "工", "answer": "gong1", "eng": "labor, work; worker, laborer"},
    {"word": "明", "answer": "ming2", "eng": "bright, light, brilliant; clear"},
    {"word": "见", "answer": "jian4", "eng": "see, observe, behold; perceive"},
    {"word": "什", "answer": "shen2", "eng": "file of ten soldiers; mixed, miscellaneous"},
    {"word": "果", "answer": "guo3", "eng": "fruit; result"},
    {"word": "话", "answer": "hua4", "eng": "speech, talk, language; dialect"},
    {"word": "老", "answer": "lao3", "eng": "old, aged; experienced"},
    {"word": "先", "answer": "xian1", "eng": "first, former, previous"},
    {"word": "儿", "answer": "er2", "eng": "son, child"},
    {"word": "电", "answer": "dian4", "eng": "electricity; electric; lightning"},
    {"word": "再", "answer": "zai4", "eng": "again, twice, re-"},
    {"word": "系", "answer": "xi4", "eng": "system; line, link, connection"},
    {"word": "认", "answer": "ren4", "eng": "recognize, know, understand"},
    {"word": "气", "answer": "qi4", "eng": "steam, vapor"},
    {"word": "名", "answer": "ming2", "eng": "name, rank, title, position"},
    {"word": "期", "answer": "qi1", "eng": "period of time; date; time limit"},
    {"word": "觉", "answer": "jue2,jiao4", "eng": "to wake up from sleep; conscious"},
    {"word": "师", "answer": "shi1", "eng": "teacher, master, specialist"},
    {"word": "今", "answer": "jin1", "eng": "now, today, modern era"},
    {"word": "院", "answer": "yuan4", "eng": "courtyard, yard, court; school"},
    {"word": "识", "answer": "shi2", "eng": "recognize, understand, know"},
    {"word": "候", "answer": "hou4", "eng": "wait; expect; visit; greet"},
    {"word": "车", "answer": "che1", "eng": "cart, vehicle; carry in cart"},
    {"word": "服", "answer": "fu2", "eng": "clothes; wear, dress"},
    {"word": "怎", "answer": "zen3", "eng": "what? why? how?"},
    {"word": "影", "answer": "ying3", "eng": "shadow; image, reflection; photograph"},
    {"word": "商", "answer": "shang1", "eng": "commerce, business, trade"},
    {"word": "视", "answer": "shi4", "eng": "look at, inspect, observe, see"},
    {"word": "医", "answer": "yi1", "eng": "cure, heal; doctor, medical"},
    {"word": "号", "answer": "hao4", "eng": "mark, sign; symbol; number"},
    {"word": "语", "answer": "yu3", "eng": "language, words; saying, expression"},
    {"word": "兴", "answer": "xing4", "eng": "thrive, prosper, flourish"},
    {"word": "星", "answer": "xing1", "eng": "a star, planet; any point of light"},
    {"word": "星星", "answer": "xing1xing1,xing1xing", "eng": "star"},
    {"word": "京", "answer": "jing1", "eng": "capital city"},
    {"word": "米", "answer": "mi3", "eng": "hulled or husked uncooked rice"},
    {"word": "客", "answer": "ke4", "eng": "guest, traveller; customer"},
    {"word": "友", "answer": "you3", "eng": "friend, companion; fraternity"},
    {"word": "校", "answer": "xiao4", "eng": "school; military field officer"},
    {"word": "脑", "answer": "nao3", "eng": "brain"},
    {"word": "喜", "answer": "xi3", "eng": "like, love, enjoy; joyful thing"},
    {"word": "欢", "answer": "huan1", "eng": "happy, pleased, glad; joy; enjoy"},
    {"word": "汉", "answer": "han4", "eng": "Chinese people, Chinese language"},
    {"word": "衣", "answer": "yi1", "eng": "clothes, clothing; cover, skin"},
    {"word": "亮", "answer": "liang4", "eng": "bright, brilliant, radiant, light"},
    {"word": "两", "answer": "liang3", "eng": "two (when counting things)"},
    {"word": "朋", "answer": "peng2", "eng": "friend, pal, acquaintance"},
    {"word": "谢", "answer": "xie4", "eng": "to thank"},
    {"word": "钟", "answer": "zhong1", "eng": "clock; bell"},
    {"word": "饭", "answer": "fan4", "eng": "cooked rice; food, meal"},
    {"word": "睡", "answer": "shui4", "eng": "sleep, doze"},
    {"word": "午", "answer": "wu3", "eng": "noon"},
    {"word": "店", "answer": "dian4", "eng": "shop, store; inn, hotel"},
    {"word": "租", "answer": "zu1", "eng": "rent, lease; rental; tax"},
    {"word": "漂", "answer": "piao4", "eng": "float, drift; tossed about"},
    {"word": "票", "answer": "piao4", "eng": "ticket"},
    {"word": "苹", "answer": "ping2", "eng": "artemisia; duckweed; apple"},
    {"word": "大家", "answer": "da4jia1", "eng": "everyone, everybody"},
    {"word": "班", "answer": "ban1", "eng": "class, group, grade; squad; job"},
    {"word": "汽", "answer": "qi4", "eng": "steam, vapor, gas"}
];