export const hsk2 = [
    {"word": "您","answer": "nin2","eng": "you (polite)"},
    {"word": "为什么","answer": "wei4shen2me","eng": "why"},
    {"word": "为","answer": "wei4","eng": "because, reason why"},
    {"word": "第","answer": "di4","eng": "sequence, number; grade, degree"},
    {"word": "第一","answer": "di4yi1","eng": "first"},
    {"word": "第二","answer": "di4er4","eng": "second"},
    {"word": "第三","answer": "di4san1","eng": "third"},
    {"word": "第四","answer": "di4si4","eng": "fourth"},
    {"word": "第五","answer": "di4wu3","eng": "fifth"},
    {"word": "第六","answer": "di4liu4","eng": "sixth"},
    {"word": "第七","answer": "di4qi1","eng": "seventh"},
    {"word": "第八","answer": "di4ba1","eng": "eighth"},
    {"word": "第九","answer": "di4jiu3","eng": "ninth"},
    {"word": "第十","answer": "di4shi2","eng": "tenth"},
    {"word": "到","answer": "dao4","eng": "go to, arrive, been to"},
    {"word": "以","answer": "yi3","eng": "by means of; thereby, therefore; consider as; in order to"},
    {"word": "要","answer": "yao4","eng": "necessary, essential; necessity; to want"},
    {"word": "就","answer": "jiu4","eng": "just, simply; to come, go to; to approach, near"},
    {"word": "可","answer": "ke3","eng": "may, can, -able; possibly"},
    {"word": "也","answer": "ye3","eng": "also; classical final particle of strong affirmation or identity"},
    {"word": "得","answer": "de2","eng": "obtain, get, gain, acquire"},
    {"word": "着","answer": "zhe","eng": "make move, take action"},
    {"word": "过","answer": "guo4","eng": "pass, pass through, go across"},
    {"word": "道","answer": "dao4","eng": "path, road, street; method, way"},
    {"word": "知道","answer": "zhi1dao4","eng": "to know, to understand"},
    {"word": "知","answer": "zhi1","eng": "know"},
    {"word": "所","answer": "suo3","eng": "place, location; numerary adjunct"},
    {"word": "然","answer": "ran2","eng": "yes, certainly; pledge, promise"},
    {"word": "事","answer": "shi4","eng": "affair, matter, business; to serve; accident, incident"},
    {"word": "经","answer": "jing1","eng": "classic works; pass through"},
    {"word": "动","answer": "dong4","eng": "move, happen; movement, action"},
    {"word": "还","answer": "hai2","eng": "still, yet, also, besides"},
    {"word": "进","answer": "jin4","eng": "advance, make progress, enter"},
    {"word": "但","answer": "dan4","eng": "only; but, however, yet, still"},
    {"word": "鸡蛋","answer": "ji1dan4","eng": "chicken egg, eggs"},
    {"word": "鸡","answer": "ji1","eng": "chicken"},
    {"word": "蛋","answer": "dan4","eng": "egg, animal egg"},
    {"word": "因","answer": "yin1","eng": "cause, reason; by; because (of)"},
    {"word": "从","answer": "cong2","eng": "from, by, since, whence, through"},
    {"word": "意","answer": "yi4","eng": "thought, idea, opinion; think"},
    {"word": "意思","answer": "yi4si,yi4si1","eng": "meaning"},
    {"word": "思","answer": "si1","eng": "think"},
    {"word": "长","answer": "zhang3","eng": "long; length; excel in; leader"},
    {"word": "公","answer": "gong1","eng": "fair, equitable; public; duke"},
    {"word": "已","answer": "yi3","eng": "already; finished; stop"},
    {"word": "情","answer": "qing2","eng": "feeling, sentiment, emotion"},
    {"word": "正","answer": "zheng4","eng": "right, proper, correct"},
    {"word": "外","answer": "wai4","eng": "out, outside, external; foreign"},
    {"word": "间","answer": "jian1","eng": "midpoint, space; place, locality"},
    {"word": "问","answer": "wen4","eng": "ask about, inquire after"},
    {"word": "最","answer": "zui4","eng": "most, extremely, exceedingly"},
    {"word": "体","answer": "ti3","eng": "body; group, class, body, unit; inferior"},
    {"word": "等","answer": "deng3","eng": "to wait"},
    {"word": "新","answer": "xin1","eng": "new, recent, fresh, modern"},
    {"word": "身","answer": "shen1","eng": "body; trunk, hull"},
    {"word": "身体","answer": "shen1ti3","eng": "body"},
    {"word": "表","answer": "biao3","eng": "show, express, manifest, display"},
    {"word": "手表","answer": "shou3biao3","eng": "watch, wristwatch"},
    {"word": "手","answer": "shou3","eng": "hand"},
    {"word": "给","answer": "gei3","eng": "give; by, for"},
    {"word": "次","answer": "ci4","eng": "order, sequence; next"},
    {"word": "门","answer": "men2","eng": "gate, door, entrance, opening"},
    {"word": "常","answer": "chang2","eng": "common, normal, frequent, regular"},
    {"word": "教","answer": "jiao4","eng": "teach, class"},
    {"word": "比","answer": "bi3","eng": "to compare, liken; comparison; than"},
    {"word": "员","answer": "yuan2","eng": "member; personnel, staff member"},
    {"word": "真","answer": "zhen1","eng": "real, actual, true, genuine"},
    {"word": "走","answer": "zou3","eng": "walk, go on foot; run; leave"},
    {"word": "条","answer": "tiao2","eng": "clause, condition; string, stripe"},
    {"word": "题","answer": "ti2","eng": "forehead; title, headline; theme"},
    {"word": "问题","answer": "wen4ti2","eng": "question"},
    {"word": "别","answer": "bie2","eng": "separate, other; do not"},
    {"word": "报","answer": "bao4","eng": "report, tell, announce"},
    {"word": "务","answer": "wu4","eng": "affairs, business; must, should"},
    {"word": "商务","answer": "shang1wu4","eng": "affairs, business"},
    {"word": "场","answer": "chang3","eng": "open space, field, market"},
    {"word": "件","answer": "jian4","eng": "numerary adjunct for article; matter"},
    {"word": "便","answer": "bian4","eng": "convenience, ease; expedient"},
    {"word": "司","answer": "si1","eng": "take charge of, control, manage; officer"},
    {"word": "眼","answer": "yan3","eng": "eye; eyelet, hole, opening"},
    {"word": "非","answer": "fei1","eng": "not, negative, non-; oppose"},
    {"word": "完","answer": "wan2","eng": "complete, finish, settle; whole"},
    {"word": "色","answer": "se4","eng": "color, tint, hue, shade; form, body; beauty, desire for beauty"},
    {"word": "路","answer": "lu4","eng": "road, path, street; journey"},
    {"word": "告","answer": "gao4","eng": "tell, announce, inform; accuse"},
    {"word": "边","answer": "bian1","eng": "edge, margin, side, border"},
    {"word": "望","answer": "wang4","eng": "to look at, look forward; to hope, expect"},
    {"word": "共","answer": "gong4","eng": "together with, all, total; to share"},
    {"word": "让","answer": "rang4","eng": "allow, permit, yield, concede"},
    {"word": "运","answer": "yun4","eng": "run; simplified form of 運 luck, fortune; ship, transport"},
    {"word": "笑","answer": "xiao4","eng": "smile, laugh, giggle; snicker"},
    {"word": "步","answer": "bu4","eng": "step, pace; walk, stroll"},
    {"word": "每","answer": "mei3","eng": "every, each"},
    {"word": "快","answer": "kuai4","eng": "rapid, quick, speedy, fast; soon"},
    {"word": "往","answer": "wang3","eng": "go, depart; past, formerly"},
    {"word": "近","answer": "jin4","eng": "near, close; approach; intimate"},
    {"word": "夫","answer": "fu1","eng": "man, male adult, husband; those"},
    {"word": "准","answer": "zhun3","eng": "approve, allow, permit; in accord"},
    {"word": "始","answer": "shi3","eng": "begin, start; then, only then"},
    {"word": "远","answer": "yuan3","eng": "distant, remote, far; profound"},
    {"word": "备","answer": "bei4","eng": "prepare, ready, perfect"},
    {"word": "离","answer": "li2","eng": "rare beast; strange; elegant"},
    {"word": "病","answer": "bing4","eng": "illness, sickness, disease"},
    {"word": "息","answer": "xi1","eng": "rest, put stop to, end, cease"},
    {"word": "找","answer": "zhao3","eng": "search, seek, look for; find"},
    {"word": "吧","answer": "ba","eng": "emphatic final particle"},
    {"word": "考","answer": "kao3","eng": "examine, test; investigate"},
    {"word": "虽","answer": "sui1","eng": "although, even if"},
    {"word": "希","answer": "xi1","eng": "rare; hope, expect, strive for"},
    {"word": "房","answer": "fang2","eng": "house, building; room"},
    {"word": "足","answer": "zu2","eng": "foot; attain, satisfy, enough"},
    {"word": "孩","answer": "hai2","eng": "baby, child; children"},
    {"word": "孩子","answer": "hai2zi,hai2zi3","eng": "baby, child; children"},
    {"word": "男孩","answer": "nan2hai2","eng": "little boy"},
    {"word": "女孩","answer": "nv3hai2","eng": "little girl"},
    {"word": "诉","answer": "su4","eng": "accuse; sue; inform; narrate"},
    {"word": "助","answer": "zhu4","eng": "help, aid, assist"},
    {"word": "乐","answer": "le4","eng": "happy, glad; enjoyable; music"},
    {"word": "球","answer": "qiu2","eng": "ball, sphere, globe; round"},
    {"word": "试","answer": "shi4","eng": "test, try, experiment"},
    {"word": "送","answer": "song4","eng": "see off, send off; dispatch, give"},
    {"word": "药","answer": "yao4","eng": "leaf of Dahurian angelica plant; medicine"},
    {"word": "游","answer": "you2","eng": "to swim; float, drift; wander, roam"},
    {"word": "室","answer": "shi4","eng": "room, home, house, chamber"},
    {"word": "帮","answer": "bang1","eng": "help, assist; defend; shoe upper"},
    {"word": "帮助","answer": "bang1zhu4","eng": "help"},
    {"word": "穿","answer": "chuan1","eng": "penetrate, pierce, drill; wear"},
    {"word": "慢","answer": "man4","eng": "slow(ly), leisurely, sluggish"},
    {"word": "忙","answer": "mang2","eng": "busy, pressed for time; hustling"},
    {"word": "介","answer": "jie4","eng": "forerunner, herald, harbinger; to lie between; sea shell; to wear armor"},
    {"word": "跑","answer": "pao3","eng": "run, flee, leave in hurry"},
    {"word": "跑步","answer": "pao3bu4","eng": "to run"},
    {"word": "贵","answer": "gui4","eng": "expensive, costly, valuable"},
    {"word": "睛","answer": "jing1","eng": "eyeball; pupil of eye"},
    {"word": "眼睛","answer": "yan3jing1","eng": "eye, eyeball, eyes"},
    {"word": "旅","answer": "lv3","eng": "trip, journey; travel; traveler"},
    {"word": "笔","answer": "bi3","eng": "writing brush; write; stroke"},
    {"word": "卖","answer": "mai4","eng": "sell; betray; show off"},
    {"word": "旁","answer": "pang2","eng": "side; by side, close by, near"},
    {"word": "阴","answer": "yin1","eng": "gloom, shadow, yin"},
    {"word": "阴天","answer": "yin1tian1","eng": "cloudy, overcast"},
    {"word": "跳","answer": "tiao4","eng": "jump, leap, vault, bounce; dance"},
    {"word": "跳舞","answer": "tiao4wu3","eng": "to dance"},
    {"word": "舞","answer": "wu3","eng": "dance, posture, prance; brandish"},
    {"word": "肉","answer": "rou4","eng": "flesh; meat"},
    {"word": "馆","answer": "guan3","eng": "public building"},
    {"word": "牛","answer": "niu2","eng": "cow, ox, bull"},
    {"word": "牛奶","answer": "niu2nai3","eng": "milk, cow's milk"},
    {"word": "奶","answer": "nai3","eng": "milk"},
    {"word": "姓","answer": "xing4","eng": "surname"},
    {"word": "纸","answer": "zhi3","eng": "paper"},
    {"word": "歌","answer": "ge1","eng": "song, lyrics; sing, chant; praise"},
    {"word": "玩","answer": "wan2","eng": "play with, joke, enjoy"},
    {"word": "唱","answer": "chang4","eng": "sing, chant, call; ditty, song"},
    {"word": "唱歌","answer": "chang4ge1","eng": "to sing"},
    {"word": "妻","answer": "qi1","eng": "wife"},
    {"word": "妻子","answer": "qi1zi","eng": "a wife"},
    {"word": "休","answer": "xiu1","eng": "rest, stop; retire; do not!"},
    {"word": "汽","answer": "qi4","eng": "steam, vapor, gas"},
    {"word": "课","answer": "ke4","eng": "lesson; course; classwork"},
    {"word": "懂","answer": "dong3","eng": "understand, comprehend"},
    {"word": "绍","answer": "shao4","eng": "continue, carry on; join"},
    {"word": "丈","answer": "zhang4","eng": "unit of length equal 3.3 meters; gentleman, man, husband"},
    {"word": "宜","answer": "yi2","eng": "suitable, right, fitting, proper"},
    {"word": "累","answer": "lei4","eng": "tired; implicate, involve; bother"},
    {"word": "宾","answer": "bin1","eng": "guest, visitor; surname; submit"},
    {"word": "颜","answer": "yan2","eng": "face, facial appearance"},
    {"word": "瓜","answer": "gua1","eng": "melon, gourd, cucumber"},
    {"word": "西瓜","answer": "xi1gua1","eng": "watermelon"},
    {"word": "晴","answer": "qing2","eng": "clear weather, fine weather"},
    {"word": "啡","answer": "fei1","eng": "morphine; coffee"},
    {"word": "篮","answer": "lan2","eng": "basket"},
    {"word": "咖","answer": "ka1","eng": "coffee; a phonetic"},
    {"word": "踢","answer": "ti1","eng": "kick"},
    {"word": "泳","answer": "yong3","eng": "dive; swim"},
    {"word": "游泳","answer": "you2yong3","eng": "to swim"},
    {"word": "铅","answer": "qian1","eng": "lead"},
    {"word": "公斤","answer": "gong1jin1","eng": "kilogram"},
    {"word": "斤","answer": "jin1","eng": "jin, catty"},
    {"word": "公共","answer": "gong1gong4","eng": "public (adj)"},
    {"word": "元","answer": "yuan2","eng": "yuan, yen"},
    {"word": "张","answer": "zhang1","eng": "sheet"},
    {"word": "非常","answer": "fei1chang2","eng": "very"},
    {"word": "正在","answer": "zheng4zai4","eng": "be being"},
    {"word": "已经","answer": "yi3jing1","eng": "already"},
    {"word": "一起","answer": "yi4qi3","eng": "together"},
    {"word": "再","answer": "zai4","eng": "again"},
    {"word": "因为","answer": "yin1wei4","eng": "because"},
    {"word": "所以","answer": "suo3yi3","eng": "so"},
    {"word": "但是","answer": "dan4shi4","eng": "but"},
    {"word": "此","answer": "ci3","eng": "this"},
    {"word": "向","answer": "xiang4","eng": "towards"},
    {"word": "机场","answer": "ji1chang3","eng": "airport"},
    {"word": "教室","answer": "jiao4shi4","eng": "classroom"},
    {"word": "房间","answer": "fang2jian1","eng": "room"},
    {"word": "旁边","answer": "pang2bian1","eng": "side"},
    {"word": "里面","answer": "li3mian4","eng": "inside"},
    {"word": "小时","answer": "xiao3shi2","eng": "hour"},
    {"word": "时间","answer": "shi2jian1","eng": "time"},
    {"word": "去年","answer": "qu4nian2","eng": "last year"},
    {"word": "生日","answer": "sheng1ri4","eng": "birthday"},
    {"word": "羊肉","answer": "yang2rou4","eng": "lamb meat, mutton"},
    {"word": "自行车","answer": "zi4xing2che1","eng": "bicycle, bike"},
    {"word": "自","answer": "zi4","eng": "self, auto-"},
    {"word": "船","answer": "chuan2","eng": "boat, ship"},
    {"word": "公共汽车","answer": "gong1gong4qi4che1","eng": "bus"},
    {"word": "报纸","answer": "bao4zhi3","eng": "newspaper"},
    {"word": "事情","answer": "shi4qing2","eng": "matter"},
    {"word": "考试","answer": "kao3shi4","eng": "exam"},
    {"word": "回答","answer": "hui2da2","eng": "to answer"},
    {"word": "告诉","answer": "gao4su4","eng": "to tell"},
    {"word": "准备","answer": "zhun3bei4","eng": "to prepare"},
    {"word": "开始","answer": "kai1shi3","eng": "to start, to begin"},
    {"word": "介绍","answer": "jie4shao4","eng": "to introduce"},
    {"word": "旅游","answer": "lv3you2","eng": "to travel"},
    {"word": "生病","answer": "sheng1bing4","eng": "to fall ill, to get sick"},
    {"word": "休息","answer": "xiu1xi1,xiu1xi","eng": "to rest"},
    {"word": "运动","answer": "yun4dong4","eng": "to exercise"},
    {"word": "踢足球","answer": "ti1zu2qiu2","eng": "to play football"},
    {"word": "打篮球","answer": "da3lan2qiu2","eng": "to play basketball"},
    {"word": "觉得","answer": "jue2de2,jue2de","eng": "to think"},
    {"word": "希望","answer": "xi1wang4","eng": "to hope"},
    {"word": "可以","answer": "ke3yi3","eng": "to be able to"},
    {"word": "可能","answer": "ke3neng2","eng": "may"},
    {"word": "好吃","answer": "hao3chi1","eng": "delicious"},
    {"word": "便宜","answer": "pian2yi2","eng": "cheap"},
    {"word": "快乐","answer": "kuai4le4","eng": "happy"},
    {"word": "牛肉","answer": "niu2rou4","eng": "beef"},
    {"word": "鱼肉","answer": "yu2rou4","eng": "fish meat"},
    {"word": "鸡肉","answer": "ji1rou4","eng": "chicken meat"},
    {"word": "猪肉","answer": "zhu1rou4","eng": "pork"},
    {"word": "猪","answer": "zhu1","eng": "pig"}
];