export const hsk4 = [
    {"word": "安排","answer": "an1pai2","eng": "to arrange; to plan; to set up"},
    {"word": "安全","answer": "an1quan2","eng": "safe; secure; safety; security"},
    {"word": "暗","answer": "an4","eng": "dark; gloomy; hidden; secret; muddled; obscure; in the dark"},
    {"word": "按时","answer": "an4shi2","eng": "on time; before deadline; on schedule"},
    {"word": "按照","answer": "an4zhao4","eng": "according to; in accordance with; in the light of; on the basis of"},
    {"word": "包括","answer": "bao1gua1","eng": "to comprise; to include; to involve; to incorporate; to consist of"},
    {"word": "保护","answer": "bao3hu4","eng": "to protect; to defend; to safeguard; protection; CL:種|种[zhong3]"},
    {"word": "保证","answer": "bao3zheng4","eng": "guarantee; to guarantee; to ensure; to safeguard; to pledge; CL:個|个[ge4]"},
    {"word": "抱","answer": "bao4","eng": "to hold; to carry (in one's arms); to hug or embrace; surround; cherish"},
    {"word": "报道","answer": "bao4dao4","eng": "report; CL:篇[pian1],份[fen4]"},
    {"word": "报名","answer": "bao4ming2","eng": "to sign up; to enter one's name; to apply; to register; to enroll; to enlist"},
    {"word": "抱歉","answer": "bao4qian4","eng": "sorry; We apologize!; to feel apologetic; to regret"},
    {"word": "被","answer": "bei4","eng": "by (indicates passive-voice sentences or clauses); quilt; to cover (literary)"},
    {"word": "本来","answer": "ben3lai2","eng": "original; originally; at first; it goes without saying; of course"},
    {"word": "笨","answer": "ben4","eng": "stupid; foolish; silly; slow-witted; clumsy"},
    {"word": "笔记本","answer": "bi3ji4ben3","eng": "notebook; CL:本[ben3]"},
    {"word": "毕业","answer": "bi4ye4","eng": "graduation; to graduate; to finish school"},
    {"word": "遍","answer": "bian4","eng": "a time; everywhere; turn; all over; one time"},
    {"word": "标准","answer": "biao1zhun3","eng": "(an official) standard; norm; criterion; CL:個|个[ge4]"},
    {"word": "表达","answer": "biao3da2","eng": "to voice (an opinion); to express; to convey"},
    {"word": "表格","answer": "biao3ge2","eng": "form; table; CL:張|张[zhang1],份[fen4]"},
    {"word": "表扬","answer": "biao3yang2","eng": "to praise; to commend"},
    {"word": "饼干","answer": "bing3gan1","eng": "biscuit; cracker; cookie; CL:片[pian4],塊|块[kuai4]"},
    {"word": "并且","answer": "bing4qie3","eng": "and; besides; moreover; furthermore; in addition"},
    {"word": "博士","answer": "bo2shi4","eng": "doctor; court academician (in feudal China); Ph.D."},
    {"word": "不但","answer": "bu2dan4","eng": "not only (... but also...)"},
    {"word": "不得不","answer": "bu4de2bu4","eng": "have no choice or option but to; cannot but; have to; can't help it; can't avoid"},
    {"word": "不管","answer": "bu4guan3","eng": "no matter (what, how); regardless of; no matter"},
    {"word": "不过","answer": "bu2guo4","eng": "only; merely; no more than; but; however; anyway (to get back to a previous topic)"},
    {"word": "不仅","answer": "bu4jin3","eng": "not only (this one); not just (...) but also"},
    {"word": "擦","answer": "ca1","eng": "to wipe; to erase; rubbing (brush stroke in painting); to clean; to polish"},
    {"word": "猜","answer": "cai1","eng": "to guess"},
    {"word": "材料","answer": "cai2liao4","eng": "material; data; makings; stuff; CL:個|个[ge4],種|种[zhong3]"},
    {"word": "参观","answer": "can1guan1","eng": "to look around; to inspect; visit and observe"},
    {"word": "差不多","answer": "cha4bu5duo1","eng": "almost; nearly; more or less"},
    {"word": "尝","answer": "chang2","eng": "to taste; flavor; (past tense marker); already; formerly; ever; once; test"},
    {"word": "长城","answer": "Chang2cheng2","eng": "the Great Wall"},
    {"word": "长江","answer": "Chang2jiang1","eng": "Changjiang river; Yangtze river"},
    {"word": "超过","answer": "chao1guo4","eng": "to surpass; to exceed; to outstrip"},
    {"word": "吵","answer": "chao3","eng": "to quarrel; to make a noise; noisy; to disturb by making a noise"},
    {"word": "成功","answer": "cheng2gong1","eng": "success; to succeed; CL:次[ci4],個|个[ge4]"},
    {"word": "诚实","answer": "cheng2shi2","eng": "honest; honesty; honorable; truthful"},
    {"word": "成熟","answer": "cheng2shu2","eng": "mature; ripe; Taiwan pr. cheng2 shou2"},
    {"word": "成为","answer": "cheng2wei2","eng": "to become; to turn into"},
    {"word": "乘坐","answer": "cheng2zuo4","eng": "to ride (in a vehicle)"},
    {"word": "吃惊","answer": "chi1jing1","eng": "to be startled; to be shocked; to be amazed"},
    {"word": "重新","answer": "chong2xin1","eng": "again; once more; re-"},
    {"word": "抽烟","answer": "chou1yan1","eng": "to smoke (a cigarette, tobacco)"},
    {"word": "出差","answer": "chu1chai1","eng": "to go on an official or business trip"},
    {"word": "出发","answer": "chu1fa1","eng": "to start out; to set off"},
    {"word": "出生","answer": "chu1sheng1","eng": "to be born"},
    {"word": "传真","answer": "chuan2zhen1","eng": "fax; facsimile"},
    {"word": "窗户","answer": "chuang1hu5","eng": "window; CL:個|个[ge4],扇[shan4]"},
    {"word": "词典","answer": "ci2dian3","eng": "dictionary (of Chinese compound words); also written 辭典|辞典[ci2 dian3]; CL:部[bu4],本[ben3]"},
    {"word": "从来","answer": "cong2lai2","eng": "always; at all times; never (if used in negative sentence)"},
    {"word": "粗心","answer": "cu1xin1","eng": "careless; thoughtless"},
    {"word": "答案","answer": "da2an4","eng": "answer; solution; CL:個|个[ge4]"},
    {"word": "打扮","answer": "da3ban5","eng": "to decorate; to dress; to make up; to adorn; manner of dressing; style of dress"},
    {"word": "打扰","answer": "da3rao3","eng": "to disturb; to bother; to trouble"},
    {"word": "打印","answer": "da3yin4","eng": "to print; to seal; to stamp"},
    {"word": "打折","answer": "da3zhe2","eng": "to give a discount"},
    {"word": "打针","answer": "da3zhen1","eng": "to give or have an injection"},
    {"word": "大概","answer": "da4gai4","eng": "roughly; probably; rough; approximate; about"},
    {"word": "大使馆","answer": "da4shi3guan3","eng": "embassy; CL:座[zuo4],個|个[ge4]"},
    {"word": "大约","answer": "da4yue1","eng": "approximately; about"},
    {"word": "戴","answer": "dai4","eng": "to put on or wear (glasses, hat, gloves etc); to respect; to bear; to support"},
    {"word": "代表","answer": "dai4biao3","eng": "representative; delegate; CL:位[wei4],個|个[ge4],名[ming2]; to represent; to stand for; on behalf of; in the name of"},
    {"word": "大夫","answer": "dai4fu5","eng": "doctor; minister of state (in pre-Han states); CL:個|个[ge4],位[wei4]"},
    {"word": "代替","answer": "dai4ti4","eng": "instead; to replace; to substitute (X for Y, or a number in an algebraic expression)"},
    {"word": "当","answer": "dang1","eng": "to be; to act as; manage; withstand; when; during; ought; should; match equally; equal; same; obstruct; just at (a time or place); on the spot; right; just at"},
    {"word": "当地","answer": "dang1di4","eng": "local"},
    {"word": "当时","answer": "dang1shi2","eng": "then; at that time; while"},
    {"word": "刀","answer": "dao1","eng": "knife; CL:把[ba3]"},
    {"word": "导游","answer": "dao3you2","eng": "tour guide; to conduct a tour; a guidebook"},
    {"word": "到处","answer": "dao4chu4","eng": "in all places; everywhere"},
    {"word": "到底","answer": "dao4di3","eng": "finally; in the end; when all is said and done; after all; to the end; to the last"},
    {"word": "道歉","answer": "dao4qian4","eng": "to apologize; to make an apology"},
    {"word": "得意","answer": "de2yi4","eng": "proud of oneself; pleased with oneself; complacent"},
    {"word": "得","answer": "dei3","eng": "to have to; must; ought to; to need to"},
    {"word": "等","answer": "deng3","eng": "et cetera; and so on; et al. (and other authors); after; as soon as; once"},
    {"word": "底","answer": "di3","eng": "background; bottom; base; the end of a period of time; towards the end of (last month)"},
    {"word": "地球","answer": "di4qiu2","eng": "the Earth; planet; CL:個|个[ge4]"},
    {"word": "地址","answer": "di4zhi3","eng": "address; CL:個|个[ge4]"},
    {"word": "掉","answer": "diao4","eng": "to fall; to drop; to lag behind; to lose; to go missing; to reduce; fall (in prices); to lose (value, weight etc); to wag; to swing; to turn; to change; to exchange; to swap; to show off; to shed (hair)"},
    {"word": "调查","answer": "diao4cha2","eng": "investigation; inquiry; to investigate; to survey; survey; (opinion) poll; CL:項|项[xiang4],個|个[ge4]"},
    {"word": "丢","answer": "diu1","eng": "to lose; to put aside; to throw"},
    {"word": "动作","answer": "dong4zuo4","eng": "movement; motion; action; CL:個|个[ge4]"},
    {"word": "堵车","answer": "du3che1","eng": "traffic jam; choking"},
    {"word": "肚子","answer": "du4zi5","eng": "belly; abdomen; stomach; CL:個|个[ge4]"},
    {"word": "断","answer": "duan4","eng": "to break; to snap; to cut off; to give up or abstain from sth; to judge; (usu. used in the negative) absolutely, definitely,decidedly"},
    {"word": "对话","answer": "dui4hua4","eng": "dialog; CL:個|个[ge4]"},
    {"word": "对面","answer": "dui4mian4","eng": "opposite"},
    {"word": "顿","answer": "dun4","eng": "stop; pause; to arrange; to lay out; to kowtow; to stamp; at once; classifier for meals, beating, tellings off etc: time, bout, spell, meal"},
    {"word": "朵","answer": "duo3","eng": "flower; earlobe; fig. item on both sides; classifier for flowers, clouds etc"},
    {"word": "而","answer": "er2","eng": "and; as well as; and so; but (not); yet (not); (indicates causal relation); (indicates change of state); (indicates contrast)"},
    {"word": "儿童","answer": "er2tong2","eng": "child; CL:個|个[ge4]"},
    {"word": "发","answer": "fa1","eng": "to send out; to show (one's feeling); to issue; to develop; classifier for gunshots (rounds)"},
    {"word": "发生","answer": "fa1sheng1","eng": "to happen; to occur; to take place; to break out"},
    {"word": "发展","answer": "fa1zhan3","eng": "development; growth; to develop; to grow; to expand"},
    {"word": "法律","answer": "fa3lv4","eng": "law; CL:條|条[tiao2], 套[tao4], 個|个[ge4]"},
    {"word": "翻译","answer": "fan1yi4","eng": "to translate; to interpret; translator; interpreter; translation; interpretation; CL:個|个[ge4],位[wei4],名[ming2]"},
    {"word": "烦恼","answer": "fan2nao3","eng": "agonize; agony; annoyance; upset; vexation; worries"},
    {"word": "反对","answer": "fan3dui4","eng": "to fight against; to oppose; to be opposed to; opposition"},
    {"word": "反映","answer": "fan3ying4","eng": "to mirror; to reflect; mirror image; reflection; fig. to report; to make known; to render; used erroneously for 反應|反应, response or reaction"},
    {"word": "范围","answer": "fan4wei2","eng": "range; scope; limit; extent; CL:個|个[ge4]"},
    {"word": "方法","answer": "fang1fa3","eng": "method; way; means; CL:個|个[ge4]"},
    {"word": "方面","answer": "fang1mian4","eng": "respect; aspect; field; side; CL:個|个[ge4]"},
    {"word": "方向","answer": "fang1xiang4","eng": "direction; orientation; path to follow; CL:個|个[ge4]"},
    {"word": "访问","answer": "fang3wen4","eng": "to visit; to call on; to interview; CL:次[ci4]"},
    {"word": "放弃","answer": "fang4qi4","eng": "to renounce; to abandon; to give up"},
    {"word": "放暑假","answer": "fang4shu3jia4","eng": "take summer vacation"},
    {"word": "…分之…","answer": "fen1zhi1","eng": "used for fractions and percentages, e.g. 四分之一 is 1/4 and 百分之一 is 1%"},
    {"word": "份","answer": "fen4","eng": "part; share; portion; copy; classifier for gifts, newspaper, magazine, papers, reports, contracts etc"},
    {"word": "丰富","answer": "feng1fu4","eng": "rich; plentiful; abundant"},
    {"word": "风景","answer": "feng1jing3","eng": "scenery; landscape; CL:個|个[ge4]"},
    {"word": "否则","answer": "fou3ze2","eng": "if not; otherwise; else; or else"},
    {"word": "符合","answer": "fu2he2","eng": "in keeping with; in accordance with; tallying with; in line with; to agree with; to accord with; to conform to; to correspond with; to manage; to handle"},
    {"word": "富","answer": "fu4","eng": "rich; surname Fu"},
    {"word": "父亲","answer": "fu4qin1","eng": "father; also pr. with light tone [fu4 qin5]; CL:個|个[ge4]"},
    {"word": "复印","answer": "fu4yin4","eng": "to photocopy; to duplicate a document"},
    {"word": "复杂","answer": "fu4za2","eng": "complicated; complex"},
    {"word": "负责","answer": "fu4ze2","eng": "to be in charge of; to take responsibility for; to be to blame; conscientious"},
    {"word": "改变","answer": "gai3bian4","eng": "to change; to alter; to transform"},
    {"word": "干杯","answer": "gan1bei1","eng": "to drink a toast; Cheers! (proposing a toast); Here's to you!; Bottoms up!; lit. dry cup"},
    {"word": "干燥","answer": "gan1zao4","eng": "to dry (of weather, paint, cement etc); desiccation; dull; uninteresting; arid"},
    {"word": "感动","answer": "gan3dong4","eng": "to move (sb); to touch (sb emotionally); moving"},
    {"word": "感觉","answer": "gan3jue2","eng": "to feel; to become aware of; feeling; sense; perception; CL:個|个[ge4]"},
    {"word": "感情","answer": "gan3qing2","eng": "feeling; emotion; sensation; likes and dislikes; deep affection for sb or sth; relationship (i.e. love affair); CL:個|个[ge4],種|种[zhong3]"},
    {"word": "感谢","answer": "gan3xie4","eng": "(express) thanks; gratitude; grateful; thankful; thanks"},
    {"word": "高级","answer": "gao1ji2","eng": "high level; high grade; advanced; high-ranking"},
    {"word": "各","answer": "ge4","eng": "each; every"},
    {"word": "个子","answer": "ge4zi5","eng": "height; stature; build; size"},
    {"word": "工具","answer": "gong1ju4","eng": "tool; instrument; utensil; means (to achieve a goal etc)"},
    {"word": "公里","answer": "gong1li3","eng": "kilometer"},
    {"word": "工资","answer": "gong1zi1","eng": "wages; pay; CL:個|个[ge4],份[fen4],月[yue4]"},
    {"word": "共同","answer": "gong4tong2","eng": "common; joint; jointly; together; collaborative"},
    {"word": "够","answer": "gou4","eng": "to reach; to be enough"},
    {"word": "购物","answer": "gou4wu4","eng": "shopping"},
    {"word": "孤单","answer": "gu1dan1","eng": "lone; lonely; loneliness"},
    {"word": "估计","answer": "gu1ji4","eng": "to estimate; to reckon; CL:個|个[ge4]"},
    {"word": "鼓励","answer": "gu3li4","eng": "to encourage"},
    {"word": "鼓掌","answer": "gu3zhang3","eng": "to applaud; to clap"},
    {"word": "顾客","answer": "gu4ke4","eng": "client; customer; CL:位[wei4]"},
    {"word": "故意","answer": "gu4yi4","eng": "deliberately; on purpose"},
    {"word": "挂","answer": "gua4","eng": "to hang or suspend (from a hook etc); (of a telephone call) to hang up; to be worried or concerned; to make a phone call (topolect); to register or record; to hitch; classifier for sets or clusters of objects"},
    {"word": "关键","answer": "guan1jian4","eng": "crucial point; crux; CL:個|个[ge4]; key; crucial; pivotal"},
    {"word": "观众","answer": "guan1zhong4","eng": "spectators; audience; visitors (to an exhibition etc)"},
    {"word": "管理","answer": "guan3li3","eng": "to supervise; to manage; to administer; management; administration; CL:個|个[ge4]"},
    {"word": "光","answer": "guang1","eng": "light; ray; CL:道[dao4]; bright; only; merely; to use up"},
    {"word": "广播","answer": "guang3bo1","eng": "broadcast; widely spread; CL:個|个[ge4]"},
    {"word": "广告","answer": "guang3gao4","eng": "to advertise; a commercial; advertisement; CL:項|项[xiang4]"},
    {"word": "逛","answer": "guang4","eng": "to stroll; to visit"},
    {"word": "规定","answer": "gui1ding4","eng": "provision; to fix; to set; to formulate; to stipulate; to provide; regulation; rule; CL:個|个[ge4]"},
    {"word": "国际","answer": "guo2ji4","eng": "international"},
    {"word": "果然","answer": "guo3ran2","eng": "really; sure enough; as expected"},
    {"word": "过程","answer": "guo4cheng2","eng": "course of events; process; CL:個|个[ge4]"},
    {"word": "海洋","answer": "hai3yang2","eng": "ocean; CL:個|个[ge4]"},
    {"word": "害羞","answer": "hai4xiu1","eng": "blush; shy"},
    {"word": "寒假","answer": "han2jia4","eng": "winter vacation"},
    {"word": "汗","answer": "han4","eng": "perspiration; sweat; CL:滴[di1],頭|头[tou2],身[shen1]; Khan (Persian or Mongol king or emperor); Khan (name); to be speechless (out of helplessness, embarrassment etc) (Internet slang used as an interjection)"},
    {"word": "航班","answer": "hang2ban1","eng": "scheduled flight; flight number; plane; scheduled sailing; sailing number; passenger ship"},
    {"word": "好处","answer": "hao3chu5","eng": "benefit; advantage; gain; profit; also pronounced hao3 chu4; CL:個|个[ge4]"},
    {"word": "好像","answer": "hao3xiang4","eng": "as if; to seem like"},
    {"word": "号码","answer": "hao4ma3","eng": "number; CL:堆[dui1],個|个[ge4]"},
    {"word": "合格","answer": "he2ge2","eng": "qualified; meeting a standard; eligible (voter)"},
    {"word": "合适","answer": "he2shi4","eng": "suitable; fitting; decent; to fit"},
    {"word": "盒","answer": "he2","eng": "case"},
    {"word": "猴","answer": "hou2","eng": "monkey; CL:隻|只[zhi1]"},
    {"word": "厚","answer": "hou4","eng": "thick; deep or profound; kind; generous; rich or strong in flavor; to favor; to stress"},
    {"word": "后悔","answer": "hou4hui3","eng": "to regret; to repent"},
    {"word": "后来","answer": "hou4lai2","eng": "afterwards; later"},
    {"word": "忽然","answer": "hu1ran2","eng": "suddenly; all of a sudden"},
    {"word": "护士","answer": "hu4shi5","eng": "nurse; CL:個|个[ge4]"},
    {"word": "互相","answer": "hu4xiang1","eng": "each other; mutually; mutual"},
    {"word": "怀疑","answer": "huai2yi2","eng": "to doubt; to suspect; doubt; suspicion; skeptical"},
    {"word": "还","answer": "huan2","eng": "to pay back; to return; surname Huan"},
    {"word": "回忆","answer": "hui2yi4","eng": "to recall; recollection; CL:個|个[ge4]"},
    {"word": "活动","answer": "huo2dong4","eng": "to exercise; to move about; to operate; activity; loose; shaky; active; movable; maneuver; to use connections; CL:項|项[xiang4],個|个[ge4]"},
    {"word": "活泼","answer": "huo2po5","eng": "lively; vivacious; brisk; active"},
    {"word": "火","answer": "huo3","eng": "fire; CL:把[ba3]"},
    {"word": "获得","answer": "huo4de2","eng": "to obtain; to receive; to get"},
    {"word": "基础","answer": "ji1chu3","eng": "base; foundation; basis; underlying; CL:個|个[ge4]"},
    {"word": "激动","answer": "ji1dong4","eng": "to excite; to agitate; exciting"},
    {"word": "积极","answer": "ji1ji2","eng": "active; energetic; vigorous; positive (outlook); proactive"},
    {"word": "积累","answer": "ji1lei3","eng": "to accumulate; accumulation; cumulative; cumulatively"},
    {"word": "集合","answer": "ji2he2","eng": "a congregation; to gather; a set"},
    {"word": "极其","answer": "ji2qi2","eng": "extremely"},
    {"word": "及时","answer": "ji2shi2","eng": "in time; promptly; without delay; timely"},
    {"word": "即使","answer": "ji2shi3","eng": "even if; even though; given that"},
    {"word": "寄","answer": "ji4","eng": "to live (in a house); to lodge; to mail; to send; to entrust; to depend"},
    {"word": "计划","answer": "ji4hua4","eng": "plan; project; program; to plan; to map out; CL:個|个[ge4],項|项[xiang4]"},
    {"word": "既然","answer": "ji4ran2","eng": "since; as; this being the case"},
    {"word": "技术","answer": "ji4shu4","eng": "technology; technique; skill; CL:門|门[men2],種|种[zhong3],項|项[xiang4]"},
    {"word": "继续","answer": "ji4xu4","eng": "to continue; to proceed with; to go on with"},
    {"word": "记者","answer": "ji4zhe3","eng": "reporter; journalist; CL:個|个[ge4]"},
    {"word": "加班","answer": "jia1ban1","eng": "to work overtime"},
    {"word": "家具","answer": "jia1ju4","eng": "furniture; CL:件[jian4],套[tao4]"},
    {"word": "加油站","answer": "jia1you2zhan4","eng": "gas station"},
    {"word": "假","answer": "jia3","eng": "fake; false; artificial; to borrow; if; suppose"},
    {"word": "价格","answer": "jia4ge2","eng": "price; CL:個|个[ge4]"},
    {"word": "坚持","answer": "jian1chi2","eng": "to continue upholding; to remain committed to; persistence; to persist; to uphold; to insist on; persevere"},
    {"word": "减肥","answer": "jian3fei2","eng": "to lose weight"},
    {"word": "减少","answer": "jian3shao3","eng": "to lessen; to decrease; to reduce; to lower"},
    {"word": "将来","answer": "jiang1lai2","eng": "in the future; future; the future; CL:個|个[ge4]"},
    {"word": "奖金","answer": "jiang3jin1","eng": "premium; award money; a bonus"},
    {"word": "降低","answer": "jiang4di1","eng": "to reduce; to lower; to bring down"},
    {"word": "交","answer": "jiao1","eng": "to hand over; to deliver; to pay (money); to turn over; to make friends; to intersect (lines)"},
    {"word": "骄傲","answer": "jiao1ao4","eng": "arrogant; full of oneself; conceited; proud of sth; CL:個|个[ge4]"},
    {"word": "交流","answer": "jiao1liu2","eng": "exchange; give-and-take; to exchange; to alternate; communication; alternating current (electricity)"},
    {"word": "交通","answer": "jiao1tong1","eng": "to be connected; traffic; communications; liaison"},
    {"word": "饺子","answer": "jiao3zi5","eng": "dumpling; pot-sticker; CL:個|个[ge4],隻|只[zhi1]"},
    {"word": "教授","answer": "jiao4shou4","eng": "professor; to instruct; to lecture on; CL:個|个[ge4],位[wei4]"},
    {"word": "教育","answer": "jiao4yu4","eng": "to educate; to teach; education"},
    {"word": "接受","answer": "jie1shou4","eng": "to accept; to receive"},
    {"word": "节约","answer": "jie2yue1","eng": "to economize; to conserve (resources); economy; frugal"},
    {"word": "解释","answer": "jie3shi4","eng": "explanation; to explain; to interpret; to resolve; CL:個|个[ge4]"},
    {"word": "尽管","answer": "jin3guan3","eng": "despite; although; even though; in spite of; unhesitatingly; do not hesitate (to ask, complain etc); (go ahead and do it) without hesitating"},
    {"word": "紧张","answer": "jin3zhang1","eng": "nervous; keyed up; intense; tense; strained; in short supply; scarce; CL:陣|阵[zhen4]"},
    {"word": "进行","answer": "jin4xing2","eng": "to advance; to conduct; underway; in progress; to do; to carry out; to carry on; to execute"},
    {"word": "禁止","answer": "jin4zhi3","eng": "to prohibit; to forbid; to ban"},
    {"word": "精彩","answer": "jing1cai3","eng": "brilliant; splendid"},
    {"word": "经济","answer": "jing1ji4","eng": "economy; economic"},
    {"word": "京剧","answer": "Jing1ju4","eng": "Beijing opera; CL:場|场[chang3],出[chu1]"},
    {"word": "经历","answer": "jing1li4","eng": "experience; CL:個|个[ge4],次[ci4]; to experience; to go through"},
    {"word": "精神","answer": "jing1shen2","eng": "spirit; mind; consciousness; thought; mental; psychological; essence; gist; CL:個|个[ge4]"},
    {"word": "经验","answer": "jing1yan4","eng": "to experience; experience"},
    {"word": "警察","answer": "jing3cha2","eng": "police; policeman; policewoman; CL:個|个[ge4]"},
    {"word": "竟然","answer": "jing4ran2","eng": "unexpectedly; to one's surprise; in spite of everything; in that crazy way; actually; to go as far as to"},
    {"word": "竞争","answer": "jing4zheng1","eng": "to compete; competition"},
    {"word": "镜","answer": "jing4","eng": "mirror; CL:面[mian4],個|个[ge4]"},
    {"word": "究竟","answer": "jiu1jing4","eng": "after all (when all is said and done); actually; outcome; result"},
    {"word": "举办","answer": "ju3ban4","eng": "to conduct; to hold"},
    {"word": "拒绝","answer": "ju4jue2","eng": "to refuse; to decline; to reject"},
    {"word": "距离","answer": "ju4li2","eng": "distance; to be apart; CL:個|个[ge4]"},
    {"word": "开玩笑","answer": "kai1wan2xiao4","eng": "to play a joke; to make fun of; to joke"},
    {"word": "看法","answer": "kan4fa3","eng": "way of looking at a thing; view; opinion; CL:個|个[ge4]"},
    {"word": "考虑","answer": "kao3lv4","eng": "to think over; to consider; consideration"},
    {"word": "棵","answer": "ke1","eng": "classifier for trees, cabbages, plants etc"},
    {"word": "科学","answer": "ke1xue2","eng": "science; scientific knowledge; scientific; CL:門|门[men2],個|个[ge4],種|种[zhong3]"},
    {"word": "咳嗽","answer": "ke2sou5","eng": "to cough; CL:陣|阵[zhen4]"},
    {"word": "可怜","answer": "ke3lian2","eng": "pitiful; pathetic"},
    {"word": "可是","answer": "ke3shi4","eng": "but; however"},
    {"word": "可惜","answer": "ke3xi1","eng": "it is a pity; what a pity; (it's) too bad"},
    {"word": "肯定","answer": "ken3ding4","eng": "to be sure; to be certain; sure; certain; definite; to confirm; to affirm; affirmative"},
    {"word": "空气","answer": "kong1qi4","eng": "air; atmosphere"},
    {"word": "恐怕","answer": "kong3pa4","eng": "fear; to dread; I'm afraid that...; perhaps; maybe"},
    {"word": "苦","answer": "ku3","eng": "bitter; hardship; pain; to suffer; painstaking"},
    {"word": "宽","answer": "kuan1","eng": "lenient; wide; broad"},
    {"word": "困","answer": "kun4","eng": "to trap; to surround; hard-pressed; stranded; destitute"},
    {"word": "困难","answer": "kun4nan5","eng": "(financial etc) difficulty; problem; issue; CL:個|个[ge4]"},
    {"word": "扩大","answer": "kuo4da4","eng": "to expand; to enlarge; to broaden one's scope"},
    {"word": "拉","answer": "la1","eng": "to pull; to play (string instruments); to drag; to draw"},
    {"word": "垃圾桶","answer": "la1ji1tong3","eng": "rubbish bin"},
    {"word": "辣","answer": "la4","eng": "hot (spicy); pungent"},
    {"word": "来不及","answer": "lai2bu5ji2","eng": "there's not enough time (to do sth); it's too late (to do sth)"},
    {"word": "来得及","answer": "lai2de5ji2","eng": "there's still time; able to do sth in time"},
    {"word": "懒","answer": "lan3","eng": "lazy"},
    {"word": "浪费","answer": "lang4fei4","eng": "to waste; to squander"},
    {"word": "浪漫","answer": "lang4man4","eng": "romantic"},
    {"word": "老虎","answer": "lao3hu3","eng": "tiger; CL:隻|只[zhi1]"},
    {"word": "冷静","answer": "leng3jing4","eng": "calm; cool-headed"},
    {"word": "理发","answer": "li3fa4","eng": "a barber; hairdressing"},
    {"word": "理解","answer": "li3jie3","eng": "to comprehend; to understand; comprehension; understanding"},
    {"word": "礼貌","answer": "li3mao4","eng": "courtesy; manners"},
    {"word": "理想","answer": "li3xiang3","eng": "a dream; an ideal; perfection; ideal; perfect; desirable; CL:個|个[ge4]"},
    {"word": "厉害","answer": "li4hai5","eng": "difficult to deal with; difficult to endure; ferocious; radical; serious; terrible; violent; tremendous; awesome"},
    {"word": "力气","answer": "li4qi5","eng": "strength; CL:把[ba3]"},
    {"word": "例如","answer": "li4ru2","eng": "for example; for instance; such as"},
    {"word": "俩","answer": "lia3","eng": "two (colloquial equivalent of 兩個|两个); both; some"},
    {"word": "连","answer": "lian2","eng": "to link; to join; to connect; continuously; in succession; including; (used with 也, 都 etc) even; company (military)"},
    {"word": "联系","answer": "lian2xi4","eng": "connection; contact; relation; in touch with; to integrate; to link; to touch"},
    {"word": "凉快","answer": "liang2kuai5","eng": "nice and cold; pleasantly cool"},
    {"word": "亮","answer": "liang4","eng": "bright; clear; resonant; to shine; to show; to reveal"},
    {"word": "聊天","answer": "liao2tian1","eng": "to chat; to gossip"},
    {"word": "另外","answer": "ling4wai4","eng": "additional; in addition; besides; separate; other; moreover; furthermore"},
    {"word": "留","answer": "liu2","eng": "to leave (eg a message); to retain; to stay; to remain; to keep; to preserve"},
    {"word": "流泪","answer": "liu2lei4","eng": "to shed tears"},
    {"word": "流利","answer": "liu2li4","eng": "fluent"},
    {"word": "流行","answer": "liu2xing2","eng": "to spread; to rage (of contagious disease); popular; fashionable; prevalent; (math.) manifold"},
    {"word": "留学","answer": "liu2xue2","eng": "to study abroad"},
    {"word": "乱","answer": "luan4","eng": "in confusion or disorder; in a confused state of mind; disorder; upheaval; riot; illicit sexual relations; to throw into disorder; to mix up; indiscriminate; random; arbitrary"},
    {"word": "律师","answer": "lv4shi1","eng": "lawyer"},
    {"word": "麻烦","answer": "ma2fan5","eng": "inconvenient; troublesome; to trouble or bother sb; to put sb to trouble"},
    {"word": "马虎","answer": "ma3hu5","eng": "careless; sloppy; negligent; skimpy"},
    {"word": "满","answer": "man3","eng": "full; filled; packed; fully; completely; quite; to reach the limit; to satisfy; satisfied; contented; to fill; abbr. for Manchurian"},
    {"word": "毛巾","answer": "mao2jin1","eng": "towel; CL:條|条[tiao2]"},
    {"word": "美丽","answer": "mei3li4","eng": "beautiful"},
    {"word": "梦","answer": "meng4","eng": "dream; CL:場|场[chang2],個|个[ge4]"},
    {"word": "密码","answer": "mi4ma3","eng": "code; secret code; password; pin number"},
    {"word": "免费","answer": "mian3fei4","eng": "free (of charge)"},
    {"word": "民族","answer": "min2zu2","eng": "nationality; ethnic group; CL:個|个[ge4]"},
    {"word": "母亲","answer": "mu3qin1","eng": "mother; also pr. with light tone [mu3 qin5]; CL:個|个[ge4]"},
    {"word": "目的","answer": "mu4di4","eng": "purpose; aim; goal; target; objective; CL:個|个[ge4]"},
    {"word": "耐心","answer": "nai4xin1","eng": "patient (adjective)"},
    {"word": "难道","answer": "nan2dao4","eng": "don't tell me ...; could it be that...?"},
    {"word": "难受","answer": "nan2shou4","eng": "to feel unwell; to suffer pain; to be difficult to bear"},
    {"word": "内","answer": "nei4","eng": "inside; inner; internal; within; interior"},
    {"word": "内容","answer": "nei4rong2","eng": "content; substance; details; CL:個|个[ge4],項|项[xiang4]"},
    {"word": "能力","answer": "neng2li4","eng": "capability; capable; able; ability; CL:個|个[ge4]"},
    {"word": "年龄","answer": "nian2ling2","eng": "(a person's) age; CL:把[ba3],個|个[ge4]"},
    {"word": "农村","answer": "nong2cun1","eng": "rural area; village; CL:個|个[ge4]"},
    {"word": "弄","answer": "nong4","eng": "to do; to manage; to handle; to play with; to fool with; to mess with; to fix; to toy with"},
    {"word": "暖和","answer": "nuan3huo5","eng": "warm; nice and warm"},
    {"word": "偶尔","answer": "ou3er3","eng": "occasionally; once in a while; sometimes"},
    {"word": "排列","answer": "pai2lie4","eng": "array; arrangement; permutation (i.e. ordered choice of n elements out of m)"},
    {"word": "判断","answer": "pan4duan4","eng": "to decide; to determine; CL:個|个[ge4]"},
    {"word": "陪","answer": "pei2","eng": "to accompany; to keep sb company"},
    {"word": "批评","answer": "pi1ping2","eng": "to criticize; criticism; CL:個|个[ge4]"},
    {"word": "皮肤","answer": "pi2fu1","eng": "skin; CL:種|种[zhong3]"},
    {"word": "篇","answer": "pian1","eng": "sheet; piece of writing; bound set of bamboo slips used for record keeping (old); classifier for written items: chapter, article"},
    {"word": "骗","answer": "pian4","eng": "to cheat; to swindle; to deceive; to fool; to hoodwink; to trick"},
    {"word": "乒乓球","answer": "ping1pang1qiu2","eng": "table tennis; ping-pong; ping pong; table tennis ball; CL:個|个[ge4]"},
    {"word": "平时","answer": "ping2shi2","eng": "in normal times; in peacetime"},
    {"word": "瓶子","answer": "ping2zi5","eng": "bottle; CL:個|个[ge4]"},
    {"word": "破","answer": "po4","eng": "broken; damaged; worn out; to break, split or cleave; to get rid of; to destroy; to break with; to defeat; to capture (a city etc); to expose the truth of"},
    {"word": "普遍","answer": "pu3bian4","eng": "universal; general; widespread; common"},
    {"word": "其次","answer": "qi2ci4","eng": "next; secondly"},
    {"word": "其中","answer": "qi2zhong1","eng": "among; in; included among these"},
    {"word": "起飞","answer": "qi3fei1","eng": "to take off (in an airplane)"},
    {"word": "气候","answer": "qi4hou4","eng": "climate; atmosphere; situation; CL:種|种[zhong3]"},
    {"word": "千万","answer": "qian1wan4","eng": "ten million; countless; many; one must by all means"},
    {"word": "签证","answer": "qian1zheng4","eng": "visa; certificate; to certify; CL:個|个[ge4]"},
    {"word": "墙","answer": "qiang2","eng": "wall; CL:面[mian4],堵[du3]"},
    {"word": "敲","answer": "qiao1","eng": "extort; knock; to strike; to knock (at a door); to hit"},
    {"word": "桥","answer": "qiao2","eng": "bridge; CL:座[zuo4]"},
    {"word": "巧克力","answer": "qiao3ke4li4","eng": "chocolate (loanword); CL:塊|块[kuai4]"},
    {"word": "亲戚","answer": "qin1qi5","eng": "a relative (i.e. family relation); CL:門|门[men2],個|个[ge4],位[wei4]"},
    {"word": "轻","answer": "qing1","eng": "light; easy; gentle; soft; reckless; unimportant; frivolous; small in number; unstressed; neutral"},
    {"word": "轻松","answer": "qing1song1","eng": "gentle; relaxed"},
    {"word": "情况","answer": "qing2kuang4","eng": "circumstances; state of affairs; situation; CL:個|个[ge4],種|种[zhong3]"},
    {"word": "请假","answer": "qing3jia4","eng": "ask for time off"},
    {"word": "请客","answer": "qing3ke4","eng": "give a dinner party; entertain guests; invite to dinner"},
    {"word": "穷","answer": "qiong2","eng": "exhausted; poor"},
    {"word": "区别","answer": "qu1bie2","eng": "difference; to distinguish; to discriminate; to make a distinction; CL:個|个[ge4]"},
    {"word": "取","answer": "qu3","eng": "to take; to get; to choose; to fetch"},
    {"word": "全部","answer": "quan2bu4","eng": "whole; entire; complete"},
    {"word": "缺点","answer": "que1dian3","eng": "weak point; fault; shortcoming; CL:個|个[ge4]"},
    {"word": "缺少","answer": "que1shao3","eng": "lack; shortage of; shortfall; to be short (of); to lack"},
    {"word": "却","answer": "que4","eng": "but; yet; however; while; to go back; to decline; to retreat; nevertheless; even though"},
    {"word": "确实","answer": "que4shi2","eng": "indeed; really; reliable; real; true"},
    {"word": "群","answer": "qun2","eng": "group; crowd; flock, herd, pack etc"},
    {"word": "然而","answer": "ran2er2","eng": "however; yet; but"},
    {"word": "热闹","answer": "re4nao5","eng": "bustling with noise and excitement; lively"},
    {"word": "人民币","answer": "ren2min2bi4","eng": "Renminbi (RMB); Chinese Yuan (CNY)"},
    {"word": "任何","answer": "ren4he2","eng": "any; whatever; whichever; whatsoever"},
    {"word": "任务","answer": "ren4wu5","eng": "mission; assignment; task; duty; role; CL:項|项[xiang4],個|个[ge4]"},
    {"word": "扔","answer": "reng1","eng": "to throw; to throw away"},
    {"word": "仍然","answer": "reng2ran2","eng": "still; yet"},
    {"word": "日记","answer": "ri4ji4","eng": "diary; CL:則|则[ze2],本[ben3],篇[pian1]"},
    {"word": "入口","answer": "ru4kou3","eng": "entrance"},
    {"word": "软","answer": "ruan3","eng": "soft; flexible"},
    {"word": "散步","answer": "san4bu4","eng": "to take a walk; to go for a walk"},
    {"word": "森林","answer": "sen1lin2","eng": "forest; CL:片[pian4]"},
    {"word": "沙发","answer": "sha1fa1","eng": "sofa; CL:條|条[tiao2],張|张[zhang1]"},
    {"word": "商量","answer": "shang1liang5","eng": "to consult; to talk over; to discuss"},
    {"word": "伤心","answer": "shang1xin1","eng": "to grieve; broken-hearted"},
    {"word": "稍微","answer": "shao1wei1","eng": "a little bit"},
    {"word": "社会","answer": "she4hui4","eng": "society; CL:個|个[ge4]"},
    {"word": "深","answer": "shen1","eng": "close; deep; late; profound; dark (of color, water etc)"},
    {"word": "申请","answer": "shen1qing3","eng": "to apply for sth; application (form etc); CL:份[fen4]"},
    {"word": "甚至","answer": "shen4zhi4","eng": "even; so much so that"},
    {"word": "生活","answer": "sheng1huo2","eng": "life; activity; to live; livelihood"},
    {"word": "生命","answer": "sheng1ming4","eng": "life; living; biological; CL:個|个[ge4]"},
    {"word": "省","answer": "sheng3","eng": "to save; to economize; to do without; to omit; to leave out; province; CL:個|个[ge4]"},
    {"word": "剩","answer": "sheng4","eng": "to remain; to be left; to have as remainder"},
    {"word": "失败","answer": "shi1bai4","eng": "to be defeated; to lose; to fail (e.g. experiments); failure; defeat; CL:次[ci4]"},
    {"word": "师傅","answer": "shi1fu5","eng": "master; qualified worker; respectful form of address for older men; CL:個|个[ge4],位[wei4],名[ming2]"},
    {"word": "湿润","answer": "shi1run4","eng": "moist"},
    {"word": "失望","answer": "shi1wang4","eng": "disappointed; to lose hope; to despair"},
    {"word": "十分","answer": "shi2fen1","eng": "to divide into ten equal parts; very; hundred percent; completely; extremely; utterly; absolutely"},
    {"word": "实际","answer": "shi2ji4","eng": "actual; reality; practice"},
    {"word": "食品","answer": "shi2pin3","eng": "foodstuff; food; provisions; CL:種|种[zhong3]"},
    {"word": "实在","answer": "shi2zai4","eng": "in reality; honestly; really; verily; concrete"},
    {"word": "使用","answer": "shi3yong4","eng": "to use; to employ; to apply; to make use of"},
    {"word": "试","answer": "shi4","eng": "to test; to try; experiment; examination; test"},
    {"word": "市场","answer": "shi4chang3","eng": "market place; market (also in abstract); abbr. for 超級市場|超级市场 supermarket; CL:個|个[ge4]"},
    {"word": "适合","answer": "shi4he2","eng": "to fit; to suit"},
    {"word": "世纪","answer": "shi4ji4","eng": "century; CL:個|个[ge4]"},
    {"word": "适应","answer": "shi4ying4","eng": "to suit; to fit; to be suitable; to adapt; to get used to sth"},
    {"word": "收","answer": "shou1","eng": "to receive; to accept; to collect; in care of (used on address line after name)"},
    {"word": "收入","answer": "shou1ru4","eng": "to take in; income; revenue; CL:筆|笔[bi3],個|个[ge4]"},
    {"word": "收拾","answer": "shou1shi5","eng": "to put in order; to tidy up; to pack; to repair; to punish (colloquial); to manage"},
    {"word": "首都","answer": "shou3du1","eng": "capital (city); CL:個|个[ge4]"},
    {"word": "首先","answer": "shou3xian1","eng": "first (of all); in the first place"},
    {"word": "受不了","answer": "shou4bu4liao3","eng": "unbearable; unable to endure; can't stand"},
    {"word": "售货员","answer": "shou4huo4yuan2","eng": "salesperson; CL:個|个[ge4]"},
    {"word": "输","answer": "shu1","eng": "to lose; to transport; to donate; to enter (a password)"},
    {"word": "熟悉","answer": "shu2xi1","eng": "to be familiar with; to know well"},
    {"word": "数量","answer": "shu4liang4","eng": "amount; quantity; CL:個|个[ge4]"},
    {"word": "数字","answer": "shu4zi4","eng": "numeral; digit; number; figure; amount; digital (electronics etc); CL:個|个[ge4]"},
    {"word": "帅","answer": "shuai4","eng": "handsome; graceful; smart; commander in chief"},
    {"word": "顺便","answer": "shun4bian4","eng": "conveniently; in passing; without much extra effort"},
    {"word": "顺利","answer": "shun4li4","eng": "smoothly; without a hitch"},
    {"word": "顺序","answer": "shun4xu4","eng": "sequence; order"},
    {"word": "说明","answer": "shuo1ming2","eng": "to explain; to illustrate; explanation; directions; caption; CL:個|个[ge4]"},
    {"word": "硕士","answer": "shuo4shi4","eng": "master's degree; learned person"},
    {"word": "死","answer": "si3","eng": "to die; impassable; uncrossable; inflexible; rigid; extremely"},
    {"word": "速度","answer": "su4du4","eng": "speed; rate; velocity; CL:個|个[ge4]"},
    {"word": "塑料袋","answer": "su4liao4dai4","eng": "plastic bag"},
    {"word": "酸","answer": "suan1","eng": "sour; sore; ache; acid"},
    {"word": "算","answer": "suan4","eng": "regard as; to figure; to calculate; to compute"},
    {"word": "随便","answer": "sui2bian4","eng": "as one wishes; as one pleases; at random; negligent; casual; wanton"},
    {"word": "随着","answer": "sui2zhe5","eng": "along with; in the wake of; following"},
    {"word": "所有","answer": "suo3you3","eng": "all; to have; to possess; to own"},
    {"word": "台","answer": "tai2","eng": "desk; platform; stage; terrace; stand; support; desk; station; broadcasting station; classifier for vehicles or machines; Taiwan (abbr.)"},
    {"word": "抬","answer": "tai2","eng": "to lift; to raise; (of two or more persons) to carry"},
    {"word": "态度","answer": "tai4du5","eng": "manner; bearing; attitude; approach; CL:個|个[ge4]"},
    {"word": "谈","answer": "tan2","eng": "to talk"},
    {"word": "弹钢琴","answer": "tan2gang1qin2","eng": "play the piano"},
    {"word": "汤","answer": "tang1","eng": "soup; broth; hot water"},
    {"word": "躺","answer": "tang3","eng": "to recline; to lie down"},
    {"word": "讨论","answer": "tao3lun4","eng": "to discuss; to talk over; CL:個|个[ge4]"},
    {"word": "讨厌","answer": "tao3yan4","eng": "disgusting; troublesome; nuisance; nasty; to hate doing sth"},
    {"word": "特点","answer": "te4dian3","eng": "characteristic (feature); trait; feature; CL:個|个[ge4]"},
    {"word": "提供","answer": "ti2gong1","eng": "to offer; to supply; to provide; to furnish"},
    {"word": "提前","answer": "ti2qian2","eng": "to shift to an earlier date; to bring forward; to advance"},
    {"word": "提醒","answer": "ti2xing3","eng": "to remind; to call attention to; to warn of"},
    {"word": "填空","answer": "tian2kong4","eng": "to fill a job vacancy; to fill in a blank (e.g. on questionnaire or exam paper)"},
    {"word": "条件","answer": "tiao2jian4","eng": "condition; circumstances; term; factor; requirement; prerequisite; qualification; CL:個|个[ge4]"},
    {"word": "停止","answer": "ting2zhi3","eng": "to stop; to halt; to cease"},
    {"word": "挺","answer": "ting3","eng": "to stick out; to (physically) straighten up; to endure or hold out; straight; stiff; outstanding; extraordinary; rather; quite; very; classifier for machine guns"},
    {"word": "通过","answer": "tong1guo4","eng": "by means of; through; via; to pass through; to get through; to adopt; to pass (a bill); to switch over"},
    {"word": "通知","answer": "tong1zhi1","eng": "to notify; to inform; notice; notification; CL:個|个[ge4]"},
    {"word": "同情","answer": "tong2qing2","eng": "compassion; relent; sympathize; sympathy"},
    {"word": "推","answer": "tui1","eng": "to push; to cut; to refuse; to reject; to decline; to shirk (responsibility); to put off; to delay; to push forward; to nominate; to elect"},
    {"word": "推迟","answer": "tui1chi2","eng": "to postpone; to put off; to defer"},
    {"word": "脱","answer": "tuo1","eng": "to shed; to take off; to escape; to get away from"},
    {"word": "袜","answer": "wa4","eng": "socks; stockings; CL:隻|只[zhi1],對|对[dui4],雙|双[shuang1]"},
    {"word": "完全","answer": "wan2quan2","eng": "complete; whole; totally; entirely"},
    {"word": "往","answer": "wang3","eng": "to go (in a direction); to; towards; (of a train) bound for; past; previous"},
    {"word": "网球","answer": "wang3qiu2","eng": "tennis; CL: 粒[li4]; 個|个[ge4]"},
    {"word": "往往","answer": "wang3wang3","eng": "often; frequently"},
    {"word": "网站","answer": "wang3zhan4","eng": "website; network station; node"},
    {"word": "危险","answer": "wei1xian3","eng": "danger; dangerous"},
    {"word": "味道","answer": "wei4dao4","eng": "flavor; smell; hint of"},
    {"word": "温度","answer": "wen1du4","eng": "temperature; CL:個|个[ge4]"},
    {"word": "文章","answer": "wen2zhang1","eng": "article; essay; literary works; writings; hidden meaning; CL:篇[pian1],段[duan4],頁|页[ye4]"},
    {"word": "握手","answer": "wo4shou3","eng": "to shake hands"},
    {"word": "污染","answer": "wu1ran3","eng": "pollution; contamination; CL:個|个[ge4]"},
    {"word": "无","answer": "wu2","eng": "-less; not to have; no; none; not; to lack; un-"},
    {"word": "无聊","answer": "wu2liao2","eng": "nonsense; bored"},
    {"word": "无论","answer": "wu2lun4","eng": "no matter what or how; regardless of whether..."},
    {"word": "误会","answer": "wu4hui4","eng": "to misunderstand; to mistake; misunderstanding; CL:個|个[ge4]"},
    {"word": "西红柿","answer": "xi1hong2shi4","eng": "tomato; CL:隻|只[zhi1]"},
    {"word": "吸引","answer": "xi1yin3","eng": "to attract (interest, investment etc); CL:個|个[ge4]"},
    {"word": "洗衣机","answer": "xi3yi1ji1","eng": "washer; washing machine; CL:臺|台[tai2]"},
    {"word": "咸","answer": "xian2","eng": "salty"},
    {"word": "现代","answer": "xian4dai4","eng": "modern times; modern age; modern era"},
    {"word": "羡慕","answer": "xian4mu4","eng": "envious; envy; to admire"},
    {"word": "限制","answer": "xian4zhi4","eng": "to restrict; to limit; to confine; restriction; limit; CL:個|个[ge4]"},
    {"word": "香","answer": "xiang1","eng": "fragrant; sweet smelling; aromatic; savory or appetizing; (to eat) with relish; (of sleep) sound; perfume or spice; joss or incense stick; CL:根[gen1]"},
    {"word": "相反","answer": "xiang1fan3","eng": "opposite; contrary"},
    {"word": "详细","answer": "xiang2xi4","eng": "detailed; in detail; minute"},
    {"word": "响","answer": "xiang3","eng": "to make a sound; to sound; to ring; loud; classifier for noises"},
    {"word": "消息","answer": "xiao1xi5","eng": "news; information; CL:條|条[tiao2]"},
    {"word": "小说","answer": "xiao3shuo1","eng": "novel; fiction; CL:本[ben3],部[bu4]"},
    {"word": "效果","answer": "xiao4guo3","eng": "result; effect; quality; CL:個|个[ge4]"},
    {"word": "笑话","answer": "xiao4hua4","eng": "joke; jest; CL:個|个[ge4]"},
    {"word": "辛苦","answer": "xin1ku3","eng": "hard; exhausting; with much toil; thanks for your trouble"},
    {"word": "心情","answer": "xin1qing2","eng": "mood; frame of mind; CL:個|个[ge4]"},
    {"word": "信任","answer": "xin4ren4","eng": "to trust; to have confidence in"},
    {"word": "信心","answer": "xin4xin1","eng": "confidence; faith (in sb or sth); CL:個|个[ge4]"},
    {"word": "信用卡","answer": "xin4yong4ka3","eng": "credit card"},
    {"word": "兴奋","answer": "xing1fen4","eng": "excited; excitement"},
    {"word": "行","answer": "xing2","eng": "to walk; to go; to travel; a visit; temporary; makeshift; current; in circulation; to do; to perform; capable; competent; effective; all right; OK!; will do"},
    {"word": "醒","answer": "xing3","eng": "to wake up; to awaken; to be awake"},
    {"word": "性别","answer": "xing4bie2","eng": "gender; sex; distinguishing between the sexes"},
    {"word": "幸福","answer": "xing4fu2","eng": "blessed; happiness; happy"},
    {"word": "性格","answer": "xing4ge2","eng": "nature; disposition; temperament; character; CL:個|个[ge4]"},
    {"word": "修","answer": "xiu1","eng": "to mend; to repair; to build; to embellish; to study"},
    {"word": "许多","answer": "xu3duo1","eng": "many; a lot of; much"},
    {"word": "血","answer": "xue4","eng": "blood; informal colloquial and Taiwan pr. xie3; also pr. xue3; CL:滴[di1],片[pian4]"},
    {"word": "压力","answer": "ya1li4","eng": "pressure"},
    {"word": "牙膏","answer": "ya2gao1","eng": "toothpaste; CL:管[guan3]"},
    {"word": "亚洲","answer": "Ya4zhou1","eng": "Asia; Asian"},
    {"word": "呀","answer": "ya5","eng": "(particle equivalent to 啊 after a vowel, expressing surprise or doubt)"},
    {"word": "盐","answer": "yan2","eng": "salt; CL:粒[li4]"},
    {"word": "严格","answer": "yan2ge2","eng": "strict; stringent; tight; rigorous"},
    {"word": "研究生","answer": "yan2jiu1sheng1","eng": "graduate student; postgraduate student; research student"},
    {"word": "严重","answer": "yan2zhong4","eng": "grave; serious; severe; critical"},
    {"word": "演出","answer": "yan3chu1","eng": "to act (in a play); to perform; to put on (a performance); performance; concert; show; CL:場|场[chang2],次[ci4]"},
    {"word": "演员","answer": "yan3yuan2","eng": "actor or actress; performer; CL:個|个[ge4],位[wei4],名[ming2]"},
    {"word": "阳光","answer": "yang2guang1","eng": "sunshine; CL:線|线[xian4]"},
    {"word": "养成","answer": "yang3cheng2","eng": "to cultivate; to raise; to form (a habit); to acquire"},
    {"word": "样子","answer": "yang4zi5","eng": "manner; air; looks; aspect"},
    {"word": "邀请","answer": "yao1qing3","eng": "to invite; invitation; CL:個|个[ge4]"},
    {"word": "钥匙","answer": "yao4shi5","eng": "key; CL:把[ba3]"},
    {"word": "也许","answer": "ye3xu3","eng": "perhaps; maybe"},
    {"word": "页","answer": "ye4","eng": "page; leaf"},
    {"word": "叶子","answer": "ye4zi5","eng": "foliage; leaf; CL:片[pian4]"},
    {"word": "一切","answer": "yi1qie4","eng": "everything; every; all"},
    {"word": "以","answer": "yi3","eng": "to use as; according to; because of"},
    {"word": "亿","answer": "yi4","eng": "a hundred million; calculate"},
    {"word": "意见","answer": "yi4jian4","eng": "idea; opinion; suggestion; objection; complaint; CL:點|点[dian3],條|条[tiao2]"},
    {"word": "艺术","answer": "yi4shu4","eng": "art; CL:種|种[zhong3]"},
    {"word": "因此","answer": "yin1ci3","eng": "thus; consequently; as a result"},
    {"word": "饮料","answer": "yin3liao4","eng": "drink; beverage"},
    {"word": "引起","answer": "yin3qi3","eng": "to give rise to; to lead to; to cause; to arouse"},
    {"word": "印象","answer": "yin4xiang4","eng": "impression; reflection; perception; CL:個|个[ge4]"},
    {"word": "赢","answer": "ying2","eng": "to beat; to win; to profit"},
    {"word": "硬","answer": "ying4","eng": "hard; stiff; strong; firm; to manage to do sth with difficulty; good (quality); able (person)"},
    {"word": "勇敢","answer": "yong3gan3","eng": "brave; courageous"},
    {"word": "永远","answer": "yong3yuan3","eng": "forever; eternal"},
    {"word": "优点","answer": "you1dian3","eng": "merit; benefit; strong point; advantage; CL:個|个[ge4]"},
    {"word": "幽默","answer": "you1mo4","eng": "humor; humorous"},
    {"word": "优秀","answer": "you1xiu4","eng": "outstanding; excellent"},
    {"word": "由","answer": "you2","eng": "to follow; from; it is for...to; reason; cause; because of; due to; to; to leave it (to sb); by (introduces passive verb)"},
    {"word": "尤其","answer": "you2qi2","eng": "especially; particularly"},
    {"word": "由于","answer": "you2yu2","eng": "due to; as a result of; thanks to; owing to; since; because"},
    {"word": "友好","answer": "you3hao3","eng": "friendly; amicable"},
    {"word": "有趣","answer": "you3qu4","eng": "interesting; fascinating; amusing"},
    {"word": "友谊","answer": "you3yi4","eng": "companionship; fellowship; friendship"},
    {"word": "愉快","answer": "yu2kuai4","eng": "cheerful; cheerily; delightful; pleasant; pleasantly; pleasing; happy; delighted"},
    {"word": "于是","answer": "yu2shi4","eng": "thereupon; as a result; consequently; thus; hence"},
    {"word": "语法","answer": "yu3fa3","eng": "grammar"},
    {"word": "羽毛球","answer": "yu3mao2qiu2","eng": "shuttlecock; badminton; CL:個|个[ge4]"},
    {"word": "语言","answer": "yu3yan2","eng": "language; CL:門|门[men2],種|种[zhong3]"},
    {"word": "预习","answer": "yu4xi2","eng": "to prepare a lesson"},
    {"word": "元","answer": "yuan2","eng": "first; primary; basic"},
    {"word": "原来","answer": "yuan2lai2","eng": "original; former; originally; formerly; at first; so... actually"},
    {"word": "原谅","answer": "yuan2liang4","eng": "to excuse; to forgive; to pardon"},
    {"word": "原因","answer": "yuan2yin1","eng": "cause; origin; root cause; reason; CL:個|个[ge4]"},
    {"word": "约会","answer": "yue1hui4","eng": "appointment; engagement; date; CL:次[ci4],個|个[ge4]"},
    {"word": "阅读","answer": "yue4du2","eng": "to read; reading"},
    {"word": "允许","answer": "yun3xu3","eng": "to permit; to allow"},
    {"word": "杂志","answer": "za2zhi4","eng": "magazine; CL:本[ben3],份[fen4],期[qi1]"},
    {"word": "咱们","answer": "zan2men5","eng": "we or us (including both the speaker and the person(s) spoken to); I or me; you"},
    {"word": "暂时","answer": "zan4shi2","eng": "temporary; provisional; for the time being"},
    {"word": "责任","answer": "ze2ren4","eng": "responsibility; blame; duty; CL:個|个[ge4]"},
    {"word": "增加","answer": "zeng1jia1","eng": "to raise; to increase"},
    {"word": "增长","answer": "zeng1zhang3","eng": "to grow; to increase"},
    {"word": "窄","answer": "zhai3","eng": "narrow; narrow-minded; badly off"},
    {"word": "招聘","answer": "zhao1pin4","eng": "recruitment; to invite applications for a job"},
    {"word": "真正","answer": "zhen1zheng4","eng": "genuine; real; true; genuinely"},
    {"word": "整理","answer": "zheng3li3","eng": "to arrange; to tidy up; to sort out; to straighten out; to list systematically; to collate (data, files); to pack (luggage)"},
    {"word": "整齐","answer": "zheng3qi2","eng": "orderly; neat; even; tidy"},
    {"word": "正常","answer": "zheng4chang2","eng": "regular; normal; ordinary"},
    {"word": "正好","answer": "zheng4hao3","eng": "just (in time); just right; just enough; to happen to; to chance to; by chance; it just so happens that"},
    {"word": "证明","answer": "zheng4ming2","eng": "proof; certificate; identification; testimonial; CL:個|个[ge4]; to prove; to testify; to confirm the truth of"},
    {"word": "正确","answer": "zheng4que4","eng": "correct; proper"},
    {"word": "正式","answer": "zheng4shi4","eng": "formal; official"},
    {"word": "之","answer": "zhi1","eng": "(possessive particle, literary equivalent of 的); him; her; it"},
    {"word": "只","answer": "zhi1","eng": "classifier for birds and certain animals, one of a pair, some utensils, vessels etc"},
    {"word": "支持","answer": "zhi1chi2","eng": "to be in favor of; to support; to back; support; backing; to stand by; CL:個|个[ge4]"},
    {"word": "知识","answer": "zhi1shi5","eng": "intellectual; knowledge-related; knowledge; CL:門|门[men2]"},
    {"word": "值得","answer": "zhi2de5","eng": "to be worth; to deserve"},
    {"word": "直接","answer": "zhi2jie1","eng": "direct; opposite: indirect 間接|间接; immediate; directly; straightforward"},
    {"word": "植物","answer": "zhi2wu4","eng": "botanical; plant; vegetation; CL:種|种[zhong3]"},
    {"word": "职业","answer": "zhi2ye4","eng": "occupation; profession; vocation; professional"},
    {"word": "指","answer": "zhi3","eng": "finger; to point at or to; to indicate or refer to; to depend on; to count on; (of hair) to stand on end"},
    {"word": "只好","answer": "zhi3hao3","eng": "without any better option; to have to; to be forced to"},
    {"word": "只要","answer": "zhi3yao4","eng": "if only; so long as"},
    {"word": "质量","answer": "zhi4liang4","eng": "quality; mass (in physics); CL:個|个[ge4]"},
    {"word": "至少","answer": "zhi4shao3","eng": "at least; (to say the) least"},
    {"word": "制造","answer": "zhi4zao4","eng": "to manufacture; to make"},
    {"word": "中文","answer": "Zhong1wen2","eng": "Chinese; Chinese written language; Chinese writing"},
    {"word": "重点","answer": "zhong4dian3","eng": "emphasis; focal point; priority; key; with the emphasis on; focusing on"},
    {"word": "重视","answer": "zhong4shi4","eng": "to attach importance to sth; to value"},
    {"word": "周围","answer": "zhou1wei2","eng": "surroundings; environment; to encompass"},
    {"word": "猪","answer": "zhu1","eng": "hog; pig; swine; CL:口[kou3],頭|头[tou2]"},
    {"word": "逐渐","answer": "zhu2jian4","eng": "gradually"},
    {"word": "主动","answer": "zhu3dong4","eng": "to take the initiative; to do sth of one's own accord; active; opposite: passive 被動|被动[bei4 dong4]; drive (of gears and shafts etc)"},
    {"word": "主意","answer": "zhu3yi5","eng": "plan; idea; decision; CL:個|个[ge4]"},
    {"word": "祝贺","answer": "zhu4he4","eng": "to congratulate; congratulations; CL:個|个[ge4]"},
    {"word": "著名","answer": "zhu4ming2","eng": "famous; noted; well-known; celebrated"},
    {"word": "专门","answer": "zhuan1men2","eng": "specialist; specialized; customized"},
    {"word": "专业","answer": "zhuan1ye4","eng": "specialty; specialized field; main field of study (at university); major; CL:門|门[men2],個|个[ge4]; professional"},
    {"word": "赚","answer": "zhuan4","eng": "earn; make a profit"},
    {"word": "撞","answer": "zhuang4","eng": "to hit; to strike; to meet by accident; to run into; to bump against; to bump into"},
    {"word": "准确","answer": "zhun3que4","eng": "accurate; exact; precise"},
    {"word": "准时","answer": "zhun3shi2","eng": "on time; punctual; on schedule"},
    {"word": "仔细","answer": "zi3xi4","eng": "careful; attentive; cautious"},
    {"word": "自然","answer": "zi4ran2","eng": "nature; natural; naturally"},
    {"word": "总结","answer": "zong3jie2","eng": "to sum up; to conclude; summary; resume; CL:個|个[ge4]"},
    {"word": "租","answer": "zu1","eng": "to hire; to rent; to charter; to rent out; to lease out; rent; land tax"},
    {"word": "组成","answer": "zu3cheng2","eng": "component; part; element; constitute; make up"},
    {"word": "组织","answer": "zu3zhi1","eng": "to organize; organization; organized system; nerve; tissue; CL:個|个[ge4]"},
    {"word": "嘴","answer": "zui3","eng": "mouth; beak; spout (of teapot etc); CL:張|张[zhang1],個|个[ge4]"},
    {"word": "最好","answer": "zui4hao3","eng": "best; (you) had better (do what we suggest)"},
    {"word": "最后","answer": "zui4hou4","eng": "final; last; finally; ultimate"},
    {"word": "尊重","answer": "zun1zhong4","eng": "esteem; respect; to honor; to value sth"},
    {"word": "座","answer": "zuo4","eng": "seat; base; stand; CL:個|个[ge4]; classifier for buildings, mountains and similar immovable objects"},
    {"word": "做生意","answer": "zuo4sheng1yi4","eng": "to do business"},
    {"word": "座位","answer": "zuo4wei4","eng": "seat; CL:個|个[ge4]"},
    {"word": "作者","answer": "zuo4zhe3","eng": "author; writer; CL:個|个[ge4]"},
    {"word": "爱情","answer": "ai4qing2","eng": "romance; love (romantic); CL:個|个[ge4]"}
];