export const hsk1 = [
    {"word": "我", "answer": "wo3,wǒ", "eng": "I, me"},
    {"word": "我们", "answer": "wo3men,wǒmen", "eng": "we, us"},
    {"word": "你", "answer": "ni3,nǐ", "eng": "you (singular)"},
    {"word": "你们", "answer": "ni3men,nǐmen", "eng": "you (plural), you all"},
    {"word": "他", "answer": "ta1,tā", "eng": "he, him"},
    {"word": "她", "answer": "ta1,tā", "eng": "she, her"},
    {"word": "它", "answer": "ta1,tā", "eng": "it"},
    {"word": "他们", "answer": "ta1men,tāmen", "eng": "they, them (masculine)"},
    {"word": "她们", "answer": "ta1men,tāmen", "eng": "they, them (feminine)"},
    {"word": "这", "answer": "zhe4,zhè", "eng": "this; here"},
    {"word": "那", "answer": "na4,nà", "eng": "that; there"},
    {"word": "什么", "answer": "shen2me,shénme", "eng": "what"},
    {"word": "多少", "answer": "duo1shao3,duōshǎo", "eng": "how much, how many"},
    {"word": "几", "answer": "ji3,jǐ", "eng": "a few, how many"},
    {"word": "怎么", "answer": "zen3me,zěnme", "eng": "how"},
    {"word": "怎么样", "answer": "zen3meyang4,zěnmeyàng", "eng": "how"},
    {"word": "一", "answer": "yi1,yī", "eng": "one"},
    {"word": "二", "answer": "er4,èr", "eng": "two"},
    {"word": "三", "answer": "san1,sān", "eng": "three"},
    {"word": "四", "answer": "si4,sì", "eng": "four"},
    {"word": "五", "answer": "wu3,wǔ", "eng": "five"},
    {"word": "六", "answer": "liu4,liù", "eng": "six"},
    {"word": "七", "answer": "qi1,qī", "eng": "seven"},
    {"word": "八", "answer": "ba1,bā", "eng": "eight"},
    {"word": "九", "answer": "jiu3,jiǔ", "eng": "nine"},
    {"word": "十", "answer": "shi2,shí", "eng": "ten"},
    {"word": "零", "answer": "ling2,líng", "eng": "zero"},
    {"word": "个", "answer": "ge4,gè,ge", "eng": "counter word for people, general"},
    {"word": "岁", "answer": "sui4,suì", "eng": "age, years old"},
    {"word": "些", "answer": "xie1,xiē", "eng": "some"},
    {"word": "块", "answer": "kuai4,kuài", "eng": "pieces"},
    {"word": "本", "answer": "ben3,běn", "eng": "volume"},
    {"word": "不", "answer": "bu4,bù", "eng": "not"},
    {"word": "没", "answer": "mei2,méi", "eng": "not have"},
    {"word": "太", "answer": "tai4,tài", "eng": "too (excessive)"},
    {"word": "都", "answer": "dou1,dōu", "eng": "all"},
    {"word": "很", "answer": "hen3,hěn", "eng": "very"},
    {"word": "和", "answer": "he2,hé", "eng": "and"},
    {"word": "在", "answer": "zai4,zài", "eng": "at"},
    {"word": "的", "answer": "de", "eng": "possessive marker"},
    {"word": "了", "answer": "le,liao3,liǎo", "eng": "completion marker"},
    {"word": "吗", "answer": "ma", "eng": "word marker"},
    {"word": "呢", "answer": "ne", "eng": "word marker v2"},
    {"word": "喂", "answer": "wei2,wéi,wei4,wèi", "eng": "hey"},
    {"word": "家", "answer": "jia1,jiā", "eng": "home"},
    {"word": "学校", "answer": "xue2xiao4,xuéxiào", "eng": "school"},
    {"word": "饭店", "answer": "fan4dian4,fàndiàn", "eng": "restaurant"},
    {"word": "商店", "answer": "shang1dian4,shāngdiàn", "eng": "store"},
    {"word": "医院", "answer": "yi1yuan4,yīyuàn", "eng": "hospital"},
    {"word": "火车站", "answer": "huo3che1zhan4,huǒchēzhàn", "eng": "train station"},
    {"word": "中国", "answer": "zhong1guo2,zhōngguó", "eng": "China"},
    {"word": "北京", "answer": "bei3jing1,běijīng", "eng": "Beijing"},
    {"word": "上", "answer": "shang4,shàng", "eng": "up, on, over"},
    {"word": "下", "answer": "xia4,xià", "eng": "down, under"},
    {"word": "前面", "answer": "qian2mian4,qiánmiàn", "eng": "front side"},
    {"word": "后面", "answer": "hou4mian4,hòumiàn", "eng": "back side, behind"},
    {"word": "里面", "answer": "li3mian4,lǐmiàn", "eng": "inside"},
    {"word": "今天", "answer": "jin1tian1,jīntiān", "eng": "today"},
    {"word": "明天", "answer": "ming2tian1,míngtiān", "eng": "tomorrow"},
    {"word": "昨天", "answer": "zuo2tian1,zuótiān", "eng": "yesterday"},
    {"word": "上午", "answer": "shang4wu3,shàngwǔ", "eng": "morning"},
    {"word": "中午", "answer": "zhong1wu3,zhōngwǔ", "eng": "noon"},
    {"word": "下午", "answer": "xia4wu3,xiàwǔ", "eng": "afternoon"},
    {"word": "年", "answer": "nian2,nián", "eng": "year"},
    {"word": "月", "answer": "yue4,yuè", "eng": "moon, month"},
    {"word": "日", "answer": "ri4,rì", "eng": "day, sun"},
    {"word": "星期", "answer": "xing1qi1,xīngqī", "eng": "week"},
    {"word": "分钟", "answer": "fen1zhong1,fēnzhōng", "eng": "minute"},
    {"word": "点", "answer": "dian3,diǎn", "eng": "dot"},
    {"word": "现在", "answer": "xian4zai4,xiànzài", "eng": "now"},
    {"word": "时候", "answer": "shi2hou4,shíhòu", "eng": "time"},
    {"word": "爸爸", "answer": "ba4ba,bàba", "eng": "dad, father"},
    {"word": "妈妈", "answer": "ma1ma,māma", "eng": "mom, mother"},
    {"word": "儿子", "answer": "er2zi,érzi", "eng": "son"},
    {"word": "女儿", "answer": "nü3er2,nǚér", "eng": "daughter"},
    {"word": "老师", "answer": "lao3shi1,lǎoshī", "eng": "teacher"},
    {"word": "学生", "answer": "xue2sheng1,xuéshēng", "eng": "student"},
    {"word": "同学", "answer": "tong2xue2,tóngxué", "eng": "schoolmate"},
    {"word": "朋友", "answer": "peng2you3,péngyǒu", "eng": "friend"},
    {"word": "医生", "answer": "yi1sheng1,yīshēng", "eng": "doctor"},
    {"word": "先生", "answer": "xian1sheng1,xiānshēng", "eng": "sir"},
    {"word": "小姐", "answer": "xiao3jie3,xiǎojiě", "eng": "ma'am"},
    {"word": "衣服", "answer": "yi1fu2,yīfú", "eng": "clothes"},
    {"word": "水", "answer": "shui3,shuǐ", "eng": "water"},
    {"word": "菜", "answer": "cai4,cài", "eng": "cuisine"},
    {"word": "米饭", "answer": "mi3fan4,mǐfàn", "eng": "cooked rice, meal"},
    {"word": "水果", "answer": "shui3guo3,shuǐguǒ", "eng": "fruit"},
    {"word": "苹果", "answer": "ping2guo3,píngguǒ", "eng": "apple"},
    {"word": "茶", "answer": "cha2,chá", "eng": "tea"},
    {"word": "杯子", "answer": "bei1zi,bēizi", "eng": "cup"},
    {"word": "钱", "answer": "qian2,qián", "eng": "money"},
    {"word": "飞机", "answer": "fei1ji1,fēijī", "eng": "airplane"},
    {"word": "出租车", "answer": "chu1zu1che1,chūzūchē", "eng": "taxi"},
    {"word": "电视", "answer": "dian4shi4,diànshì", "eng": "television"},
    {"word": "电脑", "answer": "dian4nao3,diànnǎo", "eng": "computer"},
    {"word": "电影", "answer": "dian4ying3,diànyǐng", "eng": "movie"},
    {"word": "天气", "answer": "tian1qi4,tiānqì", "eng": "weather"},
    {"word": "猫", "answer": "mao1,māo", "eng": "cat"},
    {"word": "狗", "answer": "gou3,gǒu", "eng": "dog"},
    {"word": "东西", "answer": "dong1xi,dōngxi", "eng": "thing, things, stuff"},
    {"word": "人", "answer": "ren2,rén", "eng": "person"},
    {"word": "名字", "answer": "ming2zi4,míngzì", "eng": "name"},
    {"word": "书", "answer": "shu1,shū", "eng": "book"},
    {"word": "汉语", "answer": "han4yu3,hànyǔ", "eng": "Chinese language"},
    {"word": "字", "answer": "zi4,zì", "eng": "character, symbol"},
    {"word": "桌子", "answer": "zhuo1zi,zhuōzi", "eng": "table, desk"},
    {"word": "椅子", "answer": "yi3zi,yǐzi", "eng": "chair"},
    {"word": "谢谢", "answer": "xie4xie,xièxie", "eng": "thank you, thanks"},
    {"word": "不客气", "answer": "bu2ke4qi4,búkèqì", "eng": "you're welcome"},
    {"word": "再见", "answer": "zai4jian4,zàijiàn", "eng": "goodbye"},
    {"word": "请", "answer": "qing3,qǐng", "eng": "please"},
    {"word": "对不起", "answer": "dui4bu4qi3,duìbùqǐ", "eng": "I'm sorry"},
    {"word": "没关系", "answer": "mei2guan1xi4,méiguānxì", "eng": "it's ok"},
    {"word": "是", "answer": "shi4,shì", "eng": "to be, am, is, are, was, were"},
    {"word": "有", "answer": "you3,yǒu", "eng": "to have"},
    {"word": "看", "answer": "kan4,kàn", "eng": "to look, to see, to read"},
    {"word": "听", "answer": "ting1,tīng", "eng": "to listen, to hear"},
    {"word": "说", "answer": "shuo1,shuō", "eng": "to speak, to talk"},
    {"word": "读", "answer": "du2,dú", "eng": "to read"},
    {"word": "写", "answer": "xie3,xiě", "eng": "to write"},
    {"word": "看见", "answer": "kan4jian4,kànjiàn", "eng": "to see"},
    {"word": "叫", "answer": "jiao4,jiào", "eng": "to be called, to call to"},
    {"word": "来", "answer": "lai2,lái", "eng": "to come"},
    {"word": "回", "answer": "hui2,huí", "eng": "to return, to come back"},
    {"word": "去", "answer": "qu4,qù", "eng": "to go"},
    {"word": "吃", "answer": "chi1,chī", "eng": "to eat"},
    {"word": "喝", "answer": "he1,hē", "eng": "to drink"},
    {"word": "睡觉", "answer": "shui4jiao4,shuìjiào", "eng": "to sleep"},
    {"word": "打电话", "answer": "da3dian4hua4,dǎdiànhuà", "eng": "to call on the phone"},
    {"word": "做", "answer": "zuo4,zuò", "eng": "to do"},
    {"word": "买", "answer": "mai3,mǎi", "eng": "to buy"},
    {"word": "开", "answer": "kai1,kāi", "eng": "to open, to turn on, to drive, to begin, to start"},
    {"word": "坐", "answer": "zuo4,zuò", "eng": "to sit, to ride as passenger"},
    {"word": "住", "answer": "zhu4,zhù", "eng": "to live"},
    {"word": "学习", "answer": "xue2xi2,xuéxí", "eng": "to study, to learn"},
    {"word": "工作", "answer": "gong1zuo4,gōngzuò", "eng": "to work"},
    {"word": "下雨", "answer": "xia4yu3,xiàyǔ", "eng": "to rain"},
    {"word": "爱", "answer": "ai4,ài", "eng": "love, to love"},
    {"word": "喜欢", "answer": "xi3huan1,xǐhuān", "eng": "to like"},
    {"word": "想", "answer": "xiang3,xiǎng", "eng": "to want"},
    {"word": "认识", "answer": "ren4shi2,rènshí", "eng": "to know someone, to meet"},
    {"word": "会", "answer": "hui4,huì", "eng": "to be able to"},
    {"word": "能", "answer": "neng2,néng", "eng": "to be able to"},
    {"word": "好", "answer": "hao3,hǎo", "eng": "good"},
    {"word": "大", "answer": "da4,dà", "eng": "big"},
    {"word": "小", "answer": "xiao3,xiǎo", "eng": "small"},
    {"word": "多", "answer": "duo1,duō", "eng": "a lot, many"},
    {"word": "少", "answer": "shao3,shǎo", "eng": "a few, little"},
    {"word": "冷", "answer": "leng3,lěng", "eng": "cold"},
    {"word": "热", "answer": "re4,rè", "eng": "hot"},
    {"word": "高兴", "answer": "gao1xing4,gāoxìng", "eng": "happy, glad"},
    {"word": "漂亮", "answer": "piao4liang4,piao4liang,piàoliàng,piàoliang", "eng": "beautiful, pretty"},
    {"word": "饭馆", "answer": "fan4guan3,fànguǎn", "eng": "restaurant"},
    {"word": "下雪", "answer": "xia4xue3,xiàxuě", "eng": "to snow"},
    {"word": "雨", "answer": "yu3,yǔ", "eng": "rain"},
    {"word": "雪", "answer": "xue3,xuě", "eng": "snow"},
    {"word": "国", "answer": "guo2,guó", "eng": "country, kingdom"},
    {"word": "美国", "answer": "mei3guo2,měiguó", "eng": "America, USA"},
    {"word": "德国", "answer": "de2guo2,déguó", "eng": "Germany"},
    {"word": "法国", "answer": "fa4guo2,fa3guo2,fàguó,fǎguó", "eng": "France"},
    {"word": "俄国", "answer": "e2guo2,éguó", "eng": "Russia"},
    {"word": "日本", "answer": "ri4ben3,rìběn", "eng": "Japan"},
    {"word": "中文", "answer": "zhong1wen2,zhōngwén", "eng": "Chinese language"},
    {"word": "英文", "answer": "ying1wen2,yīngwén", "eng": "English language"},
    {"word": "北", "answer": "bei3,běi", "eng": "north"},
    {"word": "东", "answer": "dong1,dōng", "eng": "east"},
    {"word": "西", "answer": "xi1,xī", "eng": "west"},
    {"word": "南", "answer": "nan2,nán", "eng": "south"},
    {"word": "西南", "answer": "xi1nan2,xīnán", "eng": "southwest"},
    {"word": "西北", "answer": "xi1bei3,xīběi", "eng": "northwest"},
    {"word": "东南", "answer": "dong1nan2,dōngnán", "eng": "southeast"},
    {"word": "东北", "answer": "dong1bei3,dōngběi", "eng": "northeast"},
    {"word": "市", "answer": "shi4,shì", "eng": "city"},
    {"word": "东京", "answer": "dong1jing1,dōngjīng", "eng": "Tokyo"},
    {"word": "红色", "answer": "hong2se4,hóngsè", "eng": "red"},
    {"word": "绿色", "answer": "lü4se4,lǜsè", "eng": "green"},
    {"word": "颜色", "answer": "yan2se4,yánsè", "eng": "color"},
    {"word": "黄色", "answer": "huang2se4,huángsè", "eng": "yellow"},
    {"word": "白色", "answer": "bai2se4,báisè", "eng": "white"},
    {"word": "黑色", "answer": "hei1se4,hēisè", "eng": "black"},
    {"word": "橙", "answer": "cheng2,chéng", "eng": "orange"},
    {"word": "蓝色", "answer": "lan2se4,lánsè", "eng": "blue"},
    {"word": "男人", "answer": "nan2ren2,nánrén", "eng": "man"},
    {"word": "男", "answer": "nan2,nán", "eng": "male"},
    {"word": "女人", "answer": "nü3ren2,nǚrén", "eng": "woman"},
    {"word": "女", "answer": "nü3,nǚ", "eng": "female"},
    {"word": "中", "answer": "zhong1,zhōng", "eng": "middle"},
    {"word": "出", "answer": "chu1,chū", "eng": "to go out"},
    {"word": "关", "answer": "guan1,guān", "eng": "to close, to turn off"},
    {"word": "高", "answer": "gao1,gāo", "eng": "tall, high"},
    {"word": "谁", "answer": "shui2,shuí,shei2,shéi", "eng": "who, whom"},
    {"word": "哪", "answer": "na3,nǎ", "eng": "what, which, where"},
    {"word": "子", "answer": "zi,zi3,zǐ", "eng": "child"},
    {"word": "星期一", "answer": "xing1qi1yi1,xīngqīyī", "eng": "Monday"},
    {"word": "星期二", "answer": "xing1qi1er4,xīngqīèr", "eng": "Tuesday"},
    {"word": "星期三", "answer": "xing1qi1san1,xīngqīsān", "eng": "Wednesday"},
    {"word": "星期四", "answer": "xing1qi1si4,xīngqīsì", "eng": "Thursday"},
    {"word": "星期五", "answer": "xing1qi1wu3,xīngqīwǔ", "eng": "Friday"},
    {"word": "星期六", "answer": "xing1qi1liu4,xīngqīliù", "eng": "Saturday"},
    {"word": "星期天", "answer": "xing1qi1tian1,xīngqītiān", "eng": "Sunday"},
    {"word": "左", "answer": "zuo3,zuǒ", "eng": "left"},
    {"word": "右", "answer": "you4,yòu", "eng": "right"},
    {"word": "左边", "answer": "zuo3bian1,zuǒbiān", "eng": "left side"},
    {"word": "右边", "answer": "you4bian1,yòubiān", "eng": "right side"},
    {"word": "早", "answer": "zao3,zǎo", "eng": "early"},
    {"word": "早上", "answer": "zao3shang4,zǎoshàng", "eng": "morning"},
    {"word": "晚上", "answer": "wan3shang4,wǎnshàng", "eng": "evening"},
    {"word": "晚安", "answer": "wan3an1,wǎnān", "eng": "good night"},
    {"word": "安", "answer": "an1,ān", "eng": "rest, calm"},
    {"word": "鱼", "answer": "yu2,yú", "eng": "fish"},
    {"word": "夜", "answer": "ye4,yè", "eng": "night"},
    {"word": "蔬菜", "answer": "shu1cai4,shūcài", "eng": "vegetables"},
    {"word": "汉字", "answer": "han4zi4,hànzì", "eng": "Chinese character, hanzi"},
    {"word": "非常", "answer": "fei1chang2,fēicháng", "eng": "very"},
    {"word": "咖啡", "answer": "ka1fei1,kāfēi", "eng": "coffee"},
    {"word": "太阳", "answer": "tai4yang2,tàiyáng", "eng": "the sun"},
    {"word": "打", "answer": "da3,dǎ", "eng": "to hit, to strike"},
    {"word": "电话", "answer": "dian4hua4,diànhuà", "eng": "telephone"},
    {"word": "卖", "answer": "mai4,mài", "eng": "to sell"},
    {"word": "国家", "answer": "guo2jia1,guójiā", "eng": "country"},
    {"word": "上班", "answer": "shang4ban1,shàngbān", "eng": "to go to work"},
    {"word": "下班", "answer": "xia4ban1,xiàbān", "eng": "to leave from work"},
    {"word": "起床", "answer": "qi3chuang2,qǐchuáng", "eng": "to wake up"},
    {"word": "床", "answer": "chuang2,chuáng", "eng": "bed"},
    {"word": "汽车", "answer": "qi4che1,qìchē", "eng": "car"},
    {"word": "火车", "answer": "huo3che1,huǒchē", "eng": "train"},
    {"word": "月亮", "answer": "yue4liang4,yuèliàng", "eng": "the moon"},
    {"word": "洗手间", "answer": "xi3shou3jian1,xǐshǒujiān", "eng": ""},
    {"word": "洗", "answer": "xi3,xǐ", "eng": "to wash"},
    {"word": "手", "answer": "shou3,shǒu", "eng": "hand, hands"},
    {"word": "手机", "answer": "shou3ji1,shǒujī", "eng": "cell phone"},
    {"word": "机", "answer": "ji1,jī", "eng": "device, desk, machine, moment"},
    {"word": "站", "answer": "zhan4,zhàn", "eng": "to stand"},
    {"word": "白", "answer": "bai2,bái", "eng": "white"},
    {"word": "黑", "answer": "hei1,hēi", "eng": "black"},
    {"word": "蓝", "answer": "lan2,lán", "eng": "blue"},
    {"word": "绿", "answer": "lü4,lǜ", "eng": "green"},
    {"word": "黄", "answer": "huang2,huáng", "eng": "yellow"},
    {"word": "红", "answer": "hong2,hóng", "eng": "red"},
    {"word": "百", "answer": "bai3,bǎi", "eng": "hundred"},
    {"word": "千", "answer": "qian1,qiān", "eng": "thousand"},
    {"word": "哥哥", "answer": "ge1ge,gēge", "eng": "older brother"},
    {"word": "弟弟", "answer": "di4di,dìdi", "eng": "younger brother"},
    {"word": "妹妹", "answer": "mei4mei,mèimei", "eng": "younger sister"},
    {"word": "姐姐", "answer": "jie3jie,jiějie", "eng": "older sister"},
    {"word": "飞", "answer": "fei1,fēi", "eng": "to fly"},
    {"word": "时", "answer": "shi2,shí", "eng": "time, season; era, age, period"},
    {"word": "对", "answer": "dui4,duì", "eng": "correct, right; facing, opposed"},
    {"word": "生", "answer": "sheng1,shēng", "eng": "life, living, lifetime; birth"},
    {"word": "后", "answer": "hou4,hòu", "eng": "behind, rear, after"},
    {"word": "里", "answer": "li3,lǐ", "eng": "unit of distance; village; lane"},
    {"word": "么", "answer": "me", "eng": "interrogative particle; repetition of a tune small; tender"},
    {"word": "学", "answer": "xue2,xué", "eng": "learning, knowledge; school"},
    {"word": "同", "answer": "tong2,tóng", "eng": "same, similar; together with"},
    {"word": "现", "answer": "xian4,xiàn", "eng": "appear, manifest, become visible"},
    {"word": "面", "answer": "mian4,miàn", "eng": "face; surface; plane; side, dimension"},
    {"word": "起", "answer": "qi3,qǐ", "eng": "rise, stand up; go up; begin"},
    {"word": "天", "answer": "tian1,tiān", "eng": "sky, heaven; god, celestial"},
    {"word": "分", "answer": "fen1,fēn", "eng": "divide; small unit of time etc."},
    {"word": "错", "answer": "cuo4,cuò", "eng": "wrong"},
    {"word": "样", "answer": "yang4,yàng", "eng": "shape, form, pattern, style"},
    {"word": "羊", "answer": "yang2,yáng", "eng": "sheep"},
    {"word": "前", "answer": "qian2,qián", "eng": "in front, forward; preceding"},
    {"word": "工", "answer": "gong1,gōng", "eng": "labor, work; worker, laborer"},
    {"word": "明", "answer": "ming2,míng", "eng": "bright, light, brilliant; clear"},
    {"word": "见", "answer": "jian4,jiàn", "eng": "see, observe, behold; perceive"},
    {"word": "什", "answer": "shen2,shén", "eng": "file of ten soldiers; mixed, miscellaneous"},
    {"word": "果", "answer": "guo3,guǒ", "eng": "fruit; result"},
    {"word": "话", "answer": "hua4,huà", "eng": "speech, talk, language; dialect"},
    {"word": "老", "answer": "lao3,lǎo", "eng": "old, aged; experienced"},
    {"word": "先", "answer": "xian1,xiān", "eng": "first, former, previous"},
    {"word": "儿", "answer": "er2,ér", "eng": "son, child"},
    {"word": "电", "answer": "dian4,diàn", "eng": "electricity; electric; lightning"},
    {"word": "再", "answer": "zai4,zài", "eng": "again, twice, re-"},
    {"word": "系", "answer": "xi4,xì", "eng": "system; line, link, connection"},
    {"word": "认", "answer": "ren4,rèn", "eng": "recognize, know, understand"},
    {"word": "气", "answer": "qi4,qì", "eng": "steam, vapor"},
    {"word": "名", "answer": "ming2,míng", "eng": "name, rank, title, position"},
    {"word": "期", "answer": "qi1,qī", "eng": "period of time; date; time limit"},
    {"word": "觉", "answer": "jue2,jué,jiao4,jiào", "eng": "to wake up from sleep; conscious"},
    {"word": "师", "answer": "shi1,shī", "eng": "teacher, master, specialist"},
    {"word": "今", "answer": "jin1,jīn", "eng": "now, today, modern era"},
    {"word": "院", "answer": "yuan4,yuàn", "eng": "courtyard, yard, court; school"},
    {"word": "识", "answer": "shi2,shí", "eng": "recognize, understand, know"},
    {"word": "候", "answer": "hou4,hòu", "eng": "wait; expect; visit; greet"},
    {"word": "车", "answer": "che1,chē", "eng": "cart, vehicle; carry in cart"},
    {"word": "服", "answer": "fu2,fú", "eng": "clothes; wear, dress"},
    {"word": "怎", "answer": "zen3,zěn", "eng": "what? why? how?"},
    {"word": "影", "answer": "ying3,yǐng", "eng": "shadow; image, reflection; photograph"},
    {"word": "商", "answer": "shang1,shāng", "eng": "commerce, business, trade"},
    {"word": "视", "answer": "shi4,shì", "eng": "look at, inspect, observe, see"},
    {"word": "医", "answer": "yi1,yī", "eng": "cure, heal; doctor, medical"},
    {"word": "号", "answer": "hao4,hào", "eng": "mark, sign; symbol; number"},
    {"word": "语", "answer": "yu3,yǔ", "eng": "language, words; saying, expression"},
    {"word": "兴", "answer": "xing4,xìng", "eng": "thrive, prosper, flourish"},
    {"word": "星", "answer": "xing1,xīng", "eng": "a star, planet; any point of light"},
    {"word": "星星", "answer": "xing1xing1,xing1xing,xīngxīng,xīngxing", "eng": "star"},
    {"word": "京", "answer": "jing1,jīng", "eng": "capital city"},
    {"word": "米", "answer": "mi3,mǐ", "eng": "hulled or husked uncooked rice"},
    {"word": "客", "answer": "ke4,kè", "eng": "guest, traveller; customer"},
    {"word": "友", "answer": "you3,yǒu", "eng": "friend, companion; fraternity"},
    {"word": "校", "answer": "xiao4,xiào", "eng": "school; military field officer"},
    {"word": "脑", "answer": "nao3,nǎo", "eng": "brain"},
    {"word": "喜", "answer": "xi3,xǐ", "eng": "like, love, enjoy; joyful thing"},
    {"word": "欢", "answer": "huan1,huān", "eng": "happy, pleased, glad; joy; enjoy"},
    {"word": "汉", "answer": "han4,hàn", "eng": "Chinese people, Chinese language"},
    {"word": "衣", "answer": "yi1,yī", "eng": "clothes, clothing; cover, skin"},
    {"word": "亮", "answer": "liang4,liàng", "eng": "bright, brilliant, radiant, light"},
    {"word": "两", "answer": "liang3,liǎng", "eng": "two (when counting things)"},
    {"word": "朋", "answer": "peng2,péng", "eng": "friend, pal, acquaintance"},
    {"word": "谢", "answer": "xie4,xiè", "eng": "to thank"},
    {"word": "钟", "answer": "zhong1,zhōng", "eng": "clock; bell"},
    {"word": "饭", "answer": "fan4,fàn", "eng": "cooked rice; food, meal"},
    {"word": "睡", "answer": "shui4,shuì", "eng": "sleep, doze"},
    {"word": "午", "answer": "wu3,wǔ", "eng": "noon"},
    {"word": "店", "answer": "dian4,diàn", "eng": "shop, store; inn, hotel"},
    {"word": "租", "answer": "zu1,zū", "eng": "rent, lease; rental; tax"},
    {"word": "漂", "answer": "piao4,piào", "eng": "float, drift; tossed about"},
    {"word": "票", "answer": "piao4,piào", "eng": "ticket"},
    {"word": "苹", "answer": "ping2,píng", "eng": "artemisia; duckweed; apple"},
    {"word": "大家", "answer": "da4jia1,dàjiā", "eng": "everyone, everybody"},
    {"word": "班", "answer": "ban1,bān", "eng": "class, group, grade; squad; job"},
    {"word": "汽", "answer": "qi4,qì", "eng": "steam, vapor, gas"}
];