export const hsk3 = [
    {"word": "阿姨","answer": "ㄚㄧˊ,a1yi2","eng": "maternal aunt, step-mother, childcare worker, nursemaid, woman of similar age to one's parents (term of address used by child), CL:個[gè]"},
    {"word": "啊","answer": "ㄚ,ㄚˊ,ㄚˇ,ㄚˋ,ㄚ˙,a1,a2,a3,a4,a5","eng": "modal particle ending sentence, showing affirmation, approval, or consent"},
    {"word": "矮","answer": "ㄞˇ,ai3","eng": "low, short (in length)"},
    {"word": "爱好","answer": "ㄞˋㄏㄠˋ,ai4hao4","eng": "to like, to take pleasure in, keen on, fond of, interest, hobby, appetite for, CL:個[gè]"},
    {"word": "安静","answer": "ㄢㄐㄧㄥˋ,an1jing4","eng": "quiet, peaceful, calm"},
    {"word": "把","answer": "ㄅㄚˇ,ㄅㄚˋ,ba3,ba4","eng": "to hold, to contain, to grasp, to take hold of, handle, particle marking the following noun as a direct object, classifier for objects with handle, classifier for small objects: handful"},
    {"word": "搬","answer": "ㄅㄢ,ban1","eng": "to move, to shift, to remove, to transport, to apply indiscriminately, to copy mechanically"},
    {"word": "班","answer": "ㄅㄢ,ban1","eng": "team, class, squad, work shift, ranking, CL:個[gè], classifier for groups"},
    {"word": "半","answer": "ㄅㄢˋ,ban4","eng": "half, semi-, incomplete, (after a number) and a half"},
    {"word": "办法","answer": "ㄅㄢˋㄈㄚˇ,ban4fa3","eng": "means, method, way (of doing sth), CL:條,個[gè]"},
    {"word": "办公室","answer": "ㄅㄢˋㄍㄨㄥㄕˋ,ban4gong1shi4","eng": "office, business premises, bureau, CL:間[jiān]"},
    {"word": "帮忙","answer": "ㄅㄤㄇㄤˊ,bang1mang2","eng": "to help, to lend a hand, to do a favor, to do a good turn"},
    {"word": "包","answer": "ㄅㄠ,ㄆㄠˋ,bao1,pao4","eng": "to cover, to wrap, to hold, to include, to take charge of, to contract (to or for), package, wrapper, container, bag, to hold or embrace, bundle, packet, CL:個,隻[zhī]"},
    {"word": "饱","answer": "ㄅㄠˇ,bao3","eng": "to eat till full, satisfied"},
    {"word": "北方","answer": "ㄅㄟˇㄈㄤ,bei3fang1","eng": "north, the northern part a country, China north of the Yellow River"},
    {"word": "被","answer": "ㄅㄟˋ,ㄆㄧ,bei4,pi1","eng": "quilt, by, (indicates passive-voice clauses), (literary) to cover, to meet with"},
    {"word": "鼻子","answer": "ㄅㄧˊㄗ˙,bi2zi5","eng": "nose, CL:個,隻[zhī]"},
    {"word": "比较","answer": "ㄅㄧˇㄐㄧㄠˋ,bi3jiao4","eng": "to compare, to contrast, comparatively, relatively, quite, comparison"},
    {"word": "比赛","answer": "ㄅㄧˇㄙㄞˋ,bi3sai4","eng": "competition (sports etc), match, CL:場,次[cì]"},
    {"word": "必须","answer": "ㄅㄧˋㄒㄩ,bi4xu1","eng": "to have to, must, compulsory, necessarily"},
    {"word": "变化","answer": "ㄅㄧㄢˋㄏㄨㄚˋ,bian4hua4","eng": "change, variation, to change, to vary, CL:個[gè]"},
    {"word": "表示","answer": "ㄅㄧㄠˇㄕˋ,biao3shi4","eng": "to express, to show, to say, to state, to indicate, to mean"},
    {"word": "表演","answer": "ㄅㄧㄠˇㄧㄢˇ,biao3yan3","eng": "play, show, performance, exhibition, to perform, to act, to demonstrate, CL:場[chǎng]"},
    {"word": "别人","answer": "ㄅㄧㄝˊㄖㄣˊ,bie2ren2","eng": "other people, others, other person"},
    {"word": "宾馆","answer": "ㄅㄧㄣㄍㄨㄢˇ,bin1guan3","eng": "guesthouse, lodge, hotel, CL:個,家[jiā]"},
    {"word": "冰箱","answer": "ㄅㄧㄥㄒㄧㄤ,bing1xiang1","eng": "icebox, freezer cabinet, refrigerator, CL:臺,個[gè]"},
    {"word": "才（纔）","answer": "ㄘㄞˊ,cai2","eng": "a moment ago, just now, (preceded by a clause of condition or reason) not until, (followed by a numerical clause) only"},
    {"word": "菜单","answer": "ㄘㄞˋㄉㄢ,cai4dan1","eng": "menu, CL:份,張[zhāng]"},
    {"word": "参加","answer": "ㄘㄢㄐㄧㄚ,can1jia1","eng": "to participate, to take part, to join"},
    {"word": "草","answer": "ㄘㄠˇ,cao3","eng": "grass, straw, manuscript, draft (of a document), careless, rough, CL:棵,撮,株,根[gēn]"},
    {"word": "层","answer": "ㄘㄥˊ,ceng2","eng": "layer, stratum, laminated, floor (of a building), storey, classifier for layers, repeated, sheaf (math.)"},
    {"word": "差","answer": "ㄔㄚ,ㄔㄞ,ㄘ,ㄘㄨㄛ,cha1,chai1,ci1,cuo1","eng": "to differ from, to fall short of, lacking, wrong, inferior"},
    {"word": "超市","answer": "ㄔㄠㄕˋ,chao1shi4","eng": "supermarket (abbr.), CL:家[jiā]"},
    {"word": "衬衫","answer": "ㄔㄣˋㄕㄢ,chen4shan1","eng": "shirt, blouse, CL:件[jiàn]"},
    {"word": "成绩","answer": "ㄔㄥˊㄐㄧ,cheng2ji1","eng": "achievement, performance records, grades, CL:項,個[gè]"},
    {"word": "城市","answer": "ㄔㄥˊㄕˋ,cheng2shi4","eng": "city, town, CL:座[zuò]"},
    {"word": "迟到","answer": "ㄔˊㄉㄠˋ,chi2dao4","eng": "to arrive late"},
    {"word": "出现","answer": "ㄔㄨㄒㄧㄢˋ,chu1xian4","eng": "to appear, to arise, to emerge, to show up"},
    {"word": "除了","answer": "ㄔㄨˊㄌㄜ˙,chu2le5","eng": "besides, apart from (... also...), in addition to, except (for)"},
    {"word": "厨房","answer": "ㄔㄨˊㄈㄤˊ,chu2fang2","eng": "kitchen, CL:間[jiān]"},
    {"word": "春","answer": "ㄔㄨㄣ,chun1","eng": "spring (time), gay, joyful, youthful, love, lust, life"},
    {"word": "词语","answer": "ㄘˊㄩˇ,ci2yu3","eng": "word (general term including monosyllables through to short phrases), term (e.g. technical term), expression"},
    {"word": "聪明","answer": "ㄘㄨㄥㄇㄧㄥˊ,cong1ming2","eng": "acute (of sight and hearing), clever, intelligent, bright, smart"},
    {"word": "打扫","answer": "ㄉㄚˇㄙㄠˇ,da3sao3","eng": "to clean, to sweep"},
    {"word": "打算","answer": "ㄉㄚˇㄙㄨㄢˋ,da3suan4","eng": "to plan, to intend, to calculate, plan, intention, calculation, CL:個[gè]"},
    {"word": "带","answer": "ㄉㄞˋ,dai4","eng": "band, belt, girdle, ribbon, tire, area, zone, region, CL:條[tiáo], to wear, to carry, to take along, to bear (i.e. to have), to lead, to bring, to look after, to raise"},
    {"word": "担心","answer": "ㄉㄢㄒㄧㄣ,dan1xin1","eng": "anxious, worried, uneasy, to worry, to be anxious"},
    {"word": "蛋糕","answer": "ㄉㄢˋㄍㄠ,dan4gao1","eng": "cake, CL:塊,個[gè]"},
    {"word": "当然","answer": "ㄉㄤㄖㄢˊ,dang1ran2","eng": "only natural, as it should be, certainly, of course, without doubt"},
    {"word": "地","answer": "ㄉㄧˋ,ㄉㄜ˙,di4,de5","eng": "-ly, structural particle: used before a verb or adjective, linking it to preceding modifying adverbial adjunct"},
    {"word": "灯","answer": "ㄉㄥ,deng1","eng": "lamp, light, lantern, CL:盞[zhǎn]"},
    {"word": "低","answer": "ㄉㄧ,di1","eng": "low, beneath, to lower (one's head), to let droop, to hang down, to incline"},
    {"word": "地方","answer": "ㄉㄧˋㄈㄤ,di4fang1","eng": "area, place, space, room, territory, CL:處,個,塊[kuài]"},
    {"word": "地铁","answer": "ㄉㄧˋㄊㄧㄝˇ,di4tie3","eng": "subway, metro"},
    {"word": "地图","answer": "ㄉㄧˋㄊㄨˊ,di4tu2","eng": "map, CL:張,本[běn]"},
    {"word": "电梯","answer": "ㄉㄧㄢˋㄊㄧ,dian4ti1","eng": "elevator, escalator, CL:臺,部[bù]"},
    {"word": "电子","answer": "ㄉㄧㄢˋㄗˇ,dian4zi3","eng": "electronic, electron (particle physics)"},
    {"word": "冬","answer": "ㄉㄨㄥ,dong1","eng": "sound of beating a drum, onomatopoeia for rat-a-tat etc"},
    {"word": "东","answer": "ㄉㄨㄥ,dong1","eng": "east, host (i.e. sitting on east side of guest), landlord"},
    {"word": "动物","answer": "ㄉㄨㄥˋㄨˋ,dong4wu4","eng": "animal, CL:隻,群,個[gè]"},
    {"word": "短","answer": "ㄉㄨㄢˇ,duan3","eng": "short or brief, to lack, weak point, fault"},
    {"word": "段","answer": "ㄉㄨㄢˋ,duan4","eng": "paragraph, section, segment, stage (of a process), classifier for stories, periods of time, lengths of thread etc"},
    {"word": "锻炼","answer": "ㄉㄨㄢˋㄌㄧㄢˋ,duan4lian4","eng": "to engage in physical exercise, to work out, to toughen, to temper"},
    {"word": "多么","answer": "ㄉㄨㄛㄇㄜ˙,duo1me5","eng": "how (wonderful etc), what (a great idea etc), however (difficult it may be etc)"},
    {"word": "饿","answer": "ㄜˋ,e4","eng": "to be hungry, hungry"},
    {"word": "而且","answer": "ㄦˊㄑㄧㄝˇ,er2qie3","eng": "(not only ...) but also, moreover, in addition, furthermore"},
    {"word": "耳朵","answer": "ㄦˇㄉㄨㄛ˙,er3duo5","eng": "ear, CL:隻,個,對[duì]"},
    {"word": "发烧","answer": "ㄈㄚㄕㄠ,fa1shao1","eng": "to have a high temperature (from illness), to have a fever"},
    {"word": "发现","answer": "ㄈㄚㄒㄧㄢˋ,fa1xian4","eng": "to find, to discover"},
    {"word": "方便","answer": "ㄈㄤㄅㄧㄢˋ,fang1bian4","eng": "convenient, to help out, to make things easy for people, convenience, suitable, having money to spare, (euphemism) to go to the toilet"},
    {"word": "放","answer": "ㄈㄤˇ,ㄈㄤˋ,fang3,fang4","eng": "to release, to free, to let go, to put, to place, to let out, to set off (fireworks)"},
    {"word": "放心","answer": "ㄈㄤˋㄒㄧㄣ,fang4xin1","eng": "to feel relieved, to feel reassured, to be at ease"},
    {"word": "分","answer": "ㄈㄣ,ㄈㄣˋ,fen1,fen4","eng": "to divide, to separate, to allocate, to distinguish (good and bad), part or subdivision, fraction, one tenth (of certain units), unit of length equivalent to 0.33 cm, minute, a point (in sports or games), 0.01 yuan (unit of money)"},
    {"word": "附近","answer": "ㄈㄨˋㄐㄧㄣˋ,fu4jin4","eng": "(in the) vicinity, nearby, neighboring, next to"},
    {"word": "复习","answer": "ㄈㄨˋㄒㄧˊ,fu4xi2","eng": "variant of 復習|复习, to revise, to review, revision"},
    {"word": "干净","answer": "ㄍㄢㄐㄧㄥˋ,gan1jing4","eng": "clean, neat"},
    {"word": "敢","answer": "ㄍㄢˇ,gan3","eng": "to dare, daring, (polite) may I venture"},
    {"word": "感冒","answer": "ㄍㄢˇㄇㄠˋ,gan3mao4","eng": "to catch cold, (common) cold, CL:場,次[cì]"},
    {"word": "刚才","answer": "ㄍㄤㄘㄞˊ,gang1cai2","eng": "(just) a moment ago"},
    {"word": "根据","answer": "ㄍㄣㄐㄩˋ,gen1ju4","eng": "according to, based on, basis, foundation, CL:個[gè]"},
    {"word": "跟","answer": "ㄍㄣ,gen1","eng": "heel, to follow closely, to go with, to marry sb (of woman), with, towards, as (compared to), from (different from), and (in addition to)"},
    {"word": "更","answer": "ㄍㄥ,ㄍㄥˋ,geng1,geng4","eng": "more, even more, further, still, still more"},
    {"word": "公园","answer": "ㄍㄨㄥㄩㄢˊ,gong1yuan2","eng": "public park, CL:場[chǎng]"},
    {"word": "故事","answer": "ㄍㄨˋㄕˋ,ㄍㄨˋㄕ˙,gu4shi4,gu4shi5","eng": "narrative, story, tale"},
    {"word": "刮（颳）","answer": "ㄍㄨㄚ,gua1","eng": "to blow (of the wind)"},
    {"word": "关","answer": "ㄍㄨㄢ,guan1","eng": "mountain pass, to close, to shut, to turn off, to concern, to involve"},
    {"word": "关系","answer": "ㄍㄨㄢㄒㄧˋ,guan1xi4","eng": "variant of 關係|关系[guān xì]"},
    {"word": "关心","answer": "ㄍㄨㄢㄒㄧㄣ,guan1xin1","eng": "to care for sth, caring, concerned"},
    {"word": "关于","answer": "ㄍㄨㄢㄩˊ,guan1yu2","eng": "pertaining to, concerning, regarding, with regards to, about, a matter of"},
    {"word": "国家","answer": "ㄍㄨㄛˊㄐㄧㄚ,guo2jia1","eng": "country, nation, state, CL:個[gè]"},
    {"word": "果汁","answer": "ㄍㄨㄛˇㄓ,guo3zhi1","eng": "fruit juice"},
    {"word": "过去","answer": "ㄍㄨㄛˋㄑㄩˋ,guo4qu4","eng": "(in the) past, former, previous, to go over, to pass by"},
    {"word": "还是","answer": "ㄏㄞˊㄕˋ,hai2shi4","eng": "or, still, nevertheless, had better"},
    {"word": "害怕","answer": "ㄏㄞˋㄆㄚˋ,hai4pa4","eng": "to be afraid, to be scared"},
    {"word": "河","answer": "ㄏㄜˊ,he2","eng": "river, CL:條,道[dào]"},
    {"word": "黑板","answer": "ㄏㄟㄅㄢˇ,hei1ban3","eng": "blackboard, CL:塊,個[gè]"},
    {"word": "护照","answer": "ㄏㄨˋㄓㄠˋ,hu4zhao4","eng": "passport, CL:本,個[gè]"},
    {"word": "花","answer": "ㄏㄨㄚ,hua1","eng": "flower, blossom, CL:朵,支,束,把,盆,簇[cù], fancy pattern, florid, to spend (money, time)"},
    {"word": "花园","answer": "ㄏㄨㄚㄩㄢˊ,hua1yuan2","eng": "garden, CL:座,個[gè]"},
    {"word": "画","answer": "ㄏㄨㄚˋ,hua4","eng": "to draw, picture, painting, CL:幅,張[zhāng]"},
    {"word": "坏","answer": "ㄏㄨㄞˋ,huai4","eng": "bad, spoiled, broken, to break down"},
    {"word": "环境","answer": "ㄏㄨㄢˊㄐㄧㄥˋ,huan2jing4","eng": "environment, circumstances, surroundings, CL:個[gè], ambient"},
    {"word": "换","answer": "ㄏㄨㄢˋ,huan4","eng": "to change, to exchange"},
    {"word": "黄","answer": "ㄏㄨㄤˊ,huang2","eng": "yellow, pornographic, to fall through"},
    {"word": "会议","answer": "ㄏㄨㄟˋㄧˋ,hui4yi4","eng": "meeting, conference, CL:場,屆[jiè]"},
    {"word": "或者","answer": "ㄏㄨㄛˋㄓㄜˇ,huo4zhe3","eng": "or, possibly, maybe, perhaps"},
    {"word": "机会","answer": "ㄐㄧㄏㄨㄟˋ,ji1hui4","eng": "opportunity, chance, occasion, CL:個[gè]"},
    {"word": "几乎","answer": "ㄐㄧㄏㄨ,ji1hu1","eng": "almost, nearly, practically"},
    {"word": "极","answer": "ㄐㄧˊ,ji2","eng": "extremely, pole (geography, physics), utmost, top"},
    {"word": "记得","answer": "ㄐㄧˋㄉㄜ˙,ji4de5","eng": "to remember"},
    {"word": "季节","answer": "ㄐㄧˋㄐㄧㄝˊ,ji4jie2","eng": "time, season, period, CL:個[gè]"},
    {"word": "检查","answer": "ㄐㄧㄢˇㄔㄚˊ,jian3cha2","eng": "inspection, to examine, to inspect, CL:次[cì]"},
    {"word": "简单","answer": "ㄐㄧㄢˇㄉㄢ,jian3dan1","eng": "simple, not complicated"},
    {"word": "见面","answer": "ㄐㄧㄢˋㄇㄧㄢˋ,jian4mian4","eng": "to meet, to see sb, CL:次[cì]"},
    {"word": "健康","answer": "ㄐㄧㄢˋㄎㄤ,jian4kang1","eng": "health, healthy"},
    {"word": "讲","answer": "ㄐㄧㄤˇ,jiang3","eng": "to speak, to explain, to negotiate, to emphasise, to be particular about, as far as sth is concerned, speech, lecture"},
    {"word": "教","answer": "ㄐㄧㄠˋ,ㄐㄧㄠ,jiao4,jiao1","eng": "to teach"},
    {"word": "脚","answer": "ㄐㄧㄠˇ,jiao3","eng": "foot, leg, base, kick, CL:雙,隻[zhī]"},
    {"word": "角","answer": "ㄐㄧㄠˇ,ㄐㄩㄝˊ,ㄌㄨˋ,jiao3,jue2,lu4","eng": "angle, corner, horn, horn-shaped, unit of money equal to 0.1 yuan, CL:個[gè]"},
    {"word": "接","answer": "ㄐㄧㄝ,jie1","eng": "to receive, to answer (the phone), to meet or welcome sb, to connect, to catch, to join, to extend, to take one's turn on duty, to take over for sb"},
    {"word": "街道","answer": "ㄐㄧㄝㄉㄠˋ,jie1dao4","eng": "street, CL:條[tiáo], subdistrict, residential district"},
    {"word": "节目","answer": "ㄐㄧㄝˊㄇㄨˋ,jie2mu4","eng": "program, item (on a program), CL:臺,個,套[tào]"},
    {"word": "节日","answer": "ㄐㄧㄝˊㄖˋ,jie2ri4","eng": "holiday, festival, CL:個[gè]"},
    {"word": "结婚","answer": "ㄐㄧㄝˊㄏㄨㄣ,jie2hun1","eng": "to marry, to get married, CL:次[cì]"},
    {"word": "结束","answer": "ㄐㄧㄝˊㄕㄨˋ,jie2shu4","eng": "termination, to finish, to end, to conclude, to close"},
    {"word": "解决","answer": "ㄐㄧㄝˇㄐㄩㄝˊ,jie3jue2","eng": "to settle (a dispute), to resolve, to solve, to dispose of, to dispatch"},
    {"word": "借","answer": "ㄐㄧㄝˋ,jie4","eng": "to lend, to borrow, by means of, to take (an opportunity)"},
    {"word": "经常","answer": "ㄐㄧㄥㄔㄤˊ,jing1chang2","eng": "day to day, everyday, daily, frequently, constantly, regularly, often"},
    {"word": "经过","answer": "ㄐㄧㄥㄍㄨㄛˋ,jing1guo4","eng": "to pass, to go through, process, course, CL:個[gè]"},
    {"word": "经理","answer": "ㄐㄧㄥㄌㄧˇ,jing1li3","eng": "manager, director, CL:個,位,名[míng]"},
    {"word": "久","answer": "ㄐㄧㄡˇ,jiu3","eng": "(long) time, (long) duration of time"},
    {"word": "旧","answer": "ㄐㄧㄡˋ,jiu4","eng": "old, opposite: new 新, former, worn (with age)"},
    {"word": "举行","answer": "ㄐㄩˇㄒㄧㄥˊ,ju3xing2","eng": "to hold (a meeting, ceremony etc)"},
    {"word": "句子","answer": "ㄐㄩˋㄗ˙,ju4zi5","eng": "sentence, CL:個[gè]"},
    {"word": "决定","answer": "ㄐㄩㄝˊㄉㄧㄥˋ,jue2ding4","eng": "to decide (to do something), to resolve, decision, CL:個,項[xiàng], certainly"},
    {"word": "渴","answer": "ㄎㄜˇ,ㄏㄜˊ,ke3,he2","eng": "thirsty"},
    {"word": "可爱","answer": "ㄎㄜˇㄞˋ,ke3ai4","eng": "adorable, cute, lovely"},
    {"word": "刻","answer": "ㄎㄜˋ,ke4","eng": "quarter (hour), moment, to carve, to engrave, to cut, oppressive, classifier for short time intervals"},
    {"word": "客人","answer": "ㄎㄜˋㄖㄣˊ,ke4ren2","eng": "visitor, guest, customer, client, CL:位[wèi]"},
    {"word": "空调","answer": "ㄎㄨㄥㄊㄧㄠˊ,kong1tiao2","eng": "air conditioning"},
    {"word": "口","answer": "ㄎㄡˇ,kou3","eng": "mouth, classifier for things with mouths (people, domestic animals, cannons, wells etc), classifier for bites or mouthfuls"},
    {"word": "哭","answer": "ㄎㄨ,ku1","eng": "to cry, to weep"},
    {"word": "裤","answer": "ㄎㄨˋ,ku4","eng": "trousers, pants, CL:條[tiáo]"},
    {"word": "筷子","answer": "ㄎㄨㄞˋㄗ˙,kuai4zi5","eng": "chopsticks, CL:對,根,把,雙[shuāng]"},
    {"word": "蓝","answer": "ㄌㄢˊ,lan2","eng": "blue, indigo plant"},
    {"word": "老","answer": "ㄌㄠˇ,lao3","eng": "prefix used before the surname of a person or a numeral indicating the order of birth of the children in a family or to indicate affection or familiarity, old (of people), venerable (person), experienced, of long standing, always, all the time, of the past, very, outdated, (of meat etc) tough"},
    {"word": "离开","answer": "ㄌㄧˊㄎㄞ,li2kai1","eng": "to depart, to leave"},
    {"word": "礼物","answer": "ㄌㄧˇㄨˋ,li3wu4","eng": "gift, present, CL:件,個,份[fèn]"},
    {"word": "历史","answer": "ㄌㄧˋㄕˇ,li4shi3","eng": "history, CL:門,段[duàn]"},
    {"word": "脸","answer": "ㄌㄧㄢˇ,lian3","eng": "face, CL:張,個[gè]"},
    {"word": "练习","answer": "ㄌㄧㄢˋㄒㄧˊ,lian4xi2","eng": "exercise, drill, practice, CL:個[gè]"},
    {"word": "辆","answer": "ㄌㄧㄤˋ,liang4","eng": "classifier for vehicles"},
    {"word": "了解","answer": "ㄌㄧㄠˇㄐㄧㄝˇ,liao3jie3","eng": "to understand, to realize, to find out"},
    {"word": "邻居","answer": "ㄌㄧㄣˊㄐㄩ,lin2ju1","eng": "neighbor, next door, CL:個[gè]"},
    {"word": "楼","answer": "ㄌㄡˊ,lou2","eng": "house with more than 1 story, storied building, floor, CL:層,座,棟[dòng]"},
    {"word": "绿","answer": "ㄌㄩˋ,ㄌㄨˋ,lü4,lu4","eng": "green"},
    {"word": "马","answer": "ㄇㄚˇ,ma3","eng": "horse, CL:匹pi, horse or cavalry piece in Chinese chess, knight in Western chess"},
    {"word": "马上","answer": "ㄇㄚˇㄕㄤˋ,ma3shang4","eng": "at once, right away, immediately, on horseback (i.e. by military force)"},
    {"word": "满意","answer": "ㄇㄢˇㄧˋ,man3yi4","eng": "satisfied, pleased, to one's satisfaction"},
    {"word": "帽子","answer": "ㄇㄠˋㄗ˙,mao4zi5","eng": "hat, cap, (fig.) label, bad name, CL:頂[dǐng]"},
    {"word": "米","answer": "ㄇㄧˇ,mi3","eng": "rice, CL:粒[lì], meter (classifier)"},
    {"word": "面包","answer": "ㄇㄧㄢˋㄅㄠ,mian4bao1","eng": "bread, CL:片,袋,塊[kuài]"},
    {"word": "面条","answer": "ㄇㄧㄢˋㄊㄧㄠˊ,mian4tiao2","eng": "noodles"},
    {"word": "明白","answer": "ㄇㄧㄥˊㄅㄞˊ,ming2bai2","eng": "clear, obvious, unequivocal, to understand, to realize"},
    {"word": "拿","answer": "ㄋㄚˊ,na2","eng": "to hold, to seize, to catch, to apprehend, to take"},
    {"word": "奶奶","answer": "ㄋㄞˇㄋㄞ˙,nai3nai5","eng": "(informal) grandma (paternal grandmother), (respectful) mistress of the house, CL:位[wèi]"},
    {"word": "南","answer": "ㄋㄢˊ,ㄋㄚˊ,nan2,na2","eng": "south"},
    {"word": "难","answer": "ㄋㄢˊ,ㄋㄢˋ,ㄋㄨㄛˊ,nan2,nan4,nuo2","eng": "difficult (to...), problem, difficulty, difficult, not good"},
    {"word": "难过","answer": "ㄋㄢˊㄍㄨㄛˋ,nan2guo4","eng": "to feel sad, to feel unwell, (of life) to be difficult"},
    {"word": "年级","answer": "ㄋㄧㄢˊㄐㄧˊ,nian2ji2","eng": "grade, CL:個[gè]"},
    {"word": "年轻","answer": "ㄋㄧㄢˊㄑㄧㄥ,nian2qing1","eng": "young"},
    {"word": "鸟","answer": "ㄋㄧㄠˇ,ㄉㄧㄠˇ,niao3,diao3","eng": "bird, CL:隻,群[qún]"},
    {"word": "努力","answer": "ㄋㄨˇㄌㄧˋ,nu3li4","eng": "great effort, to strive, to try hard"},
    {"word": "爬山","answer": "ㄆㄚˊㄕㄢ,pa2shan1","eng": "to climb a mountain, to mountaineer, hiking, mountaineering"},
    {"word": "盘","answer": "ㄆㄢˊ,pan2","eng": "tray, plate, dish, CL:個[gè]"},
    {"word": "胖","answer": "ㄆㄤˋ,ㄆㄢˊ,pang4,pan2","eng": "fat, plump"},
    {"word": "啤酒","answer": "ㄆㄧˊㄐㄧㄡˇ,pi2jiu3","eng": "beer, CL:杯,瓶,罐,桶,缸[gāng]"},
    {"word": "葡萄","answer": "ㄆㄨˊㄊㄠˊ,pu2tao2","eng": "grape"},
    {"word": "普通话","answer": "ㄆㄨˇㄊㄨㄥㄏㄨㄚˋ,pu3tong1hua4","eng": "Mandarin (common language), Putonghua (common speech of the Chinese language), ordinary speech"},
    {"word": "骑","answer": "ㄑㄧˊ,ㄐㄧˋ,qi2,ji4","eng": "to ride (an animal or bike), to sit astride"},
    {"word": "其实","answer": "ㄑㄧˊㄕˊ,qi2shi2","eng": "actually, in fact, really"},
    {"word": "其他","answer": "ㄑㄧˊㄊㄚ,qi2ta1","eng": "other, the others, else, other than (that person), in addition to the person mentioned above"},
    {"word": "奇怪","answer": "ㄑㄧˊㄍㄨㄞˋ,qi2guai4","eng": "strange, odd, to marvel, to be baffled"},
    {"word": "铅笔","answer": "ㄑㄧㄢㄅㄧˇ,qian1bi3","eng": "(lead) pencil, CL:支,枝,桿[gǎn]"},
    {"word": "清楚","answer": "ㄑㄧㄥㄔㄨˇ,qing1chu3","eng": "clear, distinct, to understand thoroughly, to be clear about"},
    {"word": "秋","answer": "ㄑㄧㄡ,qiu1","eng": "a swing"},
    {"word": "裙","answer": "ㄑㄩㄣˊ,qun2","eng": "skirt, CL:條[tiáo]"},
    {"word": "然后","answer": "ㄖㄢˊㄏㄡˋ,ran2hou4","eng": "after, then (afterwards), after that, afterwards"},
    {"word": "热情","answer": "ㄖㄜˋㄑㄧㄥˊ,re4qing2","eng": "cordial, enthusiastic, passion, passionate, passionately"},
    {"word": "认为","answer": "ㄖㄣˋㄨㄟˊ,ren4wei2","eng": "to believe, to think, to consider, to feel"},
    {"word": "认真","answer": "ㄖㄣˋㄓㄣ,ren4zhen1","eng": "conscientious, earnest, serious, to take seriously, to take to heart"},
    {"word": "容易","answer": "ㄖㄨㄥˊㄧˋ,rong2yi4","eng": "easy, likely, liable (to)"},
    {"word": "如果","answer": "ㄖㄨˊㄍㄨㄛˇ,ru2guo3","eng": "if, in case, in the event that"},
    {"word": "伞","answer": "ㄙㄢˇ,san3","eng": "umbrella, parasol, CL:把[bǎ]"},
    {"word": "上网","answer": "ㄕㄤˋㄨㄤˇ,shang4wang3","eng": "to be on the internet, to stretch a net (in a sports game or for covering sth), to be netted (of fish)"},
    {"word": "生气","answer": "ㄕㄥㄑㄧˋ,sheng1qi4","eng": "angry, mad, offended, animated, to get angry, to be enraged, to take offense, animation"},
    {"word": "声音","answer": "ㄕㄥㄧㄣ,sheng1yin1","eng": "voice, sound, CL:個[gè]"},
    {"word": "使","answer": "ㄕˇ,shi3","eng": "to make, to cause, to enable, to use, to employ, to send, to instruct sb to do sth, envoy, messenger"},
    {"word": "世界","answer": "ㄕˋㄐㄧㄝˋ,shi4jie4","eng": "world, CL:個[gè]"},
    {"word": "瘦","answer": "ㄕㄡˋ,shou4","eng": "thin, to lose weight, (of clothing) tight, (of meat) lean, (of land) unproductive"},
    {"word": "舒服","answer": "ㄕㄨㄈㄨˊ,shu1fu2","eng": "comfortable, feeling well"},
    {"word": "叔叔","answer": "ㄕㄨˊㄕㄨ˙,shu2shu5","eng": "father's younger brother, uncle, Taiwan pr. [shú shu], CL:個[gè]"},
    {"word": "树","answer": "ㄕㄨˋ,shu4","eng": "tree, CL:棵[kē], to cultivate, to set up"},
    {"word": "数学","answer": "ㄕㄨˋㄒㄩㄝˊ,shu4xue2","eng": "mathematics, mathematical"},
    {"word": "刷","answer": "ㄕㄨㄚ,shua1","eng": "to brush, to paint, to daub, to paste up, to skip class (of students), to fire from a job"},
    {"word": "双","answer": "ㄕㄨㄤ,shuang1","eng": "two, double, pair, both"},
    {"word": "水平","answer": "ㄕㄨㄟˇㄆㄧㄥˊ,shui3ping2","eng": "level (of achievement etc), standard, horizontal"},
    {"word": "司机","answer": "ㄙㄐㄧ,si1ji1","eng": "chauffeur, driver, CL:個[gè]"},
    {"word": "虽然","answer": "ㄙㄨㄟㄖㄢˊ,sui1ran2","eng": "although, even though, even if"},
    {"word": "太阳","answer": "ㄊㄞˋㄧㄤˊ,tai4yang2","eng": "sun, CL:個[gè]"},
    {"word": "糖","answer": "ㄊㄤˊ,tang2","eng": "sugar, sweets, candy, CL:顆,塊[kuài]"},
    {"word": "特别","answer": "ㄊㄜˋㄅㄧㄝˊ,te4bie2","eng": "especially, special, particular, unusual"},
    {"word": "疼","answer": "ㄊㄥˊ,teng2","eng": "(it) hurts, sore, to love dearly"},
    {"word": "提高","answer": "ㄊㄧˊㄍㄠ,ti2gao1","eng": "to raise, to increase"},
    {"word": "体育","answer": "ㄊㄧˇㄩˋ,ti3yu4","eng": "sports, physical education"},
    {"word": "甜","answer": "ㄊㄧㄢˊ,tian2","eng": "sweet"},
    {"word": "条","answer": "ㄊㄧㄠˊ,tiao2","eng": "strip, item, article, clause (of law or treaty), classifier for long thin things (ribbon, river, road, trousers etc)"},
    {"word": "同事","answer": "ㄊㄨㄥˊㄕˋ,tong2shi4","eng": "colleague, co-worker, CL:個,位[wèi]"},
    {"word": "同意","answer": "ㄊㄨㄥˊㄧˋ,tong2yi4","eng": "to agree, to consent, to approve"},
    {"word": "头发","answer": "ㄊㄡˊㄈㄚˇ,tou2fa3","eng": "hair (on the head)"},
    {"word": "突然","answer": "ㄊㄨˊㄖㄢˊ,tu2ran2","eng": "sudden, abrupt, unexpected"},
    {"word": "图书馆","answer": "ㄊㄨˊㄕㄨㄍㄨㄢˇ,tu2shu1guan3","eng": "library, CL:家,個[gè]"},
    {"word": "腿","answer": "ㄊㄨㄟˇ,tui3","eng": "leg, CL:條[tiáo]"},
    {"word": "完成","answer": "ㄨㄢˊㄔㄥˊ,wan2cheng2","eng": "to complete, to accomplish"},
    {"word": "碗","answer": "ㄨㄢˇ,wan3","eng": "bowl, cup, CL:隻,個[gè]"},
    {"word": "万","answer": "ㄨㄢˋ,wan4","eng": "ten thousand, a great number"},
    {"word": "忘记","answer": "ㄨㄤˋㄐㄧˋ,wang4ji4","eng": "to forget"},
    {"word": "为了","answer": "ㄨㄟˋㄌㄜ˙,wei4le5","eng": "in order to, for the purpose of, so as to"},
    {"word": "为什么","answer": "ㄨㄟˋㄕㄣˊㄇㄜ˙,wei4shen2me5","eng": "why?, for what reason?"},
    {"word": "位","answer": "ㄨㄟˋ,wei4","eng": "position, location, place, seat, classifier for people (honorific), classifier for binary bits (e.g. 十六位 16-bit or 2 bytes)"},
    {"word": "文化","answer": "ㄨㄣˊㄏㄨㄚˋ,wen2hua4","eng": "culture, civilization, cultural, CL:個,種[zhǒng]"},
    {"word": "西","answer": "ㄒㄧ,xi1","eng": "west"},
    {"word": "习惯","answer": "ㄒㄧˊㄍㄨㄢˋ,xi2guan4","eng": "habit, custom, usual practice, to be used to, CL:個[gè]"},
    {"word": "洗手间","answer": "ㄒㄧˇㄕㄡˇㄐㄧㄢ,xi3shou3jian1","eng": "toilet, lavatory, washroom"},
    {"word": "洗澡","answer": "ㄒㄧˇㄗㄠˇ,xi3zao3","eng": "to bathe, to take a shower"},
    {"word": "夏","answer": "ㄒㄧㄚˋ,ㄐㄧㄚˇ,xia4,jia3","eng": "summer"},
    {"word": "先","answer": "ㄒㄧㄢ,xian1","eng": "early, prior, former, in advance, first"},
    {"word": "香蕉","answer": "ㄒㄧㄤㄐㄧㄠ,xiang1jiao1","eng": "banana, CL:枝,根,個,把[bǎ]"},
    {"word": "相同","answer": "ㄒㄧㄤㄊㄨㄥˊ,xiang1tong2","eng": "identical, same"},
    {"word": "相信","answer": "ㄒㄧㄤㄒㄧㄣˋ,xiang1xin4","eng": "to be convinced (that sth is true), to believe, to accept sth as true"},
    {"word": "像","answer": "ㄒㄧㄤˋ,xiang4","eng": "to resemble, to be like, to look as if, such as, appearance, image, portrait, image under a mapping (math.)"},
    {"word": "小心","answer": "ㄒㄧㄠˇㄒㄧㄣ,xiao3xin1","eng": "to be careful, to take care"},
    {"word": "校长","answer": "ㄒㄧㄠˋㄓㄤˇ,xiao4zhang3","eng": "(college, university) president, headmaster, CL:個,位,名[míng]"},
    {"word": "鞋","answer": "ㄒㄧㄝˊ,xie2","eng": "shoe, CL:雙,隻[zhī]"},
    {"word": "新闻","answer": "ㄒㄧㄣㄨㄣˊ,xin1wen2","eng": "news, CL:條,個[gè]"},
    {"word": "新鲜","answer": "ㄒㄧㄣㄒㄧㄢ,xin1xian1","eng": "fresh (experience, food etc), freshness, novel, uncommon"},
    {"word": "信","answer": "ㄒㄧㄣˋ,xin4","eng": "letter, mail, CL:封[fēng], to trust, to believe, to profess faith in, truthful, confidence, trust, at will, at random"},
    {"word": "行李箱","answer": "ㄒㄧㄥˊㄌㄧˇㄒㄧㄤ,xing2li3xiang1","eng": "suitcase"},
    {"word": "兴趣","answer": "ㄒㄧㄥˋㄑㄩˋ,xing4qu4","eng": "interest (desire to know about sth), interest (thing in which one is interested), hobby, CL:個[gè]"},
    {"word": "熊猫","answer": "ㄒㄩㄥˊㄇㄠ,xiong2mao1","eng": "panda, CL:隻[zhī]"},
    {"word": "需要","answer": "ㄒㄩㄧㄠˋ,xu1yao4","eng": "to need, to want, to demand, to require, requirement, need"},
    {"word": "选择","answer": "ㄒㄩㄢˇㄗㄜˊ,xuan3ze2","eng": "to select, to pick, choice, option, alternative"},
    {"word": "眼镜","answer": "ㄧㄢˇㄐㄧㄥˋ,yan3jing4","eng": "spectacles, eyeglasses, CL:副[fù]"},
    {"word": "要求","answer": "ㄧㄠㄑㄧㄡˊ,yao1qiu2","eng": "to request, to require, to stake a claim, to ask, to demand, CL:點[diǎn]"},
    {"word": "爷爷","answer": "ㄧㄝˊㄧㄝ˙,ye2ye5","eng": "(informal) father's father, paternal grandfather, CL:個[gè]"},
    {"word": "一定","answer": "ㄧˊㄉㄧㄥˋ,yi2ding4","eng": "surely, certainly, necessarily, fixed, a certain (extent etc), given, particular, must"},
    {"word": "一共","answer": "ㄧˊㄍㄨㄥˋ,yi2gong4","eng": "altogether"},
    {"word": "一会","answer": "ㄧˋㄏㄨㄟˇ,yi4hui3","eng": "a while, also pr. [yī huǐ r]"},
    {"word": "一样","answer": "ㄧˊㄧㄤˋ,yi2yang4","eng": "same, like, equal to, the same as, just like"},
    {"word": "以后","answer": "ㄧˇㄏㄡˋ,yi3hou4","eng": "after, later, afterwards, following, later on, in the future"},
    {"word": "以前","answer": "ㄧˇㄑㄧㄢˊ,yi3qian2","eng": "before, formerly, previous, ago"},
    {"word": "以为","answer": "ㄧˇㄨㄟˊ,yi3wei2","eng": "to believe, to think, to consider, to be under the impression"},
    {"word": "一般","answer": "ㄧˋㄅㄢ,yi4ban1","eng": "same, ordinary, so-so, common, general, generally, in general"},
    {"word": "一边","answer": "ㄧˋㄅㄧㄢ,yi4bian1","eng": "one side, either side, on the one hand, on the other hand, doing while"},
    {"word": "一直","answer": "ㄧˋㄓˊ,yi4zhi2","eng": "straight (in a straight line), continuously, always, from the beginning of ... up to ..., all along"},
    {"word": "音乐","answer": "ㄧㄣㄩㄝˋ,yin1yue4","eng": "music, CL:張,曲,段[duàn]"},
    {"word": "银行","answer": "ㄧㄣˊㄏㄤˊ,yin2hang2","eng": "bank, CL:家,個[gè]"},
    {"word": "应该","answer": "ㄧㄥㄍㄞ,ying1gai1","eng": "ought to, should, must"},
    {"word": "影响","answer": "ㄧㄥˇㄒㄧㄤˇ,ying3xiang3","eng": "an influence, an effect, to influence, to affect (usually adversely), to disturb, CL:股[gǔ]"},
    {"word": "用","answer": "ㄩㄥˋ,yong4","eng": "to use, to employ, to have to, to eat or drink, expense or outlay, usefulness, hence, therefore"},
    {"word": "游戏","answer": "ㄧㄡˊㄒㄧˋ,you2xi4","eng": "game, CL:場[chǎng], to play"},
    {"word": "有名","answer": "ㄧㄡˇㄇㄧㄥˊ,you3ming2","eng": "famous, well-known"},
    {"word": "又","answer": "ㄧㄡˋ,you4","eng": "(once) again, also, both... and..., and yet, (used for emphasis) anyway"},
    {"word": "遇到","answer": "ㄩˋㄉㄠˋ,yu4dao4","eng": "to meet, to run into, to come across"},
    {"word": "愿意","answer": "ㄩㄢˋㄧˋ,yuan4yi4","eng": "to wish, to want, ready, willing (to do sth)"},
    {"word": "越","answer": "ㄩㄝˋ,yue4","eng": "to exceed, to climb over, to surpass, the more... the more"},
    {"word": "月亮","answer": "ㄩㄝˋㄌㄧㄤˋ,yue4liang4","eng": "moon"},
    {"word": "云（雲）","answer": "ㄩㄣˊ,yun2","eng": "cloud, CL:朵[duǒ]"},
    {"word": "站","answer": "ㄓㄢˋ,zhan4","eng": "station, to stand, to halt, to stop, branch of a company or organization, website"},
    {"word": "着急","answer": "ㄓㄠㄐㄧˊ,zhao1ji2","eng": "to worry, to feel anxious, Taiwan pron. [zhāo jí]"},
    {"word": "照顾","answer": "ㄓㄠˋㄍㄨˋ,zhao4gu4","eng": "to take care of, to show consideration, to attend to, to look after"},
    {"word": "照片","answer": "ㄓㄠˋㄆㄧㄢˋ,zhao4pian4","eng": "photograph, picture, CL:張,套,幅[fú]"},
    {"word": "照相机","answer": "ㄓㄠˋㄒㄧㄤˋㄐㄧ,zhao4xiang4ji1","eng": "camera, CL:個,架,部,台,隻[zhī]"},
    {"word": "只（隻）","answer": "ㄓˇ,ㄓ,zhi3,zhi1","eng": "classifier for birds and certain animals, one of a pair, some utensils, vessels etc"},
    {"word": "只（祗）","answer": "ㄓˇ,ㄓ,zhi3,zhi1","eng": "but, only"},
    {"word": "终于","answer": "ㄓㄨㄥㄩˊ,zhong1yu2","eng": "at last, in the end, finally, eventually"},
    {"word": "中间","answer": "ㄓㄨㄥㄐㄧㄢ,zhong1jian1","eng": "between, intermediate, mid, middle"},
    {"word": "种","answer": "ㄓㄨㄥˇ,ㄓㄨㄥˋ,zhong3,zhong4","eng": "abbr. for 物種|物种, genus, race, seed, breed, species, strain, kind, type, has guts (i.e. courage), nerve, classifier for types: kind, sort, classifier for languages"},
    {"word": "重要","answer": "ㄓㄨㄥˋㄧㄠˋ,zhong4yao4","eng": "important, significant, major"},
    {"word": "周末","answer": "ㄓㄡㄇㄛˋ,zhou1mo4","eng": "weekend"},
    {"word": "主要","answer": "ㄓㄨˇㄧㄠˋ,zhu3yao4","eng": "main, principal, major, primary"},
    {"word": "祝","answer": "ㄓㄨˋ,zhu4","eng": "to wish, to express good wishes, to pray, (old) wizard"},
    {"word": "注意","answer": "ㄓㄨˋㄧˋ,zhu4yi4","eng": "to take note of, to pay attention to"},
    {"word": "字典","answer": "ㄗˋㄉㄧㄢˇ,zi4dian3","eng": "dictionary, character dictionary, CL:本[běn]"},
    {"word": "自己","answer": "ㄗˋㄐㄧˇ,zi4ji3","eng": "oneself, one's own"},
    {"word": "总是","answer": "ㄗㄨㄥˇㄕˋ,zong3shi4","eng": "always"},
    {"word": "最近","answer": "ㄗㄨㄟˋㄐㄧㄣˋ,zui4jin4","eng": "recent, recently, these days, latest, soon, nearest (of locations), shortest (of routes)"},
    {"word": "作业","answer": "ㄗㄨㄛˋㄧㄝˋ,zuo4ye4","eng": "school assignment, homework, work, task, operation, CL:個[gè], to operate"},
    {"word": "作用","answer": "ㄗㄨㄛˋㄩㄥˋ,zuo4yong4","eng": "to act on, to affect, action, function, activity, impact, result, effect, purpose, intent, to play a role, corresponds to English -ity, -ism, -ization, CL:個[gè]"}
  ]